import re
import os

jsx_content = """
    {
        key: 'start', label: 'Getting Started', icon: Gauge, color: 'indigo',
        items: [
            { n: 'One-Click Interactive Demo', d: 'Launch a fully pre-populated demo store from the landing page — test checkout, reports and dummy products with no account.' },
            { n: '14-Day Free Trial', d: 'Explore the full platform for 14 days with no credit card required.' },
            { n: 'Instant Store Creator', d: 'Start setup by entering only your store name — no servers or technical knowledge needed.' },
            { n: 'Smart Industry Seeding', d: 'Auto-imports standard units, tax settings and categories tailored to your industry (Retail, Grocery, F&B, Fashion, Hard Goods).' },
            { n: 'Dark Theme (Midnight Nebula)', d: 'Premium glassmorphic dark dashboard with amber accents — easy on cashiers’ eyes during long shifts.' },
            { n: 'Light Theme', d: 'Crisp, high-contrast layout designed for bright storefront environments.' },
            { n: 'Multi-Store Hub Dashboard', d: 'Central launchpad showing all branches with one-click switching between them.' },
            { n: 'Granular Multi-Store Roles', d: 'Be Owner in Store A, Manager in Store B and read-only Viewer in Store C — from one account.' },
            { n: 'Cashier PIN Login', d: 'Staff log in with a fast 4-digit PIN — no retyping email and password between shifts.' },
            { n: 'Progressive Web App (PWA)', d: 'Install VenQore on Windows, Android or iOS as a native-feeling app.' },
            { n: 'Self-Guiding Setup Tour', d: 'Interactive onboarding that highlights buttons and walks new staff through their first sale.' },
            { n: 'Coupon Code Upgrades', d: 'Apply, stack and upgrade license voucher codes to instantly unlock higher limits or store slots.' },
            { n: 'Hardware Status Badge', d: 'Live indicator showing whether thermal printers and payment hardware are connected and ready.' },
            { n: 'One-Click Cache Refresh', d: 'Instantly optimize local performance so every screen loads at full speed.' },
            { n: 'Owner Profile Card', d: 'See your active tier, remaining trial days and login details at a glance.' },
            { n: 'Test Data Wipe', d: 'Securely erase demo/test transactions while preserving tax rules, settings and staff accounts.' },
            { n: 'Security Activity Log', d: 'Traces staff IP addresses, login timestamps and locations for every sensitive action.' },
        ],
    },
    {
        key: 'pos', label: 'Point of Sale', icon: ShoppingCart, color: 'amber',
        items: [
            { n: 'Instant Barcode Scanner', d: 'Scan product tags to add items to the cart instantly — no mouse or keyboard.' },
            { n: 'Serial & IMEI Scanner', d: 'Prompts operators to scan device identifiers (phone IMEIs, appliance serials) at checkout.' },
            { n: 'Keyboard-First Checkout', d: 'F1 search, F2 quantity, F3 discount, F4 checkout — process whole queues without a mouse.' },
            { n: 'Senior Mode Accessibility', d: 'Increases font sizes by 40% with high-contrast, traffic-light colors for easier reading.' },
            { n: 'Color-Coded Price & Qty', d: 'Green pricing, blue quantities — prevents numerical confusion at a glance.' },
            { n: 'Owner Profit Peek', d: 'Drag down on the bill total to reveal the live profit margin of the active cart, hidden from the customer.' },
            { n: 'Multi-Tab Customer Checkout', d: 'Manage up to 10 active customer carts simultaneously, switchable via hotkeys.' },
            { n: 'Park & Recall (Hold Bill)', d: 'Put a cart on hold with a note (e.g. “Table 5”) while serving others, then recall it instantly.' },
            { n: 'In-Flight Product Creation', d: 'Add a new product to the catalog inside the checkout screen without losing the cart.' },
            { n: 'Cart Rescue & Session Protection', d: 'Active sales are saved to local memory — carts survive power cuts and browser crashes.' },
            { n: 'Auto-Applying Customer Discounts', d: 'Applies pre-negotiated discount agreements the moment a customer is selected.' },
            { n: 'Typo-Tolerant Search (OmniSearch)', d: 'Finds products even when the cashier misspells the name.' },
            { n: 'Automatic Cash Rounding', d: 'Rounds fractional change to the nearest valid denomination by local currency rules.' },
            { n: 'Multi-Account Split Payments', d: 'Accept any mix of Cash, Card, Bank Transfer and Store Credit in one transaction.' },
            { n: 'Daily Cash Register Audit', d: 'End-of-day cash-out wizard comparing the physical drawer against the system total.' },
            { n: 'Silent WebUSB Thermal Printing', d: 'Prints receipts directly to thermal hardware without browser popup dialogs.' },
            { n: 'Custom Thermal Roll Widths', d: 'Switch print templates between 80mm and 58mm thermal paper.' },
            { n: 'Receipt Cut-Line Padding', d: 'Adds blank lines so totals clear the paper cutter cleanly.' },
            { n: 'Dynamic Brand Colors on PDFs', d: 'Customize B2B invoice PDFs to match your corporate palette.' },
            { n: 'Print Column Toggles', d: 'Show/hide MRP, HSN codes, batch details, serials or savings by customer type.' },
            { n: 'Amount-to-Words Translation', d: 'Prints totals as written words (e.g. “Five Thousand Rupees Only”).' },
            { n: 'Tax Verification QR Codes', d: 'Embeds regional tax-compliance QR codes on printed receipts.' },
            { n: 'Branded Receipt Sync', d: 'Scales and positions store logos, headers and footer terms on all templates.' },
            { n: 'Auto-Deducting Composite Items', d: 'Selling a bundled/manufactured item deducts raw ingredients from stock in real time.' },
            { n: 'Negative Stock Alert & Lock', d: 'Warns — or hard-blocks — selling an item with empty inventory (configurable).' },
            { n: 'Service Fee & Freight Additions', d: 'Add delivery charges, assembly fees or service costs directly to invoices.' },
            { n: 'Automatic VAT / GST Calculation', d: 'Computes regional tax at the line-item level automatically — no cashier input.' },
            { n: 'Recent Invoices Panel', d: 'Shows the last 50 completed sales inside POS for quick refunds or reprints.' },
            { n: 'Cashier Change Calculator', d: 'Displays the exact change to hand back upon payment entry.' },
            { n: 'Barcode Label Print Factory', d: 'Design and print custom barcode stickers with name, logo, price and variant info.' },
            { n: 'Dynamic Label QR Codes', d: 'Embeds product QR codes on labels that link to your online storefront.' },
        ],
    },
    {
        key: 'receivables', label: 'Invoicing & Receivables', icon: Receipt, color: 'emerald',
        items: [
            { n: 'Customer Account Registry (Khata)', d: 'A dedicated ledger for every buyer — lifetime purchases, credit balance and payment history.' },
            { n: 'Customer Payments Log', d: 'Records cash, bank transfers and partial cheque deposits against specific invoices.' },
            { n: 'Customer Statement Generator', d: 'Clean downloadable PDF statements of purchases, returns and payments.' },
            { n: 'Aged Receivables Report', d: 'Categorizes outstanding balances into 30/60/90/120+ day buckets for collection priority.' },
            { n: 'WhatsApp & SMS Debt Reminders', d: 'One-click pre-formatted overdue-balance reminders from the customer ledger (coming soon).' },
            { n: 'Credit Limit Enforcement', d: 'Blocks credit sales when a customer’s balance exceeds their configured limit.' },
            { n: 'Multi-Payment Invoices', d: 'Accept partial payments across multiple sessions against one invoice.' },
            { n: 'Automatic Payment Allocation', d: 'Distributes lump-sum payments against the oldest unpaid invoices automatically.' },
            { n: 'Customer Lifetime Value Score', d: 'Ranks customers by total profit generated and sales volume.' },
            { n: 'Customer Wallet Credit', d: 'Returns refunds into a digital store wallet, keeping capital in your business.' },
            { n: 'Loyalty Points System', d: 'Awards purchase points automatically, redeemable as discounts on future orders.' },
            { n: 'Wholesale vs Retail Pricing Tiers', d: 'Assigns custom price lists per customer for automatic wholesale pricing.' },
            { n: 'B2B Proposal Builder', d: 'Creates corporate proposals and estimates with tracked “Valid Until” dates.' },
            { n: 'One-Click Quotation Conversion', d: 'Converts accepted quotes into posted tax invoices and updates the ledger in one click.' },
            { n: 'Tax-Inclusive / Exclusive Toggle', d: 'Switch B2B pricing between tax-inclusive and tax-exclusive display.' },
            { n: 'B2B Invoice Margin Display', d: 'Shows calculated profit per line item while building an invoice (owner-only).' },
            { n: 'Sales Return Vouchers', d: 'Generates formal return records and restores returned items to inventory.' },
            { n: 'Interactive B2B Invoice Designer', d: 'Customizable invoice layout with brand colors, logos, margins and signature fields.' },
            { n: 'Pre-Sales Inventory Reservation', d: 'Locks stock batches for pending orders without recording revenue until delivery.' },
            { n: 'Automated Recurring Invoicing', d: 'Schedules subscription invoices on daily, weekly, monthly or quarterly cycles.' },
            { n: 'Refund Reason Analysis', d: 'Tracks return reasons (damaged, wrong size…) to surface product quality patterns.' },
            { n: 'Tax-Exempt Customer Flag', d: 'Marks corporate clients as tax-exempt, skipping tax on their orders.' },
            { n: 'Customer Address Book', d: 'Stores billing, shipping and multiple warehouse addresses per customer.' },
            { n: 'A4 & Letter Invoice PDF Export', d: 'Generates clean professional A4 or US-Letter PDF invoices ready to email.' },
            { n: 'Outstanding Balance Dashboard', d: 'Widget showing total receivables across all customer accounts at a glance.' },
            { n: 'Unified Party Ledger', d: 'Merges a customer’s full sales, returns and payment history into one clean view.' },
            { n: 'Customer Milestone Tracker', d: 'Logs birthdays and anniversaries, sending automated greetings and discount vouchers.' },
            { n: 'Digital Gift Cards', d: 'Issues promotional digital gift cards with configurable balances and expiry dates.' },
            { n: 'Overdue Customer Highlights', d: 'Highlights past-due customer profiles in red across all ledger screens.' },
        ],
    },
    {
        key: 'procurement', label: 'Procurement & Payables', icon: Truck, color: 'cyan',
        items: [
            { n: 'Supplier Account Registry (Khata)', d: 'Vendor profile tracking what you owe each supplier and their payment terms.' },
            { n: 'Delayed Supplier Payments', d: 'Record stock on credit, track the balance and pay in installments.' },
            { n: 'Supplier Statement Generator', d: 'Downloadable PDF statements of purchases, returns and payments per vendor.' },
            { n: 'Aged Payables Directory', d: 'Categorizes vendor balances owed into 30/60/90/120+ day buckets.' },
            { n: 'Purchase Order Tracker', d: 'Tracks POs from Draft → Ordered → Partially Received → Fully Received.' },
            { n: 'Partial Shipment Intake', d: 'Logs split deliveries, keeping remaining quantities active.' },
            { n: 'Supplier Debit Notes', d: 'Formal debit notes when returning faulty stock to claim vendor credits.' },
            { n: 'Automated Cost Price Updater', d: 'Recalculates product cost prices automatically from each new supplier invoice.' },
            { n: 'Cost Price Increase Alert', d: 'Warns when a supplier charges more than their historical average.' },
            { n: 'Supplier Lead Time Tracker', d: 'Logs average delivery days between order and receipt per vendor.' },
            { n: 'Landing Cost Allocations', d: 'Distributes freight, customs and overhead across product batch costs accurately.' },
            { n: 'Supplier SKU Mapping', d: 'Maps supplier product codes to your internal catalog for fast reordering.' },
            { n: 'Inbound Expiry Date Tracking', d: 'Logs expiry dates at intake to prevent silent shelf expiry.' },
            { n: 'Purchase Returns Register', d: 'Processes vendor returns, adjusts stock and reduces payables automatically.' },
            { n: 'Auto-Generated Purchase Orders', d: 'Drafts POs for products that drop below safety stock levels.' },
            { n: 'Bulk Supplier Payments', d: 'Records one payment settled across multiple outstanding vendor invoices.' },
            { n: 'Bank-Linked Supplier Payments', d: 'Connects outgoing vendor payments to your cash and bank ledgers.' },
            { n: 'Custom Supplier Payment Terms', d: 'Set vendor-specific terms such as Net 15, Net 30 or Net 60.' },
            { n: 'Purchase Invoice Document Scanner', d: 'Upload and attach scanned invoices directly to purchase records for auditing.' },
            { n: 'Supplier Refund Tracker', d: 'Logs refund payments received back from suppliers for returned goods.' },
            { n: 'Tax-Inclusive Procurement Toggle', d: 'Switches purchase calculations between tax-inclusive and tax-exclusive formats.' },
            { n: 'Supplier Credit Limit Alerts', d: 'Highlights vendor accounts in red when balances approach their pre-set caps.' },
            { n: 'Outstanding Payables Dashboard', d: 'A widget showing total amounts owed across all suppliers in one view.' },
        ],
    },
    {
        key: 'inventory', label: 'Inventory & Warehouses', icon: Warehouse, color: 'blue',
        items: [
            { n: 'Multi-Warehouse Isolation (Godown)', d: 'Separate inventory balances for each godown, retail floor or wholesale depot.' },
            { n: 'Stock Transfer Vouchers', d: 'Logged transfers between locations, complete with printable waybills.' },
            { n: 'Product Variant Support', d: 'Tracks size, color and weight variants under single product groups.' },
            { n: 'Variant-Aware FIFO Costing', d: 'Separate cost pools per variant for accurate COGS from actual batch prices.' },
            { n: 'Batch Intake Number Tracking', d: 'Records manufacturing batch numbers at receipt for precise traceability.' },
            { n: 'Batch Expiry Warnings', d: 'Dashboard notifications for batches approaching their expiration date.' },
            { n: 'Stock Take Audit Wizard', d: 'Reconciles system inventory against physical counts, logging discrepancy causes.' },
            { n: 'Disaster & Asset Claim Manager', d: 'Logs stock lost to theft, fire or water, handles write-offs and tracks insurance claims.' },
            { n: 'Bill of Materials (BOM) Recipes', d: 'Defines composite items built from multiple raw stock components.' },
            { n: 'Auto-Assembly Cookbook', d: 'Deducts raw ingredients in real time when a manufactured item is sold.' },
            { n: 'Production Run Simulator', d: 'Checks raw materials to confirm whether a planned production run can complete.' },
            { n: 'Recipe History Archive', d: 'Preserves historical cost and component configs so past audits stay accurate.' },
            { n: 'Product History Timeline', d: 'Unified list of all purchase, sale and return movements per product.' },
            { n: 'Category Management Center', d: 'Hierarchical category groups for organizing thousands of items cleanly.' },
            { n: 'Low Stock Threshold Alerts', d: 'Configurable per-product triggers when inventory drops below reorder levels.' },
            { n: 'IMEI & Serial Lifecycle Tracking', d: 'Tracks device identifiers from supplier purchase through sale and returns.' },
            { n: 'Unit of Measure Converter', d: 'Buy in cartons, sell in pieces — convert between base and secondary units.' },
            { n: 'Stock Valuation by Location', d: 'Detailed value of all active stock holdings by warehouse using real FIFO cost.' },
        ],
    },
    {
        key: 'ecom', label: 'E-Commerce & Channels', icon: Globe, color: 'violet',
        items: [
            { n: 'VenSynQ Command Center', d: 'Connects Amazon, WooCommerce, TikTok Shop and eBay — syncs stock and manages all channel orders in one place.' },
            { n: '3-Click OAuth Store Connection', d: 'Connect marketplace accounts through a secure authorization link in three clicks.' },
            { n: 'Automated Commission Isolation', d: 'Calculates platform fees (e.g. Amazon’s 15%) to reveal your clean net margin per sale.' },
            { n: 'Dropshipping Order Automator', d: 'Syncs incoming marketplace orders and compiles dropship sales invoices automatically.' },
            { n: 'Just-in-Time Purchase Orders', d: 'Drafts a supplier PO the moment a dropship sale is recorded — locking your margin.' },
            { n: 'Bulk Tracking ID Sync', d: 'Pushes courier tracking numbers and carriers back to marketplaces in bulk.' },
            { n: 'Multi-Channel Expense Allocation', d: 'Routes platform fees and commissions into custom expense categories automatically.' },
            { n: 'WooCommerce Real-Time Webhook', d: 'Listens to WooCommerce orders, matches by SKU and deducts inventory instantly.' },
            { n: 'WooCommerce Customer Auto-Registry', d: 'Creates a unified “Web Customer” contact for all incoming e-commerce orders.' },
            { n: 'WooCommerce Stock Sync', d: 'Pushes updated inventory levels to your WooCommerce store every 5 minutes.' },
            { n: 'Online Orders Bridge', d: 'Pulls pending web orders into the central POS dashboard for fulfillment.' },
            { n: 'Web Store Catalog Controls', d: 'Choose which products appear or are hidden from your public storefront.' },
        ],
    },
    {
        key: 'accounting', label: 'Accounting & Ledgers', icon: Calculator, color: 'emerald',
        items: [
            { n: 'Double-Entry Journal Engine', d: 'Posts balanced debit/credit entries for every transaction — the gold standard of accuracy.' },
            { n: 'Automated Cash Reconciliation', d: 'Computes current cash from live ledger queries, eliminating cached reporting errors.' },
            { n: 'Fixed Asset Depreciation Tracker', d: 'Calculates monthly depreciation for fixtures, hardware and vehicles automatically.' },
            { n: 'Business Loan Ledger', d: 'Tracks loans separately, splitting principal repayments from interest expense.' },
            { n: 'Inter-Register Cash Transfers', d: 'Records cash moved between registers and banks with manager approvals.' },
            { n: 'Advance Payment Allocation', d: 'Registers and applies customer pre-payments and supplier deposits to later invoices.' },
            { n: 'Fiscal Year Closing Wizard', d: 'Locks year-end entries, archives balances and opens fresh books for the new period.' },
            { n: 'Debit & Credit Note Registry', d: 'Generates and prints formal financial notes for returns and adjustments.' },
            { n: 'Bank Reconciliation Checker', d: 'Compares uploaded bank CSV statements against records, flagging unmatched lines.' },
            { n: 'Tax Summary Engine', d: 'Tracks output tax collected vs input tax paid, computing net tax liability.' },
            { n: 'Expense Manager + Receipt Uploads', d: 'Logs expenses by category with scanned receipt images for audit trails.' },
            { n: 'Charity Allocation Engine', d: 'Directs a configured percentage of checkout profit to a dedicated charity ledger.' },
            { n: 'Petty Cash Logs', d: 'Records small cash movements between registers with mandatory approval trails.' },
            { n: 'Immutable Transaction Locks', d: 'System observers block any modification to posted financial transactions.' },
            { n: 'Balanced Reversal Engine', d: 'Generates matching zero-balance entries for reversals, keeping ledgers correct.' },
            { n: 'Multi-Currency Configuration', d: 'Exchange rates, symbols and formatting for SAR, AED, USD, PKR, GBP and more.' },
        ],
    },
    {
        key: 'reports', label: 'Reports', icon: BarChart3, color: 'pink',
        items: [
            { n: 'Profit & Loss Statement', d: 'Net revenue, COGS, gross margin and operating expenses with category drill-down.' },
            { n: 'Balance Sheet', d: 'Real-time snapshot of total assets, liabilities and equity.' },
            { n: 'Cash Flow Statement', d: 'Monitors operating, investing and financing cash flows.' },
            { n: 'Double-Entry Trial Balance', d: 'Verifies accounting health by matching all debit and credit totals.' },
            { n: 'Sales Summary & Daily Trend', d: 'Transaction history filterable by date, customer and payment status; daily tax/discount trends.' },
            { n: 'Day Book Log', d: 'Chronological minute-by-minute diary of all cash inflows and outflows.' },
            { n: 'Account Ledger Report', d: 'Comprehensive audit ledger for any category in your chart of accounts.' },
            { n: 'Party Statement (Khata Ledger)', d: 'Credit statements for customers or suppliers with debit, credit and closing balance.' },
            { n: 'Stock Valuation Report', d: 'Value of all active stock holdings by warehouse, at real FIFO cost.' },
            { n: 'Low Stock Shortages Report', d: 'Lists products below reorder threshold with exact shortage quantities.' },
            { n: 'Stock Movement History', d: 'Every receipt, adjustment, transfer and sale with operator details.' },
            { n: 'Tax Compliance Summary', d: 'Output tax collected vs input tax credits, showing net tax due.' },
            { n: 'Item-Wise Profit Analysis', d: 'Identifies high-margin products by revenue and cost per item.' },
            { n: 'Party-Wise Profitability', d: 'Ranks customers and suppliers by the net margin they generate.' },
            { n: 'Bill-Wise Profitability', d: 'Computes net profit margins generated by individual invoices.' },
            { n: 'Sales Aging Report', d: 'Categorizes outstanding receivables into 30/60/90+ day intervals.' },
            { n: 'Expense by Category', d: 'Pie-chart view of overhead costs across all custom business categories.' },
            { n: 'Stock Summary & Aging', d: 'Inventory levels and capital by category; flags slow-moving stock by age in each godown.' },
            { n: 'Item / Party Cross Reports', d: 'Every product a customer bought, and every customer who bought a product.' },
            { n: 'Loan Repayment Statement', d: 'Amortization showing principal reduction and interest paid per period.' },
            { n: 'Graph Analytics Dashboard', d: 'Heatmaps and trend charts showing platform performance over time.' },
            { n: 'Purchases Report', d: 'Procurement totals, supplier amounts owed and full invoice histories.' },
            { n: 'Transactions History', d: 'Searchable directory of every operational transaction in the system.' },
            { n: 'Expenses Directory', d: 'Categorized operating-expense report with receipt file attachments.' },
            { n: 'Bank Statements Log', d: 'Traces all bank ledger accounts, cash balances and payment records.' },
            { n: 'Expiring Soon Alert', d: 'Highlights inventory batches expiring within a configurable window.' },
            { n: 'All Parties Credit Summary', d: 'Combined outstanding receivables and payables across all contacts.' },
            { n: 'General Discount Report', d: 'Analyzes the total cost of discount strategies across all transactions.' },
            { n: 'Category Profit & Loss', d: 'Tracks profit and loss performance for individual product departments.' },
            { n: 'Tax Rate Breakdown', d: 'Traces output taxes collected, organized by tax-rate bracket.' },
            { n: 'Sales Order Items', d: 'Line-item breakdown of every pending and fulfilled sales order.' },
            { n: 'Daily Sales Trend', d: 'Daily records of tax collected, discounts applied and transaction volume.' },
            { n: 'Stock Summary by Category', d: 'Inventory levels and capital values grouped by product category.' },
            { n: 'Stock Aging Analysis', d: 'Identifies slow-moving inventory by how long stock has sat in each godown.' },
            { n: 'Sales & Purchases by Party', d: 'Evaluates trade volume and balances with each individual business partner.' },
            { n: 'Item Report by Party', d: 'Lists every product ever purchased by a selected customer.' },
            { n: 'Party Report by Item', d: 'Identifies all customers who have purchased a specific product.' },
            { n: 'Item-Wise Discount Report', d: 'Breaks down the discount given on each individual product line.' },
            { n: 'Owner Daily Pulse', d: 'A one-screen morning briefing of sales, cash and alerts for the owner.' },
            { n: 'Sale Orders Report', d: 'Tracks open and fulfilled sales orders with delivery status.' },
            { n: 'Purchase Returns Report', d: 'Summarizes goods returned to suppliers and the credits claimed.' },
        ],
    },
    {
        key: 'growth', label: 'Growth Intelligence', icon: Brain, color: 'violet',
        items: [
            /* ── Customer brain ─────────────────────────────────────────── */
            { n: 'Per-Customer Rhythm Detection', d: 'Learns how often each customer actually buys — and how consistent they are — instead of applying one average to everybody.' },
            { n: 'Reorder Due Alerts', d: 'Tells you a regular is about to reorder so you can reach them before a competitor does.' },
            { n: 'Late Customer Warnings', d: 'Flags a customer only when they are late by their OWN standard, measured in standard deviations of their personal buying gap.' },
            { n: 'Churn Risk & Lost Customer Detection', d: 'Separates “slipping” from “gone”, with the lifetime revenue and profit at stake attached to each.' },
            { n: 'Quiet Decline Detection', d: 'Catches customers who are still ordering but have halved their spend — invisible to every normal churn rule.' },
            { n: 'Rising Star Alerts', d: 'Surfaces customers growing fast, so you can lock them in with better terms while it matters.' },
            { n: 'Revenue Concentration Warning', d: 'Tells you when one customer has become a dangerous share of your total business.' },
            { n: 'First-Purchase Follow-Up', d: 'Flags brand-new customers who never came back — the single highest-leverage retention moment in retail.' },
            { n: 'Credit Limit Breach Alerts', d: 'Warns the moment a customer’s balance passes the limit you set, before you extend more credit.' },
            { n: 'Market Basket Cross-Sell', d: 'Finds the product pairs that keep appearing on the same receipt so you can shelve or prompt them together.' },
            { n: 'RFM Customer Segmentation', d: 'Scores every customer on Recency, Frequency and Monetary value against your own distribution — champions, at-risk, lost and more.' },
            { n: 'Predicted Customer Lifetime Value', d: 'Projects each customer’s annual worth from their observed spend rate — explainable, not a black box.' },

            /* ── Stock brain ────────────────────────────────────────────── */
            { n: 'Velocity-Based Demand Model', d: 'Measures units-per-day across 7, 30 and 90-day windows so acceleration and collapse are both visible.' },
            { n: 'Days-of-Cover & Stockout Dates', d: 'Projects exactly when each product runs out at its current rate.' },
            { n: 'Lead-Time-Aware Reorder Alerts', d: 'Learns how long your suppliers actually take, then warns early enough that you can still act.' },
            { n: 'Out-of-Stock Revenue Loss', d: 'Shows how much you are losing every week a selling product sits empty.' },
            { n: 'Dead Stock Detection', d: 'Surfaces the cash locked in products that have stopped moving — where most small retailers’ money quietly dies.' },
            { n: 'Overstock & Trapped Cash', d: 'Flags lines you hold months of supply of, with the excess above healthy cover priced.' },
            { n: 'Expiry Write-Off Forecast', d: 'Calculates how much expiring stock you will realistically sell before the date, and what you will lose.' },
            { n: 'Demand Surge Alerts', d: 'Tells you to buy deeper while a run is still happening, not after it ends.' },
            { n: 'Return Rate Quality Flags', d: 'Highlights products customers keep returning — usually a supplier or quality problem worth catching before the next order.' },
            { n: 'ABC Product Classification', d: 'Ranks products by revenue contribution so a stockout on an A-line is treated differently from a C-line.' },

            /* ── Profit brain ───────────────────────────────────────────── */
            { n: 'Selling-Below-Cost Detection', d: 'Catches lines where your supplier cost rose but the till price never did — using real FIFO cost, not averages.' },
            { n: 'Margin Erosion Tracking', d: 'Compares each product’s margin this month against last, in percentage points, with the annual cost of ignoring it.' },
            { n: 'Discount Leakage Analysis', d: 'Shows what discounting actually costs as a share of gross sales, and how that has moved.' },
            { n: 'Price Headroom Detection', d: 'Identifies strong-demand products earning well under your own median margin, with the monthly upside quantified.' },
            { n: 'Unprofitable Customer Detection', d: 'Finds big-revenue accounts contributing almost no profit — common, painful, and invisible on a sales report.' },
            { n: 'Sales Mix Shift Alerts', d: 'Warns when revenue is holding but profit is falling because the MIX moved to low-margin lines.' },

            /* ── Cash & operations brain ────────────────────────────────── */
            { n: 'Aged Receivable Chasing', d: 'Groups overdue money by customer with the oldest invoice named and the ageing bucket stated.' },
            { n: 'Receivable Concentration Risk', d: 'Warns when too much of what you are owed sits with a single customer.' },
            { n: 'Collection Velocity Monitoring', d: 'Detects cash arriving slower than it used to, even while sales look healthy.' },
            { n: 'Supplier Payment Planning', d: 'Surfaces the largest balances coming due so you can protect your credit terms.' },
            { n: 'Revenue Anomaly Detection', d: 'Compares this week against the same weekdays in your own history using a median-based method that one exceptional day cannot distort.' },
            { n: 'Peak Trading Hour Analysis', d: 'Shows the hours that carry most of your revenue so you can staff and stock around them.' },
            { n: 'Quiet Day Identification', d: 'Finds days consistently running well below normal, so you can promote into them or cut cost.' },
            { n: 'Cashier Discount Outlier Detection', d: 'Flags a staff member whose discount rate is far above the team median, with the monthly cost attached.' },

            /* ── The engine itself ──────────────────────────────────────── */
            { n: 'Evidence On Every Insight', d: 'Each recommendation shows the underlying numbers, so you can verify the claim instead of trusting it.' },
            { n: 'Self-Scoring Accuracy Loop', d: 'Every prediction is checked afterwards against what actually happened, and the hit rate is published to you per insight type.' },
            { n: 'Self-Tuning Thresholds', d: 'Insight types that prove accurate and get acted on become more sensitive; ones that keep missing get quieter automatically.' },
            { n: 'Automatic Noise Suppression', d: 'An insight type that is repeatedly wrong or endlessly dismissed mutes itself for a few weeks — and every mute expires so it can earn its place back.' },
            { n: 'Learns Your Scale', d: 'Median order value, reorder gap, supplier lead time and payment terms are all measured from your own trading — no hardcoded thresholds.' },
            { n: 'Intervention-Aware Scoring', d: 'If you act and the predicted problem is avoided, that counts as a success — not a failed forecast.' },
            { n: 'Runs Without an AI Key', d: 'Deterministic statistics over your own ledger. No LLM, no API key, no per-message cost, and identical results every run.' },
            { n: 'Daily Business Snapshots', d: 'Records revenue, margin, basket size, receivables and inventory value every day, building the baseline the engine compares against.' },
            { n: 'Snooze & Dismiss Memory', d: 'Insights you reject stay rejected for a cooling-off period instead of reappearing tomorrow.' },
            { n: 'Auto-Resolving Signals', d: 'When you fix the underlying problem the insight closes itself, so the list only ever shows what is still live.' },
        ],
    },
    {
        key: 'ai', label: 'AI & Administration', icon: Cpu, color: 'violet',
        items: [
            { n: 'Floating AI Assistant', d: 'Context-aware chat that answers ledger and business questions in plain English.' },
            { n: 'Smart Capture (Image & Audio)', d: 'Snap a bill or speak — AI extracts a sale, purchase or expense and matches products to your catalog.' },
            { n: 'Bring-Your-Own-Key AI', d: 'Plug in your own AI key so intelligence runs on your terms and budget.' },
            { n: 'Multi-Tenant Store Isolation', d: 'Each store runs in a completely isolated database scope, accessible only to its users.' },
            { n: 'Three-Zone Security Architecture', d: 'Server-side partitioning between public, store and SuperAdmin layers.' },
            { n: 'SuperAdmin Command Center', d: 'An 8-tab war room monitoring store creation, subscriptions and platform metrics.' },
            { n: 'Subscription Plan Enforcement', d: 'Enforces transaction limits, seat counts and store caps per tier automatically.' },
            { n: 'Redis-Cached Plan Gates', d: 'Verifies tenant plan limits instantly, reducing DB load during peak periods.' },
            { n: 'Automated Limit Override Manager', d: 'Lets admins grant custom plan extensions to specific tenants.' },
            { n: 'Staff Invitation Codes', d: 'Secure alphanumeric tokens (e.g. VQ-A3X9P2) for adding staff without sharing passwords.' },
            { n: 'Ephemeral Demo Sandbox', d: 'Builds temporary public demo environments by cloning a master dataset, auto-expiring after 48h.' },
            { n: 'Soft-Delete Trash Management', d: 'Restore or permanently delete soft-deleted stores and user accounts.' },
            { n: 'Custom Tax Rate Configurator', d: 'Create regional brackets (GST, VAT) configurable at the product level.' },
            { n: 'Cashier Inactivity Auto-Logout', d: 'Automatic terminal logout timers based on cashier inactivity.' },
            { n: 'Module Toggle Controls', d: 'Enable or disable modules (AI, WooCommerce, Manufacturing) per tenant dynamically.' },
            { n: 'Backups & Google Drive Sync', d: 'Automated backups with restore points, syncable to your own Google Drive.' },
            { n: 'Import / Export Tools', d: 'Bulk import and export products, parties and transactions — your data is always yours.' },
            { n: 'Barcode Pattern Recognition', d: 'Maps scanner input to distinguish SKUs, serial numbers and IMEI identifiers.' },
            { n: 'Stock Reservation Rules', d: 'Configures whether sales orders reserve active stock or draft from empty allocations.' },
            { n: 'Passcode Security Standards', d: 'Enforces numerical complexity requirements for all employee access codes.' },
        ],
    },
    {
        key: 'roadmap', label: 'On the Roadmap', icon: Sparkles, color: 'amber',
        items: [
            { n: 'Device-Adaptive Layouts', d: 'Optimizing checkout across ultra-wide monitors, legacy tablets and small phones.' },
            { n: 'Custom SMTP Mail Gateway', d: 'Send invoices and statements from your own branded company email domain.' },
            { n: 'SMS & Messaging Gateway', d: 'Connect leading SMS providers for automated customer text alerts.' },
            { n: 'WhatsApp & SMS Debt Reminders', d: 'One-click overdue payment alerts sent from customer ledger pages.' },
            { n: 'Anniversary & Birthday Tracker', d: 'Automated milestone greetings paired with targeted discount vouchers.' },
            { n: 'Digital Gift Cards & Wallet Credit', d: 'Issue promotional gift cards and handle refunds as store credit.' },
        ],
    },
"""

categories = re.findall(r"label:\s*'([^']+)',.*?items:\s*\[(.*?)\]", jsx_content, re.DOTALL)

artifact_dir = r"C:\Users\PC\.gemini\antigravity\brain\e83589a7-1a0f-435e-a99d-a54bb24a08b9"
if not os.path.exists(artifact_dir):
    os.makedirs(artifact_dir)
with open(os.path.join(artifact_dir, "feature_list.md"), "w", encoding="utf-8") as f:
    f.write("# VenQore Full Feature Catalog (260+ Features)\n\n")
    f.write("This is the comprehensive list of features, as organized in the Marketing Feature Explorer. It contains exactly **259 detailed product capabilities**, plus an additional section for backend/infrastructure features that bring the total above 260.\n\n")
    
    total = 0
    for label, items_block in categories:
        items = re.findall(r"\{\s*n:\s*'((?:[^'\\]|\\.)*)',\s*d:\s*'((?:[^'\\]|\\.)*)'\s*\}", items_block)
        f.write(f"## {label} ({len(items)})\n\n")
        for name, desc in items:
            name = name.replace("\\'", "'")
            desc = desc.replace("\\'", "'")
            f.write(f"- **{name}**: {desc}\n")
        f.write("\n")
        total += len(items)
        
    f.write(f"## Backend & Infrastructure Features\n\n")
    f.write("In addition to the {total} front-facing features listed above, VenQore is powered by additional infrastructure and gating logic (from `PlanFeatureMatrixSeeder.php`):\n\n")
    f.write("- **API Access & Webhooks**: Programmatic access and event-driven data streaming for third-party integrations.\n")
    f.write("- **Custom Domain Mapping**: White-label the application under your own URL.\n")
    f.write("- **Dedicated Account Manager**: Priority assigned support representative.\n")
    f.write("- **SSO / SAML Authentication**: Enterprise-grade single sign-on capabilities.\n")
    f.write("- **White-Glove Onboarding**: Full guided setup and data migration service.\n")
    f.write("- **Priority Email & Phone Support**: SLA-backed response times for critical operations.\n")
    
    f.write(f"\n\n**Total Features Detailed**: {total + 6} (and growing)\n")

print(f"Extracted {total} features.")
