// Single source: sidebar sub-item label -> Ziggy route name.
// Read by SidebarItem (sidebar) and DockNav (dock). Add a page here once.
export function subItemRoute(itemName, auth) {
    const routeMap = {
                            'Products': 'store.inventory.index',
                            'Categories': 'store.categories.index',
                            'Stock Operations': 'store.stock-operations',
                            'Suppliers': 'store.suppliers.index',
                            'Purchase Orders': 'store.purchase-orders.index',
                            'Labels': 'store.labels.index',
                            'Reports': 'store.reports.index',
                            'Import/Export': 'store.admin.data',
                            'Attributes': 'store.attributes.index',
                            'Quick Access': 'store.home',
                            'Home': 'store.home',
                            'Dashboard': 'store.dashboard',
                            'Main Dashboard': 'store.dashboard',
                            'Executive Dashboard': 'store.admin.dashboard',
                            'User Management': 'store.admin.users',
                            'Approvals': (auth?.user?.can_review_approvals ?? false) ? 'store.approvals.inbox' : 'store.approvals.my-submissions',
                            'Staff Attendance': 'store.admin.attendance',
                            'Data Management': 'store.admin.data',
                            'System Settings': 'store.admin.settings',
                            'Store Settings': 'store.settings',
                            'Builder': 'store.builder',
                            'Modules & Features': 'store.builder',
                            'System Builder': 'store.builder',
                            'Customize Modules': 'store.builder',
                            'Subscription': 'store.billing',
                            'POS': 'store.pos',
                            'Tables': 'store.tables.index',
                            'FOH': 'store.foh',
                            'FOH Settings': 'store.foh.settings',
                            'Add-ons': 'store.addons.index',
                            'Floor': 'store.tables.index',
                            'Floor Plan': 'store.tables.plan',
                            'Kitchen': 'store.restaurant.kitchen',
                            'Order TV Screen': 'store.restaurant.queue',
                            'TV Screen': 'store.restaurant.queue',
                            'Dispatch': 'store.restaurant.dispatch',
                            'Riders': 'store.restaurant.riders',
                            'Restaurant Settings': 'store.restaurant.settings',
                            'Reservations': 'store.reservations.list',
                            'Reservations (Coming Soon)': 'store.reservations.list',
                            'Store Overview': 'store.commerce.home',
                            'Online Orders': 'store.commerce.orders',
                            'Online Products': 'store.commerce.products',
                            'Offers & Coupons': 'store.commerce.promotions',
                            'Onsite Catalogue': 'store.commerce.catalogue',
                            'Analytics': 'store.sales.analytics',
                            'Orders': 'store.sales.index',
                            'Invoices': 'store.sales.invoice.create',
                            'Customers': 'store.customers.index',
                            'To Receive': 'store.finance.receivables',
                            'To Pay': 'store.finance.payables',
                            'Bank Accounts': 'store.bank-accounts.index',
                            'Chart of Accounts': 'store.accounting.index',
                            'P&L': 'store.accounting.pnl',
                            'Balance Sheet': 'store.accounting.balance-sheet',
                            // Phase 2 routes
                            'Parties': 'store.parties.index',
                            'Purchases': 'store.purchases.index',
                            'Payments': 'store.payments.index',
                            'Expenses': 'store.expenses.index',
                            'All Transactions': 'store.transactions.index',
                            // Phase 3 routes
                            'Stock Levels': 'store.inventory.stock',
                            'Sales Orders': 'store.sales.orders.index',
                            'Production': 'store.production.index',
                            'Parked Sales': 'store.parked-sales.index',
                            // Phase 4 Reports
                            'Sales Report': 'store.reports.sales',
                            'Purchase Report': 'store.reports.purchases',
                            'Day Book': 'store.reports.day-book',
                            'Profit & Loss': 'store.reports.profit-loss',
                            'Party Statement': 'store.reports.party-statement',
                            'Cookbook': 'store.cookbook.index', 
                            // ALL 40 Reports
                            'Stock Valuation': 'store.reports.stock-valuation',
                            'Low Stock': 'store.reports.low-stock',
                            'Movement History': 'store.reports.movement-history',
                            'Expiry Report': 'store.reports.expiry',
                            'Stock Summary by Category': 'store.reports.stock-summary-by-category',
                            'Item Detail': 'store.reports.item-detail',
                            'Item Report by Party': 'store.reports.item-report-by-party',
                            'Party Report by Item': 'store.reports.item-report-by-item',
                            'Sale/Purchase by Item Category': 'store.reports.sale-purchase-by-item-category',
                            'Bank Statement': 'store.reports.bank-statement',
                            'Expense Report': 'store.reports.expenses',
                            'Tax Report': 'store.reports.tax',
                            'Tax Rate Report': 'store.reports.tax-rate',
                            'Trial Balance': 'store.reports.trial-balance',
                            'Cash Flow': 'store.reports.cash-flow',
                            'Discount Report': 'store.reports.discount',
                            'Loan Statement': 'store.reports.loan-statement',
                            'Item Wise Profit': 'store.reports.item-wise-profit',
                            'Party Wise Profit Loss': 'store.reports.party-wise-profit-loss',
                            'Bill Wise Profit': 'store.reports.bill-wise-profit',
                            'Item Category Wise Profit Loss': 'store.reports.item-category-wise-profit-loss',
                            'Item Wise Discount': 'store.reports.item-wise-discount',
                            'Sale Purchase by Party': 'store.reports.sale-purchase-by-party',
                            'Sale Purchase by Party Group': 'store.reports.sale-purchase-by-party-group',
                            'Stock Aging': 'store.reports.stock-aging',
                            'Sale Orders Report': 'store.reports.sale-orders',
                            'Sale Order Items': 'store.reports.sale-order-items',
                            'Sale Aging': 'store.reports.sale-aging',
                            'All Parties': 'store.reports.all-parties',
                            'Expense by Category': 'store.reports.expense-by-category',
                            'Expense by Item': 'store.reports.expense-by-item',
                            'Staff Summaries': 'store.admin.staff',
                            // New Features
                            'Service Jobs': 'store.service-jobs.index',
                            'Dispatch Calendar': 'store.service-jobs.calendar',
                            'Tools & Equipment': 'store.tools.index',
                            'Services': 'store.service-jobs.index',
                            'Proposals': 'store.proposals.index',
                            'Returns History': 'store.returns-history.index',
                            'Recurring Invoices': 'store.recurring-invoices.index',
                            'Invoice Reminders': 'store.invoice-reminders.index',
                            'Stock Transfers': 'store.stock-transfers.index',
                            'Stock Audit': 'store.stock-takes.index',
                            'Batch Tracking': 'store.batches.index',
                            'Serial Tracking': 'store.serials.index',
                            'Debit Notes': 'store.debit-notes.index',
                            'Purchase Returns': 'store.debit-notes.index',
                            'Campaigns': 'store.marketing-campaigns.index',
                            'Online Store': 'store.online-store.index',
                            'VenSynQ': 'vensynq.index',
                            'VenSynQ Settings': 'vensynq.settings',
                            'WooCommerce Sync': 'store.woocommerce.index',
                            'E-Invoicing (Coming Soon)': 'store.e-invoicing.index',
                            'Bank Reconciliation': 'store.bank-reconciliation.index',
                            'Activity Log': 'store.activity-log.index',
                            'Recycle Bin': 'store.recycle-bin.index',
                            'Settings': 'store.settings',
                            'Quotations / Pre-Sales': 'store.pre-sales.index',
                            'Pre-Purchases': 'store.purchase-orders.index', 
                            'Fund Management': 'store.funds.index',
                            'Approval Inbox': 'store.approvals.inbox',
                            'Approval Policies': 'store.settings',
                            'My Submissions': 'store.approvals.my-submissions',
    };
    return routeMap[itemName];
}
