// Words on the QR menu, in English and Urdu. Dish names and descriptions come from the business.
export const TEXT = {
    en: {
        menu: 'Menu', search: 'Search the menu', add: 'Add', all: 'All', orderAtCounter: 'Order at the counter', orderingFor: (t) => `Ordering for ${t}`,
        viewOrder: 'View your order', items: (n) => `${n} item${n === 1 ? '' : 's'}`, yourOrder: 'Your order', empty: 'Nothing added yet.',
        yourName: 'Your name', yourNameOpt: 'Your name (optional)', noteForStaff: 'Anything for the staff? (optional)', total: 'Total',
        send: (t) => `Send order to ${t}`, sending: 'Sending order…', counter: 'the counter', finalNote: 'Final amount is confirmed by our team at the table.',
        addNote: 'Add a request', notePlaceholder: 'e.g. no onions, extra spicy', noteLabel: 'Any request for this dish?', addToOrder: 'Add to order',
        chooseOne: 'Choose one', required: 'Required', optional: 'Optional', upTo: (n) => `up to ${n}`, soldOut: 'Sold out', onlyLeft: (n) => `Only ${n} left`,
        myOrders: 'My orders', orderMore: 'Order more', callWaiter: 'Call a waiter', requestBill: 'Request the bill',
        waiting: 'Waiting for staff', kitchen: 'In the kitchen', done: 'Served and closed', changed: 'Changed by staff',
        changedHelp: 'Staff changed this order. Please ask your server.', removedHelp: (n) => `${n} item${n === 1 ? ' was' : 's were'} removed by staff. Please ask your server.`,
        removedLine: (n, r) => `${n} was removed by staff${r ? `: ${r}` : '.'}`,
        reference: 'Reference', billAsked: 'Bill requested', waiterAsked: 'A waiter was called', offline: 'No connection. Your order is saved here and will be sent when you are back online.',
        retry: 'Try again', held: 'Ordering is paused right now.', open: 'Open now', prep: (m) => `About ${m} min`, language: 'اردو',
        noMatch: 'Nothing matches.', menuEmpty: 'The menu is on its way.', tableHelp: 'Need help? Use the buttons in My orders.',
        popular: 'Popular', deal: 'Deal', new: 'New', close: 'Close', remove: 'Remove',
        tags: { veg: 'Vegetarian', vegan: 'Vegan', halal: 'Halal', spicy: 'Spicy', gluten_free: 'Gluten free', contains_nuts: 'Contains nuts', contains_dairy: 'Contains dairy' }, allergens: 'Allergens',
    },
    ur: {
        menu: 'مینو', search: 'مینو میں تلاش کریں', add: 'شامل کریں', all: 'سب', orderAtCounter: 'کاؤنٹر پر آرڈر کریں', orderingFor: (t) => `${t} کے لیے آرڈر`,
        viewOrder: 'اپنا آرڈر دیکھیں', items: (n) => `${n} آئٹم`, yourOrder: 'آپ کا آرڈر', empty: 'ابھی کچھ شامل نہیں کیا۔',
        yourName: 'آپ کا نام', yourNameOpt: 'آپ کا نام (اختیاری)', noteForStaff: 'عملے کے لیے کوئی بات؟ (اختیاری)', total: 'کل',
        send: (t) => `آرڈر ${t} کو بھیجیں`, sending: 'آرڈر بھیجا جا رہا ہے…', counter: 'کاؤنٹر', finalNote: 'حتمی رقم ہماری ٹیم ٹیبل پر کنفرم کرے گی۔',
        addNote: 'فرمائش لکھیں', notePlaceholder: 'مثلاً پیاز کے بغیر، زیادہ مرچ', noteLabel: 'اس ڈش کے لیے کوئی فرمائش؟', addToOrder: 'آرڈر میں شامل کریں',
        chooseOne: 'ایک منتخب کریں', required: 'ضروری', optional: 'اختیاری', upTo: (n) => `زیادہ سے زیادہ ${n}`, soldOut: 'ختم', onlyLeft: (n) => `صرف ${n} باقی`,
        myOrders: 'میرے آرڈر', orderMore: 'مزید آرڈر کریں', callWaiter: 'ویٹر کو بلائیں', requestBill: 'بل منگوائیں',
        waiting: 'عملے کا انتظار', kitchen: 'کچن میں', done: 'پیش کر دیا گیا', changed: 'عملے نے تبدیل کیا',
        changedHelp: 'عملے نے یہ آرڈر تبدیل کیا ہے۔ براہِ کرم اپنے ویٹر سے پوچھیں۔', removedHelp: (n) => `عملے نے ${n} آئٹم ہٹا دیے۔ براہِ کرم اپنے ویٹر سے پوچھیں۔`,
        removedLine: (n, r) => `عملے نے ${n} ہٹا دیا${r ? `: ${r}` : '۔'}`,
        reference: 'حوالہ نمبر', billAsked: 'بل منگوایا گیا', waiterAsked: 'ویٹر کو بلایا گیا', offline: 'انٹرنیٹ نہیں ہے۔ آپ کا آرڈر یہیں محفوظ ہے اور رابطہ بحال ہوتے ہی بھیج دیا جائے گا۔',
        retry: 'دوبارہ کوشش کریں', held: 'اس وقت آرڈر عارضی طور پر بند ہیں۔', open: 'کھلا ہے', prep: (m) => `تقریباً ${m} منٹ`, language: 'English',
        noMatch: 'کوئی نتیجہ نہیں ملا۔', menuEmpty: 'مینو جلد آ رہا ہے۔', tableHelp: 'مدد چاہیے؟ میرے آرڈر میں بٹن استعمال کریں۔',
        popular: 'مقبول', deal: 'رعایت', new: 'نیا', close: 'بند کریں', remove: 'ہٹائیں',
        tags: { veg: 'سبزی', vegan: 'ویگن', halal: 'حلال', spicy: 'تیز مصالحہ', gluten_free: 'گلوٹن فری', contains_nuts: 'گری دار میوے', contains_dairy: 'ڈیری' }, allergens: 'الرجی',
    },
};
