# setup_production_worktree.ps1
#
# ONE-TIME SETUP. Run this once, from anywhere (it uses absolute paths).
#
# IMPORTANT: this repo is rooted at E:\AMD POS\AMD POS itself -- main-app,
# production, mobile-app, windows-app are all just SUBFOLDERS of the same
# repo, not separate git repos. That means a git "worktree" for production\
# does not work here: git worktrees need their own .git pointer file, but
# our sync script uses robocopy /MIR to mirror main-app -> production, and
# /MIR deletes anything in the destination that doesn't exist in the source
# -- including that .git pointer file, since main-app has no such file at
# the same relative path. That silently destroys the worktree link.
#
# So instead: production\ is a plain, ordinary folder (not a worktree, not
# part of the big repo's tracked tree -- it's added to the root .gitignore
# below so accidental `git add -A` from the repo root never touches it).
# It is mirrored by sync_production.ps1 same as before. The actual git
# repo that tracks production-clean lives SEPARATELY, in its own folder
# with its own independent .git, at:
#   E:\AMD POS\AMD POS\app-code\production-clean-repo\
#
# sync_and_push.ps1 copies production\'s mirrored contents into that
# separate repo folder (a plain robocopy /MIR that EXCLUDES .git, so the
# repo folder's own .git is always safe), then commits/pushes from there.

$ErrorActionPreference = "Stop"

$repoRoot = "E:\AMD POS\AMD POS"
$appCode = Join-Path $repoRoot "app-code"
$prodMirror = Join-Path $appCode "production"
$prodRepo = Join-Path $appCode "production-clean-repo"
$gitignorePath = Join-Path $repoRoot ".gitignore"

Write-Host "Repo root:         $repoRoot"
Write-Host "Mirror folder:     $prodMirror  (plain folder, not a git worktree)"
Write-Host "Clean repo folder: $prodRepo  (own independent .git, tracks production-clean)"
Write-Host ""

# 1. Make sure production\ (the mirror target) is excluded from the main repo's tracking.
if (Test-Path $gitignorePath) {
    $ignoreContent = Get-Content $gitignorePath -Raw
    if ($ignoreContent -notmatch [regex]::Escape("app-code/production/")) {
        Add-Content -Path $gitignorePath -Value "`n# Clean-release mirror folder (regenerated by sync_production.ps1, never tracked here)`napp-code/production/"
        Write-Host "Added app-code/production/ to the repo root .gitignore."
    } else {
        Write-Host "app-code/production/ already in .gitignore."
    }
} else {
    Write-Host "WARNING: no .gitignore found at $gitignorePath -- skipping." -ForegroundColor Yellow
}

# 2. Create the mirror folder (plain, empty for now -- sync_production.ps1 populates it).
if (-not (Test-Path $prodMirror)) {
    New-Item -ItemType Directory -Path $prodMirror | Out-Null
    Write-Host "Created $prodMirror"
} else {
    Write-Host "$prodMirror already exists."
}

# 3. Clone production-clean into its own separate repo folder (independent .git).
if (Test-Path $prodRepo) {
    Write-Host ""
    Write-Host "ERROR: $prodRepo already exists." -ForegroundColor Red
    Write-Host "If it's not yet a valid git repo, delete it and re-run this script."
    exit 1
}

Push-Location $appCode
try {
    Write-Host ""
    Write-Host "Cloning production-clean into its own repo folder..."
    git clone --branch production-clean --single-branch https://github.com/AbdullahHashmi10/VenQore.git production-clean-repo
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "DONE."
Write-Host " - $prodMirror is your always-clean mirror of main-app (plain folder)."
Write-Host " - $prodRepo is an independent git repo tracking origin/production-clean."
Write-Host "Next: run sync_and_push.ps1 to sync + commit + push."
