<?php

return [
    'starter' => [
        'reports.sales',
        'reports.sale-orders',
        'reports.daily-sales',
        'reports.purchases',
        'reports.low-stock',
        'reports.stock-valuation',
        'reports.expenses',
        'reports.profit-loss',
        'reports.day-book',
        'reports.transactions',
        'reports.all-parties',
    ],
    'growth' => [
        'reports.analytics',
        'reports.sale-order-items',
        'reports.item-wise-profit',
        'reports.bill-wise-profit',
        'reports.discount',
        'reports.movement-history',
        'reports.cash-flow',
        'reports.bank-statement',
        'reports.tax',
        'reports.expense-by-category',
        'reports.tax-rate',
        'reports.account-ledger',
        'reports.party-statement',
        'reports.sale-purchase-by-party',
        'reports.chart-of-accounts',
    ],
    'business' => [
        'reports.sale-aging',
        'reports.stock-summary-by-category',
        'reports.stock-aging',
        'reports.item-detail',
        'reports.expiry',
        'reports.balance-sheet',
        'reports.trial-balance',
        'reports.owner-daily-pulse',
        'reports.party-wise-profit-loss',
        'reports.item-report-by-party',
        'reports.party-report-by-item',
        'reports.loan-statement',
        'reports.sale-purchase-by-item-category',
        'reports.item-category-wise-profit-loss',
        'reports.item-wise-discount',
        'reports.sale-purchase-by-party-group',
        'reports.expense-by-item',
        'reports.graphAnalytics',
    ],
];
