<?php
/*
| ROUTE OWNERSHIP AUDIT
|
| Takes the output of tools/extract_routes.py and answers one question for every
| route name in the application:
|
|     when EnsureModule sees this route, what does it do?
|
| Four possible answers:
|   OWNED      — one module claims it. Blocked when that module is off.
|   SHARED     — several modules claim it. Allowed if ANY of them is on.
|                Legal, but it must be deliberate.
|   ALWAYS-ON  — platform surface from config/qore.php. Never blocked.
|   UNCLAIMED  — nothing claims it. It is ALWAYS REACHABLE.
|
| UNCLAIMED is the dangerous one. Every unclaimed route under a module's URL
| space is a way to reach a "disabled" module by typing its address.
|
| Usage:
|   python3 tools/extract_routes.py routes/web.php > routes.txt
|   php tools/route_ownership.php routes.txt > docs/ROUTE_OWNERSHIP.md
*/

$root    = dirname(__DIR__);
$modules = require $root.'/config/modules.php';
$qore    = require $root.'/config/qore.php';
$file    = $argv[1] ?? ($root.'/routes.txt');

$routes = [];
foreach (file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
    [$name, $ln, $uri, $mw] = array_pad(explode("\t", $line), 4, '');
    $routes[$name] = ['line' => $ln, 'uri' => $uri, 'mw' => $mw];
}

$matches = function (string $pattern, string $name): bool {
    return (bool) preg_match('/^'.str_replace('\*', '.*', preg_quote($pattern, '/')).'$/', $name);
};

$owners = $always = $frozen = [];

foreach ($routes as $name => $_) {
    foreach ($modules as $key => $m) {
        foreach ($m['routes'] as $p) {
            if ($matches($p, $name)) { $owners[$name][] = $key; break; }
        }
    }
    foreach ($qore['always_on_routes'] as $p) {
        if ($matches($p, $name)) { $always[$name] = true; break; }
    }
    foreach (array_keys($qore['frozen_surfaces']) as $p) {
        if ($matches($p, $name)) { $frozen[$name] = $qore['frozen_surfaces'][$p]; break; }
    }
}

$owned = $shared = $unclaimed = [];
foreach ($routes as $name => $meta) {
    $o = array_unique($owners[$name] ?? []);
    if (count($o) === 1)      { $owned[$name] = reset($o); }
    elseif (count($o) > 1)    { $shared[$name] = $o; }
    elseif (isset($always[$name]) || isset($frozen[$name])) { /* accounted for */ }
    else                      { $unclaimed[$name] = $meta; }
}

// Unclaimed routes that sit under a URL space a module owns are the real risk.
$risky = [];
foreach ($unclaimed as $name => $meta) {
    $head = implode('.', array_slice(explode('.', $name), 0, 2));
    foreach ($modules as $key => $m) {
        foreach ($m['routes'] as $p) {
            if (str_starts_with($p, $head)) { $risky[$name] = $key; break 2; }
        }
    }
}

$total = count($routes);
$out = [];
$out[] = '# ROUTE OWNERSHIP AUDIT';
$out[] = '## Every route name in the application, and what the module gate will do with it';
$out[] = '';
$out[] = '> Generated by `tools/route_ownership.php` from `tools/extract_routes.py`, '.date('j F Y').'.';
$out[] = '> **This is a static approximation.** Before launch run `php artisan route:list --json > route_list_current.json`, re-run this against it, and diff. Anything that appears only in one of the two lists is worth understanding.';
$out[] = '';
$out[] = '## Why this document exists';
$out[] = '';
$out[] = 'Hiding a nav item is not disabling a module. If the route still resolves, the module is still reachable by typing the URL — and the customer who finds that has found a bug in the thing you are selling as "your system, your modules".';
$out[] = '';
$out[] = 'So every route name gets one of four verdicts:';
$out[] = '';
$out[] = '| Verdict | Meaning | Gate behaviour |';
$out[] = '|---|---|---|';
$out[] = '| **OWNED** | exactly one module claims it | blocked when that module is off |';
$out[] = '| **SHARED** | several modules claim it | allowed if **any** owner is on |';
$out[] = '| **ALWAYS-ON** | platform surface (`config/qore.php`) | never blocked |';
$out[] = '| **UNCLAIMED** | nothing claims it | **always reachable** |';
$out[] = '';
$out[] = '## Totals';
$out[] = '';
$out[] = '| | Count | Share |';
$out[] = '|---|---|---|';
foreach ([
    'OWNED' => count($owned), 'SHARED' => count($shared),
    'ALWAYS-ON (platform)' => count($always), 'FROZEN (built, unowned by design)' => count($frozen),
    'UNCLAIMED' => count($unclaimed),
] as $label => $n) {
    $out[] = sprintf('| %s | %d | %.1f%% |', $label, $n, $total ? $n / $total * 100 : 0);
}
$out[] = sprintf('| **TOTAL** | **%d** | |', $total);
$out[] = '';

$out[] = '---';
$out[] = '';
$out[] = '## 1. UNCLAIMED routes that sit inside a module\'s URL space ('.count($risky).')';
$out[] = '';
$out[] = '**Fix these first.** Each one shares a namespace with a module but is not listed in that module\'s `routes` array — so switching the module off leaves this route wide open.';
$out[] = '';
if ($risky) {
    $out[] = '| Route name | Line | Probably belongs to | Gate on it today |';
    $out[] = '|---|---|---|---|';
    foreach ($risky as $name => $key) {
        $m = $routes[$name];
        $out[] = '| `'.$name.'` | '.$m['line'].' | **#'.$modules[$key]['id'].' '.$modules[$key]['label'].'** | '.($m['mw'] ?: '— none —').' |';
    }
} else {
    $out[] = '*None. Every route inside a module namespace is claimed.*';
}
$out[] = '';

$out[] = '---';
$out[] = '';
$out[] = '## 2. All other UNCLAIMED routes ('.(count($unclaimed) - count($risky)).')';
$out[] = '';
$out[] = 'These are outside every module namespace. Most are legitimately platform, marketing or admin surfaces — but each should end up either in `config/qore.php` `always_on_routes`, in `frozen_surfaces`, or inside a module. **An unclaimed route is a decision you have not made yet.**';
$out[] = '';
$rest = array_diff_key($unclaimed, $risky);
$grouped = [];
foreach ($rest as $name => $meta) {
    $grouped[explode('.', $name)[0]][] = $name;
}
ksort($grouped);
$out[] = '| Namespace | Count | Examples |';
$out[] = '|---|---|---|';
foreach ($grouped as $ns => $names) {
    $out[] = '| `'.$ns.'.*` | '.count($names).' | '.implode(', ', array_map(fn ($n) => '`'.$n.'`', array_slice($names, 0, 3))).' |';
}
$out[] = '';

$out[] = '---';
$out[] = '';
$out[] = '## 3. SHARED routes ('.count($shared).')';
$out[] = '';
$out[] = 'Legal, but the gate must allow the route when **any** owning module is enabled — never "the first one that matches". Check each of these is a deliberate decision.';
$out[] = '';
if ($shared) {
    $out[] = '| Route name | Claimed by |';
    $out[] = '|---|---|';
    foreach ($shared as $name => $keys) {
        $out[] = '| `'.$name.'` | '.implode(', ', array_map(fn ($k) => '#'.$modules[$k]['id'].' '.$modules[$k]['label'], $keys)).' |';
    }
} else {
    $out[] = '*None. Every claimed route has exactly one owner.*';
}
$out[] = '';

$out[] = '---';
$out[] = '';
$out[] = '## 4. Coverage by module';
$out[] = '';
$out[] = 'A `live` module with zero owned routes is a module the gate cannot protect and a customer cannot open.';
$out[] = '';
$out[] = '| # | Module | Status | Routes owned | Verdict |';
$out[] = '|---|---|---|---|---|';
$counts = array_count_values($owned);
foreach ($shared as $keys) { foreach ($keys as $k) { $counts[$k] = ($counts[$k] ?? 0) + 1; } }
foreach ($modules as $key => $m) {
    $n = $counts[$key] ?? 0;
    $verdict = match (true) {
        $n === 0 && $m['status'] === 'live'  => '⚠️ **live but owns nothing — investigate**',
        $n === 0                             => 'expected — not built yet',
        $n < 3                               => 'thin surface, confirm it is complete',
        default                              => 'ok',
    };
    $out[] = '| '.$m['id'].' | '.$m['label'].' | `'.$m['status'].'` | '.$n.' | '.$verdict.' |';
}
$out[] = '';

$out[] = '---';
$out[] = '';
$out[] = '## 5. The full table';
$out[] = '';
$out[] = '<details><summary>All '.$total.' route names</summary>';
$out[] = '';
$out[] = '| Route name | Line | Owner | Gate today |';
$out[] = '|---|---|---|---|';
foreach ($routes as $name => $meta) {
    $own = match (true) {
        isset($owned[$name])  => '#'.$modules[$owned[$name]]['id'].' '.$modules[$owned[$name]]['label'],
        isset($shared[$name]) => 'SHARED: '.implode(' + ', $shared[$name]),
        isset($always[$name]) => '_always-on_',
        isset($frozen[$name]) => '_frozen_',
        default               => '**UNCLAIMED**',
    };
    $out[] = '| `'.$name.'` | '.$meta['line'].' | '.$own.' | '.($meta['mw'] ?: '—').' |';
}
$out[] = '';
$out[] = '</details>';
$out[] = '';

file_put_contents($root.'/docs/ROUTE_OWNERSHIP.md', implode("\n", $out)."\n");
printf("total=%d owned=%d shared=%d always=%d frozen=%d unclaimed=%d risky=%d\n",
    $total, count($owned), count($shared), count($always), count($frozen), count($unclaimed), count($risky));
