<?php

/*
|--------------------------------------------------------------------------
| Business types — the ONE catalogue (85 types, 5 sectors)
|--------------------------------------------------------------------------
| Source of truth for: the builder's business-type search and one-click setup,
| the matcher that reads what a visitor types (App\Support\BusinessTypes::match),
| the terminology a new store starts with, and the public site's "85+" list
| (resources/js/Data/businessTypes.json — regenerate with
| `php artisan vq:business-types:export`; a test fails if they drift).
|
| Per type:
|   sector   one of 'sectors' below
|   preset   a key in config/ai_builder.php presets — the base module set
|   modules  extra modules on top of the preset (dependencies are added
|            automatically; non-live modules are dropped)
|   aliases  words and phrases people actually use — including Roman Urdu
|            (kiryana, darzi, mithai). Whole-word match; plurals and one-letter
|            typos are tolerated. Adding an alias here is how you fix a miss.
|   terms    terminology overrides (App\Support\Terms keys) on top of the
|            preset's own terms: key => [singular, plural]
*/

return [

    'sectors' => [
        'services' => ['name' => 'Services, repairs & field trades', 'short' => 'Services & trades'],
        'retail' => ['name' => 'Retail & merchandising', 'short' => 'Retail'],
        'food' => ['name' => 'Food, beverage & hospitality', 'short' => 'Food & hospitality'],
        'wholesale' => ['name' => 'Wholesale, trade & B2B distribution', 'short' => 'Wholesale & B2B'],
        'manufacturing' => ['name' => 'Light manufacturing & assembly', 'short' => 'Light manufacturing'],
    ],

    'types' => [

        // ── services ────────────────────────────────────────────────────
        'phone_repair' => [
            'sector'  => 'services',
            'label'   => 'Gadget & phone repair shops',
            'note'    => 'Job cards, IMEI intake, parts deduction, repair warranty',
            'preset'  => 'repair_workshop',
            'modules' => ['serials'],
            'aliases' => ['phone repair', 'mobile repair', 'mobile phone repair', 'gadget repair', 'screen repair', 'cell phone repair', 'mobile technician', 'phone fixing', 'iphone repair', 'mobile repairing'],
            'terms'   => ['job' => ['Repair Job', 'Repair Jobs'], 'product' => ['Part', 'Parts'], 'technician' => ['Technician', 'Technicians']],
        ],
        'computer_repair' => [
            'sector'  => 'services',
            'label'   => 'Computer & laptop repair centres',
            'preset'  => 'repair_workshop',
            'modules' => ['serials'],
            'aliases' => ['computer repair', 'laptop repair', 'pc repair', 'it repair', 'laptop service', 'computer service', 'printer repair', 'computer repairing'],
            'terms'   => ['job' => ['Repair Job', 'Repair Jobs'], 'product' => ['Part', 'Parts']],
        ],
        'auto_repair' => [
            'sector'  => 'services',
            'label'   => 'Auto repair & mechanic garages',
            'note'    => 'Parts and technician labour on one invoice',
            'preset'  => 'repair_workshop',
            'aliases' => ['car repair', 'auto repair', 'mechanic', 'garage', 'auto workshop', 'car service', 'car workshop', 'denting painting', 'tuning', 'vehicle repair', 'car mechanic', 'auto mechanic', 'body shop', 'oil change'],
            'terms'   => ['job' => ['Job Card', 'Job Cards'], 'occupancy' => ['Bay', 'Bays'], 'technician' => ['Mechanic', 'Mechanics'], 'product' => ['Part', 'Parts']],
        ],
        'appliance_repair' => [
            'sector'  => 'services',
            'label'   => 'Appliance repair (AC, fridges, washers)',
            'preset'  => 'field_service',
            'aliases' => ['appliance repair', 'ac repair', 'fridge repair', 'refrigerator repair', 'washing machine repair', 'air conditioner repair', 'microwave repair', 'ac service', 'ac technician', 'home appliance repair', 'repair air conditioners', 'repair ac'],
            'terms'   => ['job' => ['Service Call', 'Service Calls'], 'product' => ['Part', 'Parts']],
        ],
        'bike_service' => [
            'sector'  => 'services',
            'label'   => 'Bicycle & motorcycle service centres',
            'preset'  => 'repair_workshop',
            'aliases' => ['bike repair', 'bike service', 'motorcycle repair', 'motorbike repair', 'motorcycle service', 'bicycle repair', 'scooter repair', 'cycle repair', 'bike mechanic'],
            'terms'   => ['job' => ['Job Card', 'Job Cards'], 'technician' => ['Mechanic', 'Mechanics'], 'product' => ['Part', 'Parts']],
        ],
        'salon_barber' => [
            'sector'  => 'services',
            'label'   => 'Hair salons & barber shops',
            'note'    => 'Staff commission, appointments, repeat-client khata',
            'preset'  => 'salon',
            'aliases' => ['salon', 'hair salon', 'barber', 'barbershop', 'barber shop', 'haircut', 'hair cut', 'beauty parlour', 'beauty parlor', 'beauty salon', 'hairdresser', 'unisex salon', 'gents salon', 'ladies salon'],
            'terms'   => ['customer' => ['Client', 'Clients'], 'staff' => ['Stylist', 'Stylists'], 'service' => ['Service', 'Services']],
        ],
        'nail_spa' => [
            'sector'  => 'services',
            'label'   => 'Nail salons & spas',
            'preset'  => 'salon',
            'aliases' => ['nail salon', 'nail bar', 'spa', 'day spa', 'massage', 'massage centre', 'manicure', 'pedicure', 'wellness centre', 'beauty spa', 'lash studio', 'waxing'],
            'terms'   => ['customer' => ['Client', 'Clients'], 'staff' => ['Therapist', 'Therapists'], 'service' => ['Treatment', 'Treatments']],
        ],
        'pet_care' => [
            'sector'  => 'services',
            'label'   => 'Pet grooming & veterinary clinics',
            'preset'  => 'salon',
            'modules' => ['products', 'inventory'],
            'aliases' => ['pet grooming', 'dog grooming', 'vet', 'veterinary', 'veterinarian', 'vet clinic', 'animal clinic', 'pet clinic', 'animal hospital', 'cat grooming'],
            'terms'   => ['customer' => ['Pet Owner', 'Pet Owners'], 'service' => ['Treatment', 'Treatments']],
        ],
        'freelance_creative' => [
            'sector'  => 'services',
            'label'   => 'Freelance designers & developers',
            'note'    => 'Milestone invoices, zero-inventory ledger',
            'preset'  => 'professional_services',
            'aliases' => ['freelancer', 'freelance', 'graphic designer', 'graphic design', 'web developer', 'web design', 'designer', 'developer', 'app developer', 'software developer', 'ui designer', 'ux designer', 'video editor', 'content writer', 'copywriter', 'illustrator'],
            'terms'   => ['customer' => ['Client', 'Clients']],
        ],
        'marketing_agency' => [
            'sector'  => 'services',
            'label'   => 'Digital marketing & SEO agencies',
            'note'    => 'Monthly retainers on recurring invoices',
            'preset'  => 'professional_services',
            'aliases' => ['marketing agency', 'digital marketing', 'digital agency', 'seo', 'seo agency', 'social media agency', 'social media marketing', 'advertising agency', 'ads agency', 'branding agency', 'creative agency', 'pr agency'],
            'terms'   => ['customer' => ['Client', 'Clients'], 'contract' => ['Retainer', 'Retainers']],
        ],
        'consultant' => [
            'sector'  => 'services',
            'label'   => 'Consultants & business coaches',
            'note'    => 'Hourly and session billing',
            'preset'  => 'professional_services',
            'aliases' => ['consultant', 'consulting', 'consultancy', 'business coach', 'coach', 'life coach', 'advisor', 'adviser', 'management consultant', 'corporate trainer', 'mentor'],
            'terms'   => ['customer' => ['Client', 'Clients'], 'service' => ['Session', 'Sessions']],
        ],
        'accounting_firm' => [
            'sector'  => 'services',
            'label'   => 'Accountants, tax consultants & auditors',
            'preset'  => 'professional_services',
            'aliases' => ['accountant', 'accounting firm', 'accounting practice', 'tax consultant', 'tax advisor', 'auditor', 'audit firm', 'bookkeeper', 'bookkeeping', 'chartered accountant', 'ca firm', 'tax filing', 'payroll services'],
            'terms'   => ['customer' => ['Client', 'Clients'], 'job' => ['Engagement', 'Engagements']],
        ],
        'law_firm' => [
            'sector'  => 'services',
            'label'   => 'Lawyers & legal practices',
            'preset'  => 'professional_services',
            'aliases' => ['lawyer', 'law firm', 'legal practice', 'advocate', 'attorney', 'solicitor', 'legal services', 'legal consultant', 'notary'],
            'terms'   => ['customer' => ['Client', 'Clients'], 'job' => ['Matter', 'Matters']],
        ],
        'architect_interior' => [
            'sector'  => 'services',
            'label'   => 'Architects & interior designers',
            'note'    => 'Quotation to final bill',
            'preset'  => 'professional_services',
            'aliases' => ['architect', 'architecture firm', 'interior designer', 'interior design', 'interior decorator', 'landscape designer', 'design studio'],
            'terms'   => ['customer' => ['Client', 'Clients'], 'job' => ['Project', 'Projects']],
        ],
        'photo_video' => [
            'sector'  => 'services',
            'label'   => 'Photographers & videographers',
            'note'    => 'Equipment hire and shoot booking',
            'preset'  => 'professional_services',
            'aliases' => ['photographer', 'photography', 'photo studio', 'videographer', 'videography', 'video production', 'wedding photographer', 'film production', 'drone photography'],
            'terms'   => ['customer' => ['Client', 'Clients'], 'job' => ['Shoot', 'Shoots']],
        ],
        'electrician' => [
            'sector'  => 'services',
            'label'   => 'Electricians & electrical contractors',
            'note'    => 'Tool management and technician dispatch',
            'preset'  => 'field_service',
            'aliases' => ['electrician', 'electrical contractor', 'fix wiring', 'install lights', 'electric fitting', 'electrical work', 'electrical services', 'wiring', 'rewiring', 'solar installation', 'solar installer', 'bijli', 'electrical job', 'electric work'],
            'terms'   => ['technician' => ['Electrician', 'Electricians'], 'product' => ['Material', 'Materials']],
        ],
        'plumber' => [
            'sector'  => 'services',
            'label'   => 'Plumbing & sanitary contractors',
            'preset'  => 'field_service',
            'aliases' => ['plumber', 'plumbing', 'leaking pipe', 'leaking pipes', 'pipe repair', 'fix pipes', 'install bathrooms', 'bathroom installation', 'water leakage', 'plumbing service', 'plumbing contractor', 'sanitary contractor', 'sanitary work', 'pipe fitting', 'pipe fitter', 'drainage', 'drain cleaning', 'leak repair', 'water tank cleaning', 'geyser repair', 'plumbing job', 'plumbing jobs', 'plumbing work'],
            'terms'   => ['technician' => ['Plumber', 'Plumbers'], 'product' => ['Material', 'Materials']],
        ],
        'carpenter' => [
            'sector'  => 'services',
            'label'   => 'Carpentry & woodwork services',
            'preset'  => 'field_service',
            'aliases' => ['carpenter', 'carpentry', 'woodwork', 'woodworking service', 'joinery', 'furniture repair', 'kitchen fitting', 'door fitting', 'wardrobe fitting'],
            'terms'   => ['technician' => ['Carpenter', 'Carpenters'], 'product' => ['Material', 'Materials']],
        ],
        'painter_renovation' => [
            'sector'  => 'services',
            'label'   => 'Painters & renovation contractors',
            'preset'  => 'field_service',
            'aliases' => ['painter', 'painting contractor', 'house painting', 'renovation', 'renovation contractor', 'remodeling', 'remodelling', 'handyman', 'fit out', 'fitout', 'building contractor', 'civil contractor', 'construction contractor', 'maintenance company'],
            'terms'   => ['technician' => ['Crew Member', 'Crew Members'], 'job' => ['Project', 'Projects'], 'product' => ['Material', 'Materials']],
        ],
        'cleaning' => [
            'sector'  => 'services',
            'label'   => 'Cleaning & janitorial companies',
            'preset'  => 'field_service',
            'aliases' => ['cleaning', 'cleaning company', 'cleaning service', 'cleaners', 'janitorial', 'housekeeping', 'deep cleaning', 'maid service', 'car wash', 'sofa cleaning', 'carpet cleaning', 'laundry', 'dry cleaning', 'dry cleaner'],
            'terms'   => ['technician' => ['Cleaner', 'Cleaners'], 'product' => ['Supply', 'Supplies']],
        ],
        'hvac' => [
            'sector'  => 'services',
            'label'   => 'HVAC installation & maintenance',
            'preset'  => 'field_service',
            'aliases' => ['hvac', 'ac installation', 'air conditioning', 'air conditioning contractor', 'chiller', 'ventilation', 'duct cleaning', 'heating', 'cooling system', 'refrigeration'],
            'terms'   => ['product' => ['Part', 'Parts']],
        ],
        'pest_control' => [
            'sector'  => 'services',
            'label'   => 'Pest control services',
            'preset'  => 'field_service',
            'aliases' => ['pest control', 'fumigation', 'termite', 'termite control', 'exterminator', 'disinfection', 'sanitization'],
            'terms'   => ['product' => ['Chemical', 'Chemicals']],
        ],
        'equipment_rental' => [
            'sector'  => 'services',
            'label'   => 'Equipment & tool rental',
            'note'    => 'Tool check-out and check-in',
            'preset'  => 'rental_hire',
            'aliases' => ['equipment rental', 'tool rental', 'tool hire', 'equipment hire', 'plant hire', 'machinery rental', 'generator rental', 'scaffolding rental', 'rent out equipment', 'car rental', 'rent a car', 'costume rental'],
            'terms'   => ['sale' => ['Rental', 'Rentals'], 'order' => ['Booking', 'Bookings']],
        ],
        'event_hire' => [
            'sector'  => 'services',
            'label'   => 'Event decorators & sound hire',
            'preset'  => 'rental_hire',
            'aliases' => ['event decor', 'event decorator', 'decorator', 'sound system hire', 'sound hire', 'tent service', 'tent house', 'wedding decor', 'event management', 'event planner', 'dj', 'dj services', 'lighting hire', 'stage decoration'],
            'terms'   => ['order' => ['Booking', 'Bookings'], 'job' => ['Event', 'Events']],
        ],
        'gym_fitness' => [
            'sector'  => 'services',
            'label'   => 'Gyms, fitness studios & trainers',
            'note'    => 'Recurring memberships',
            'preset'  => 'membership_studio',
            'aliases' => ['gym', 'fitness', 'fitness studio', 'fitness centre', 'fitness center', 'personal trainer', 'yoga', 'yoga studio', 'crossfit', 'pilates', 'martial arts', 'boxing gym', 'dance studio', 'swimming academy'],
            'terms'   => ['customer' => ['Member', 'Members'], 'service' => ['Membership', 'Memberships'], 'staff' => ['Trainer', 'Trainers']],
        ],
        'tuition_academy' => [
            'sector'  => 'services',
            'label'   => 'Tuition centres & music/art academies',
            'preset'  => 'membership_studio',
            'aliases' => ['tuition', 'tuition centre', 'teach', 'teaching', 'classes', 'online classes', 'lessons', 'quran', 'quran teaching', 'coaching classes', 'tuition center', 'academy', 'coaching centre', 'coaching center', 'music school', 'music academy', 'art class', 'art academy', 'tutoring', 'tutor', 'language school', 'driving school', 'institute', 'training institute', 'quran academy', 'school'],
            'terms'   => ['customer' => ['Student', 'Students'], 'staff' => ['Teacher', 'Teachers'], 'service' => ['Course', 'Courses']],
        ],

        // ── retail ──────────────────────────────────────────────────────
        'grocery' => [
            'sector'  => 'retail',
            'label'   => 'Grocery & kiryana stores',
            'note'    => 'Loose weights, pack units, quick-pick',
            'preset'  => 'grocery',
            'aliases' => ['grocery', 'grocery store', 'kiryana', 'kiryana store', 'karyana', 'kirana', 'general store', 'provision store', 'departmental store', 'corner shop', 'dukan'],
        ],
        'supermarket' => [
            'sector'  => 'retail',
            'label'   => 'Supermarkets & minimarts',
            'note'    => 'High-speed scanning, scale barcodes',
            'preset'  => 'grocery',
            'modules' => ['stock_takes'],
            'aliases' => ['supermarket', 'minimart', 'mini mart', 'hypermarket', 'convenience store', 'mart', 'superstore'],
        ],
        'pharmacy' => [
            'sector'  => 'retail',
            'label'   => 'Pharmacies & medical stores',
            'note'    => 'Batches, expiry alerts, FEFO, drug registers',
            'preset'  => 'pharmacy',
            'aliases' => ['pharmacy', 'chemist', 'medical store', 'drug store', 'drugstore', 'dispensary', 'medicine shop', 'medicines'],
            'terms'   => ['customer' => ['Patient', 'Patients']],
        ],
        'surgical_supplies' => [
            'sector'  => 'retail',
            'label'   => 'Surgical & medical equipment suppliers',
            'preset'  => 'retail_shop',
            'modules' => ['batches_expiry', 'serials', 'purchases', 'suppliers'],
            'aliases' => ['surgical', 'surgical store', 'surgical instruments', 'medical equipment', 'hospital supplies', 'medical supplies', 'dental supplies', 'lab equipment'],
        ],
        'mobile_retail' => [
            'sector'  => 'retail',
            'label'   => 'Mobile phone & gadget retailers',
            'note'    => 'IMEI serials, instant warranty cards',
            'preset'  => 'mobile_electronics',
            'aliases' => ['mobile shop', 'phone shop', 'mobile store', 'cell phone store', 'gadget store', 'gadget shop', 'smartphone shop', 'mobile accessories', 'phone accessories'],
        ],
        'electronics' => [
            'sector'  => 'retail',
            'label'   => 'Consumer electronics & home appliances',
            'preset'  => 'mobile_electronics',
            'aliases' => ['electronics', 'electronics store', 'electronics shop', 'home appliances', 'appliance store', 'tv shop', 'led shop', 'computer shop', 'laptop shop', 'camera shop'],
        ],
        'fashion' => [
            'sector'  => 'retail',
            'label'   => 'Fashion & garment boutiques',
            'note'    => 'Size/colour matrix, WooCommerce sync',
            'preset'  => 'clothing',
            'aliases' => ['boutique', 'clothing', 'clothing store', 'clothes shop', 'garments', 'garment shop', 'fashion', 'apparel', 'readymade', 'abaya', 'kids wear', 'menswear', 'womenswear', 'lingerie'],
        ],
        'footwear' => [
            'sector'  => 'retail',
            'label'   => 'Shoe & footwear stores',
            'preset'  => 'clothing',
            'aliases' => ['shoe store', 'shoe shop', 'shoes', 'footwear', 'sneakers', 'sandals'],
        ],
        'jewellery' => [
            'sector'  => 'retail',
            'label'   => 'Jewellery & watch shops',
            'preset'  => 'retail_shop',
            'modules' => ['serials'],
            'aliases' => ['jewellery', 'jewelry', 'jeweller', 'jeweler', 'gold shop', 'goldsmith', 'watch shop', 'watches', 'artificial jewellery', 'silver'],
        ],
        'cosmetics' => [
            'sector'  => 'retail',
            'label'   => 'Cosmetics & perfume stores',
            'preset'  => 'retail_shop',
            'modules' => ['batches_expiry'],
            'aliases' => ['cosmetics', 'cosmetic shop', 'perfume', 'perfumes', 'makeup', 'beauty products', 'fragrance', 'attar', 'oud', 'skincare'],
        ],
        'hardware' => [
            'sector'  => 'retail',
            'label'   => 'Hardware & paint stores',
            'note'    => 'Sold by length, weight or piece',
            'preset'  => 'hardware_store',
            'aliases' => ['hardware', 'hardware store', 'hardware shop', 'paint store', 'paint shop', 'tools shop', 'tool shop'],
        ],
        'sanitary_supply' => [
            'sector'  => 'retail',
            'label'   => 'Sanitary & plumbing supply stores',
            'preset'  => 'hardware_store',
            'aliases' => ['sanitary store', 'sanitary shop', 'sanitary ware', 'sanitaryware', 'plumbing supplies', 'plumbing store', 'bathroom fittings', 'tiles', 'tiles shop', 'marble'],
        ],
        'building_materials' => [
            'sector'  => 'retail',
            'label'   => 'Building materials, cement & steel',
            'preset'  => 'hardware_store',
            'modules' => ['sales_orders'],
            'aliases' => ['building materials', 'cement', 'steel', 'construction materials', 'bricks', 'sand', 'sariya', 'rebar', 'timber', 'plywood', 'glass shop'],
        ],
        'furniture_store' => [
            'sector'  => 'retail',
            'label'   => 'Furniture & home décor stores',
            'preset'  => 'retail_shop',
            'modules' => ['sales_orders'],
            'aliases' => ['furniture store', 'furniture shop', 'furniture showroom', 'home decor', 'home décor', 'furnishing', 'mattress shop', 'curtains', 'carpets', 'rugs'],
        ],
        'books_stationery' => [
            'sector'  => 'retail',
            'label'   => 'Bookstores & stationery shops',
            'preset'  => 'retail_shop',
            'aliases' => ['bookstore', 'book shop', 'bookshop', 'books', 'stationery', 'stationary', 'stationery shop', 'school supplies', 'office stationery'],
        ],
        'toys' => [
            'sector'  => 'retail',
            'label'   => 'Toy & hobby stores',
            'preset'  => 'retail_shop',
            'aliases' => ['toy store', 'toy shop', 'toys', 'hobby shop', 'hobby store', 'games shop', 'video games'],
        ],
        'pet_supply' => [
            'sector'  => 'retail',
            'label'   => 'Pet supply stores',
            'preset'  => 'retail_shop',
            'modules' => ['batches_expiry'],
            'aliases' => ['pet shop', 'pet store', 'pet supplies', 'pet food', 'aquarium shop', 'bird shop'],
        ],
        'auto_parts' => [
            'sector'  => 'retail',
            'label'   => 'Auto spare parts & accessories',
            'preset'  => 'hardware_store',
            'modules' => ['serials'],
            'aliases' => ['auto parts', 'spare parts', 'car parts', 'car accessories', 'motor parts', 'auto spare parts', 'bike parts', 'car accessories shop'],
            'terms'   => ['product' => ['Part', 'Parts']],
        ],
        'tyre_battery' => [
            'sector'  => 'retail',
            'label'   => 'Tyre & battery dealers',
            'note'    => 'Serial and warranty tracking',
            'preset'  => 'mobile_electronics',
            'aliases' => ['tyre', 'tyres', 'tire', 'tires', 'tyre shop', 'battery', 'batteries', 'battery dealer', 'ups', 'inverter'],
        ],
        'optical' => [
            'sector'  => 'retail',
            'label'   => 'Eyewear & optical boutiques',
            'preset'  => 'retail_shop',
            'modules' => ['sales_orders'],
            'aliases' => ['optical', 'optical shop', 'optician', 'eyewear', 'glasses', 'spectacles', 'sunglasses', 'contact lenses'],
        ],
        'gift_flower' => [
            'sector'  => 'retail',
            'label'   => 'Gift, flower & craft shops',
            'preset'  => 'retail_shop',
            'aliases' => ['gift shop', 'flower shop', 'florist', 'flowers', 'craft shop', 'crafts', 'souvenir shop', 'balloons'],
        ],
        'vape_tobacco' => [
            'sector'  => 'retail',
            'label'   => 'Vape & tobacco stores',
            'preset'  => 'retail_shop',
            'aliases' => ['vape', 'vape shop', 'tobacco', 'smoke shop', 'cigarettes', 'paan shop', 'shisha shop'],
        ],
        'sports' => [
            'sector'  => 'retail',
            'label'   => 'Sports & outdoor equipment',
            'preset'  => 'clothing',
            'aliases' => ['sports shop', 'sports store', 'sporting goods', 'sports equipment', 'outdoor equipment', 'camping gear', 'fitness equipment', 'cricket shop', 'bicycle shop', 'cycle shop'],
        ],
        'electrical_lighting' => [
            'sector'  => 'retail',
            'label'   => 'Electrical & lighting stores',
            'preset'  => 'hardware_store',
            'aliases' => ['electrical store', 'electrical shop', 'electric shop', 'lighting', 'lights shop', 'lighting store', 'wires', 'cables', 'switches', 'electric store'],
        ],
        'kitchenware' => [
            'sector'  => 'retail',
            'label'   => 'Kitchenware & crockery stores',
            'preset'  => 'retail_shop',
            'aliases' => ['kitchenware', 'crockery', 'utensils', 'cookware', 'homeware', 'household items', 'plastic items', 'steel utensils'],
        ],

        // ── food ────────────────────────────────────────────────────────
        'restaurant' => [
            'sector'  => 'food',
            'label'   => 'Dine-in restaurants',
            'note'    => 'Floor plan, table service, split bills, kitchen tickets',
            'preset'  => 'restaurant',
            'aliases' => ['restaurant', 'dine in', 'dine-in', 'dhaba', 'eatery', 'diner', 'family restaurant', 'bbq restaurant', 'steakhouse', 'buffet', 'hotel restaurant'],
        ],
        'cafe' => [
            'sector'  => 'food',
            'label'   => 'Cafés & coffee houses',
            'note'    => 'Rapid counter POS, ingredient deduction',
            'preset'  => 'cafe',
            'aliases' => ['cafe', 'café', 'coffee shop', 'coffee house', 'coffee bar', 'espresso bar', 'coffee'],
        ],
        'tea_shop' => [
            'sector'  => 'food',
            'label'   => 'Chai & tea shops',
            'preset'  => 'cafe',
            'aliases' => ['chai', 'tea shop', 'tea stall', 'chai shop', 'tea house', 'karak', 'chai dhaba', 'tea'],
        ],
        'bakery' => [
            'sector'  => 'food',
            'label'   => 'Artisan bakeries & cake shops',
            'note'    => 'Advance orders, batch recipes',
            'preset'  => 'bakery',
            'aliases' => ['bakery', 'cake shop', 'cakes', 'patisserie', 'cupcakes', 'home baker', 'bakers', 'bake shop', 'pastry shop'],
        ],
        'fast_food' => [
            'sector'  => 'food',
            'label'   => 'Fast food, burger & pizza outlets',
            'preset'  => 'food_counter',
            'aliases' => ['fast food', 'burger', 'burgers', 'pizza', 'pizzeria', 'shawarma', 'fried chicken', 'broast', 'takeaway', 'take away', 'sandwich shop', 'fries', 'biryani', 'grill'],
        ],
        'dessert' => [
            'sector'  => 'food',
            'label'   => 'Ice cream & dessert parlours',
            'preset'  => 'food_counter',
            'aliases' => ['ice cream', 'ice cream parlour', 'dessert', 'desserts', 'gelato', 'frozen yogurt', 'kulfi', 'waffle', 'crepe'],
        ],
        'juice_bar' => [
            'sector'  => 'food',
            'label'   => 'Juice, shake & smoothie bars',
            'preset'  => 'food_counter',
            'aliases' => ['juice', 'juice bar', 'juice shop', 'shake', 'milkshake', 'smoothie', 'smoothie bar', 'sugarcane juice'],
        ],
        'food_truck' => [
            'sector'  => 'food',
            'label'   => 'Food trucks & kiosks',
            'note'    => 'Offline-first operation',
            'preset'  => 'food_counter',
            'aliases' => ['food truck', 'kiosk', 'food stall', 'food cart', 'street food', 'stall', 'food van'],
        ],
        'sweets' => [
            'sector'  => 'food',
            'label'   => 'Sweet & mithai shops',
            'note'    => 'Weighing scale and box packs',
            'preset'  => 'bakery',
            'modules' => ['units_of_measure'],
            'aliases' => ['sweet shop', 'sweets', 'mithai', 'mithai shop', 'halwai', 'confectionery', 'nimko', 'dry fruits'],
        ],
        'catering' => [
            'sector'  => 'food',
            'label'   => 'Catering businesses',
            'note'    => 'Event quotes, bulk recipes',
            'preset'  => 'catering',
            'aliases' => ['catering', 'caterer', 'caterers', 'event catering', 'banquet', 'wedding catering', 'tiffin service', 'meal prep', 'lunch boxes'],
            'terms'   => ['order' => ['Event Order', 'Event Orders']],
        ],
        'cloud_kitchen' => [
            'sector'  => 'food',
            'label'   => 'Cloud & dark kitchens',
            'preset'  => 'food_counter',
            'aliases' => ['cloud kitchen', 'dark kitchen', 'ghost kitchen', 'delivery kitchen', 'home kitchen', 'home chef', 'online food business'],
        ],
        'pub_lounge' => [
            'sector'  => 'food',
            'label'   => 'Pubs, bistros & lounges',
            'preset'  => 'restaurant',
            'aliases' => ['pub', 'bistro', 'lounge', 'bar', 'shisha lounge', 'hookah lounge', 'sports bar', 'rooftop'],
        ],

        // ── wholesale ───────────────────────────────────────────────────
        'fmcg_wholesale' => [
            'sector'  => 'wholesale',
            'label'   => 'FMCG & packaged-goods wholesalers',
            'note'    => 'Tiered prices, cartons to pieces',
            'preset'  => 'wholesale',
            'modules' => ['units_of_measure'],
            'aliases' => ['fmcg', 'wholesaler', 'wholesale', 'distributor', 'distribution', 'packaged goods', 'wholesale shop', 'dealer', 'stockist', 'supplier to shops', 'van sales', 'supply goods to shops', 'supply to shops', 'supply shops', 'sell to shops', 'supply retailers'],
        ],
        'grain_commodities' => [
            'sector'  => 'wholesale',
            'label'   => 'Grain, flour & bulk commodities',
            'preset'  => 'wholesale',
            'modules' => ['units_of_measure'],
            'aliases' => ['grain', 'grains', 'flour', 'atta', 'rice', 'commodities', 'bulk commodities', 'pulses', 'dal', 'sugar dealer', 'flour mill', 'arhat', 'commission agent'],
        ],
        'fabric_stockist' => [
            'sector'  => 'wholesale',
            'label'   => 'Garment & fabric stockists',
            'preset'  => 'wholesale',
            'modules' => ['variants', 'units_of_measure'],
            'aliases' => ['fabric', 'fabrics', 'cloth', 'cloth merchant', 'textile', 'textiles', 'garment stockist', 'lawn', 'unstitched', 'cloth house'],
        ],
        'hardware_wholesale' => [
            'sector'  => 'wholesale',
            'label'   => 'Hardware & tools wholesalers',
            'preset'  => 'wholesale',
            'aliases' => ['hardware wholesale', 'hardware wholesaler', 'tools wholesale', 'tools distributor', 'hardware distributor'],
        ],
        'electrical_wholesale' => [
            'sector'  => 'wholesale',
            'label'   => 'Electrical supplies wholesalers',
            'preset'  => 'wholesale',
            'aliases' => ['electrical wholesale', 'electrical wholesaler', 'electrical supplies', 'electrical distributor', 'cable distributor'],
        ],
        'pharma_wholesale' => [
            'sector'  => 'wholesale',
            'label'   => 'Pharmaceutical wholesalers & stockists',
            'preset'  => 'wholesale',
            'modules' => ['batches_expiry'],
            'aliases' => ['pharma distributor', 'pharmaceutical wholesale', 'pharmaceutical distributor', 'medicine distributor', 'medicine wholesale', 'pharma wholesaler', 'medical distributor', 'pharma wholesale', 'medicine supplier'],
        ],
        'tech_distributor' => [
            'sector'  => 'wholesale',
            'label'   => 'Mobile & tech distributors',
            'preset'  => 'wholesale',
            'modules' => ['serials'],
            'aliases' => ['mobile distributor', 'tech distributor', 'it distributor', 'electronics distributor', 'phone wholesale', 'mobile wholesale', 'computer wholesale'],
        ],
        'auto_parts_distributor' => [
            'sector'  => 'wholesale',
            'label'   => 'Auto parts distributors',
            'preset'  => 'wholesale',
            'aliases' => ['auto parts distributor', 'spare parts wholesale', 'auto parts wholesale', 'parts distributor'],
            'terms'   => ['product' => ['Part', 'Parts']],
        ],
        'packaging' => [
            'sector'  => 'wholesale',
            'label'   => 'Packaging & box suppliers',
            'preset'  => 'wholesale',
            'modules' => ['units_of_measure'],
            'aliases' => ['packaging', 'packaging supplier', 'boxes', 'cartons', 'corrugated boxes', 'shopping bags', 'packaging material', 'polythene bags'],
        ],
        'office_supplies' => [
            'sector'  => 'wholesale',
            'label'   => 'Stationery & office supplies',
            'preset'  => 'wholesale',
            'aliases' => ['office supplies', 'stationery wholesale', 'stationery supplier', 'office supply', 'printer supplies', 'toner'],
        ],
        'chemicals' => [
            'sector'  => 'wholesale',
            'label'   => 'Chemical & industrial cleaning',
            'preset'  => 'wholesale',
            'modules' => ['batches_expiry'],
            'aliases' => ['chemical', 'chemicals', 'cleaning chemicals', 'industrial cleaning', 'detergent supplier', 'industrial chemicals', 'lubricants', 'oil distributor'],
        ],
        'import_export' => [
            'sector'  => 'wholesale',
            'label'   => 'Import / export trading firms',
            'preset'  => 'wholesale',
            'aliases' => ['import', 'export', 'importer', 'exporter', 'import export', 'trading company', 'trading firm', 'general trading', 're-export'],
        ],

        // ── manufacturing ───────────────────────────────────────────────
        'commercial_bakery' => [
            'sector'  => 'manufacturing',
            'label'   => 'Commercial bakeries & confectioneries',
            'note'    => 'Flour and sugar to bread, deducted automatically',
            'preset'  => 'bakery',
            'modules' => ['purchases', 'suppliers', 'purchase_orders'],
            'aliases' => ['commercial bakery', 'bread factory', 'bakery factory', 'confectionery factory', 'biscuit factory', 'rusk', 'wholesale bakery'],
        ],
        'tailoring' => [
            'sector'  => 'manufacturing',
            'label'   => 'Tailoring & custom stitching workshops',
            'preset'  => 'tailoring',
            'aliases' => ['tailor', 'tailoring', 'tailor shop', 'stitching', 'stitching centre', 'darzi', 'alterations', 'alteration shop', 'dressmaker', 'bespoke tailoring', 'embroidery'],
            'terms'   => ['order' => ['Stitching Order', 'Stitching Orders']],
        ],
        'furniture_maker' => [
            'sector'  => 'manufacturing',
            'label'   => 'Furniture makers & woodworking',
            'note'    => 'Wood and hardware into a finished table',
            'preset'  => 'light_manufacturing',
            'aliases' => ['furniture maker', 'furniture manufacturer', 'make furniture', 'furniture on order', 'custom furniture', 'furniture making', 'made to order furniture', 'furniture factory', 'furniture workshop', 'woodworking', 'wood workshop', 'cabinet maker', 'kitchen cabinets'],
            'terms'   => ['order' => ['Work Order', 'Work Orders']],
        ],
        'coffee_spice' => [
            'sector'  => 'manufacturing',
            'label'   => 'Coffee roasters, spice blenders & craft drinks',
            'preset'  => 'light_manufacturing',
            'modules' => ['batches_expiry'],
            'aliases' => ['coffee roaster', 'roast coffee', 'coffee roasting', 'coffee beans', 'roast', 'roasting', 'roastery', 'spice', 'spices', 'spice blending', 'masala', 'masala factory', 'craft drinks', 'kombucha', 'tea blending', 'honey'],
        ],
        'signage_print' => [
            'sector'  => 'manufacturing',
            'label'   => 'Signage & custom print shops',
            'preset'  => 'light_manufacturing',
            'aliases' => ['signage', 'sign board', 'signboard', 'print shop', 'printing press', 'printing', 'flex printing', 'banners', 'screen printing', 'offset printing', 'panaflex', 'sticker printing'],
            'terms'   => ['order' => ['Print Order', 'Print Orders']],
        ],
        'soap_candle' => [
            'sector'  => 'manufacturing',
            'label'   => 'Soap & candle makers',
            'preset'  => 'light_manufacturing',
            'modules' => ['batches_expiry'],
            'aliases' => ['soap', 'soap maker', 'soap making', 'candle', 'candles', 'candle maker', 'handmade soap', 'skincare brand', 'cosmetics manufacturer'],
        ],
        'kit_assembly' => [
            'sector'  => 'manufacturing',
            'label'   => 'Hardware assembly & kit packing',
            'preset'  => 'light_manufacturing',
            'aliases' => ['assembly', 'assembly unit', 'kit packing', 'hardware assembly', 'packing unit', 'repacking', 'contract packing'],
        ],
        'aluminium_glass' => [
            'sector'  => 'manufacturing',
            'label'   => 'Aluminium & glass fabrication',
            'preset'  => 'light_manufacturing',
            'modules' => ['services'],
            'aliases' => ['aluminium', 'aluminum', 'aluminium fabrication', 'glass', 'glass fabrication', 'windows and doors', 'upvc', 'steel fabrication', 'welding', 'metal fabrication'],
            'terms'   => ['order' => ['Work Order', 'Work Orders']],
        ],
        'leather_goods' => [
            'sector'  => 'manufacturing',
            'label'   => 'Leather goods & bag makers',
            'preset'  => 'light_manufacturing',
            'modules' => ['variants'],
            'aliases' => ['leather', 'leather goods', 'bags', 'bag maker', 'handbags', 'wallets', 'belts', 'leather workshop'],
        ],
        'custom_merch' => [
            'sector'  => 'manufacturing',
            'label'   => 'Custom gift & merchandise assembly',
            'preset'  => 'light_manufacturing',
            'aliases' => ['custom gifts', 'merchandise', 'merch', 'promotional products', 'corporate gifts', 'printed mugs', 'custom t-shirts', 'hampers', 'gift hampers'],
        ],
    ],
];
