<?php
header('Content-Type: text/plain'); set_time_limit(300);
use Illuminate\Support\Str; use Carbon\Carbon;
$T=1; $uid=auth()->id(); $now=now();
$run = function($label,$fn){ try { $n=$fn(); echo "OK  $label: $n\n"; } catch (\Throwable $e) { echo "ERR $label: ".substr($e->getMessage(),0,220)."\n"; } };
$wh = DB::table('warehouses')->where('tenant_id',$T)->orderBy('id')->pluck('id')->all();
$prods = DB::table('products')->where('tenant_id',$T)->orderBy('id')->limit(14)->get(['id','name','cost_price','price']);
$sups = DB::table('parties')->where('tenant_id',$T)->where('type','supplier')->orderBy('id')->limit(8)->get();
$d = fn($ago)=>Carbon::now()->subDays($ago)->toDateString();

$run('customers table', function() use($T,$now){ $n=0; foreach (DB::table('parties')->where('tenant_id',$T)->where('type','customer')->get() as $p){ if(DB::table('customers')->where('party_id',$p->id)->exists()) continue; DB::table('customers')->insert(['id'=>(string)Str::uuid(),'tenant_id'=>$T,'party_id'=>$p->id,'name'=>$p->name,'email'=>$p->email,'phone'=>$p->phone,'address'=>$p->address,'credit_limit'=>$p->credit_limit ?? 0,'loyalty_points'=>rand(0,900),'created_at'=>$now,'updated_at'=>$now]); $n++; } return $n; });
$run('suppliers table', function() use($T,$now){ $n=0; foreach (DB::table('parties')->where('tenant_id',$T)->where('type','supplier')->get() as $p){ if(DB::table('suppliers')->where('party_id',$p->id)->exists()) continue; DB::table('suppliers')->insert(['id'=>(string)Str::uuid(),'tenant_id'=>$T,'party_id'=>$p->id,'name'=>$p->name,'email'=>$p->email,'phone'=>$p->phone,'address'=>$p->address,'payment_terms'=>$p->payment_terms ?: 'Net 30','lead_time_days'=>rand(3,14),'performance_rating'=>rand(38,50)/10,'created_at'=>$now,'updated_at'=>$now]); $n++; } return $n; });

$run('purchase orders', function() use($T,$uid,$wh,$prods,$sups,$now,$d){ $n=0; $st=['pending','pending','pending','pending','pending','pending'];
  foreach ($st as $i=>$s){ $sup=$sups[$i % count($sups)]; $sid = DB::table('suppliers')->where('party_id',$sup->id)->value('id'); $id=(string)Str::uuid(); DB::table('purchase_orders')->insert(['id'=>$id,'tenant_id'=>$T,'supplier_id'=>$sid,'warehouse_id'=>$wh[0],'reference_number'=>'PO-'.date('y').'-'.str_pad($i+101,4,'0',STR_PAD_LEFT),'status'=>$s,'order_date'=>$d(3+$i*4),'expected_delivery_date'=>$d(-4+$i*-2),'total_amount'=>0,'user_id'=>$uid,'created_at'=>$now,'updated_at'=>$now]);
    $tot=0; foreach ([0,1,2] as $k){ $p=$prods[($i*3+$k)%count($prods)]; $q=rand(10,60); $c=(float)$p->cost_price; $t=$q*$c; $tot+=$t; DB::table('purchase_order_items')->insert(['id'=>(string)Str::uuid(),'tenant_id'=>$T,'purchase_order_id'=>$id,'product_id'=>$p->id,'quantity'=>$q,'unit_cost'=>$c,'total_cost'=>$t,'received_quantity'=>0,'created_at'=>$now,'updated_at'=>$now]); }
    DB::table('purchase_orders')->where('id',$id)->update(['total_amount'=>$tot]); $n++; } return $n; });

$run('stock transfers', function() use($T,$uid,$wh,$prods,$now,$d){ $n=0; $st=['completed','completed','in_progress','pending','completed'];
  foreach ($st as $i=>$s){ $id=(string)Str::uuid(); DB::table('stock_transfers')->insert(['id'=>$id,'tenant_id'=>$T,'reference_number'=>'TRF-'.str_pad($i+1,4,'0',STR_PAD_LEFT),'from_warehouse_id'=>$wh[0],'to_warehouse_id'=>$wh[1 + ($i%2)] ?? $wh[1],'transfer_date'=>$d(2+$i*5),'status'=>$s,'notes'=>'Branch restock','created_by'=>$uid,'completed_at'=>$s==='completed'?$now:null,'created_at'=>$now,'updated_at'=>$now]);
    foreach ([0,1,2] as $k){ $p=$prods[($i*2+$k)%count($prods)]; $q=rand(5,25); DB::table('stock_transfer_items')->insert(['id'=>(string)Str::uuid(),'tenant_id'=>$T,'stock_transfer_id'=>$id,'product_id'=>$p->id,'quantity'=>$q,'received_quantity'=>$s==='completed'?$q:0,'created_at'=>$now,'updated_at'=>$now]); } $n++; } return $n; });

$run('stock takes', function() use($T,$uid,$wh,$prods,$now,$d){ $n=0; foreach (['completed','completed','draft'] as $i=>$s){ $id=(string)Str::uuid(); DB::table('stock_takes')->insert(['id'=>$id,'tenant_id'=>$T,'reference_number'=>'ST-'.str_pad($i+1,4,'0',STR_PAD_LEFT),'warehouse_id'=>$wh[$i%count($wh)],'date'=>$d(6+$i*20),'status'=>$s,'notes'=>'Cycle count','created_by'=>$uid,'created_at'=>$now,'updated_at'=>$now]);
    foreach ($prods as $k=>$p){ if($k>7) break; $exp=rand(100,300); $cnt=$exp+rand(-3,2); DB::table('stock_take_items')->insert(['id'=>(string)Str::uuid(),'tenant_id'=>$T,'stock_take_id'=>$id,'product_id'=>$p->id,'expected_quantity'=>$exp,'counted_quantity'=>$s==='draft'?$exp:$cnt,'difference'=>$s==='draft'?0:$cnt-$exp,'cost_price'=>$p->cost_price,'created_at'=>$now,'updated_at'=>$now]); } $n++; } return $n; });

$run('production runs', function() use($T,$uid,$wh,$prods,$now,$d){ $n=0; foreach (range(0,13) as $i){ $p=$prods[$i%count($prods)]; $q=rand(20,120); $mat=round($q*(float)$p->cost_price*0.8,2); $lab=round($q*rand(2,6),2); $s=$i<2?'in_progress':'completed';
    DB::table('production_runs')->insert(['id'=>(string)Str::uuid(),'tenant_id'=>$T,'product_id'=>$p->id,'quantity'=>$q,'date'=>$d(2+$i*9),'status'=>$s,'notes'=>'Batch run #'.($i+1),'warehouse_id'=>$wh[0],'planned_qty'=>$q,'actual_qty'=>$s==='completed'?$q-rand(0,3):null,'material_cost'=>$mat,'labor_cost'=>$lab,'total_cost'=>$mat+$lab,'created_by'=>$uid,'completed_at'=>$s==='completed'?$now:null,'created_at'=>$now,'updated_at'=>$now]); $n++; } return $n; });

$run('product batches', function() use($T,$prods,$now){ $n=0; foreach ($prods as $i=>$p){ foreach ([0,1] as $k){ $q=rand(40,200); DB::table('product_batches')->insert(['id'=>(string)Str::uuid(),'tenant_id'=>$T,'product_id'=>$p->id,'batch_number'=>'LOT-'.date('y').str_pad($i*2+$k+1,3,'0',STR_PAD_LEFT),'manufacturing_date'=>Carbon::now()->subDays(rand(30,120))->toDateString(),'expiry_date'=>Carbon::now()->addDays($k==0?rand(10,70):rand(150,500))->toDateString(),'initial_quantity'=>$q,'current_quantity'=>(int)($q*rand(40,100)/100),'created_at'=>$now,'updated_at'=>$now]); $n++; } } return $n; });

$run('cheque books', function() use($T,$uid,$now,$d){ $ba=DB::table('bank_accounts')->where('tenant_id',$T)->orderBy('id')->first(); if(!$ba) return 'no bank account'; $n=0;
  foreach ([100001,100051] as $i=>$st){ $b=(string)Str::uuid(); DB::table('cheque_books')->insert(['id'=>$b,'tenant_id'=>$T,'bank_account_id'=>$ba->id,'book_number'=>'CB-'.($i+1),'serial_start'=>$st,'serial_end'=>$st+49,'total_leaves'=>50,'received_date'=>$d(90-$i*40),'status'=>'active','created_by'=>$uid,'created_at'=>$now,'updated_at'=>$now]);
    for($s=$st;$s<$st+50;$s++){ $used=$i==0 && $s<$st+14; DB::table('cheque_leaves')->insert(['id'=>(string)Str::uuid(),'tenant_id'=>$T,'cheque_book_id'=>$b,'bank_account_id'=>$ba->id,'normalized_serial_number'=>(string)$s,'display_serial_number'=>(string)$s,'numeric_serial'=>$s,'serial_number'=>(string)$s,'status'=>$used?($s<$st+10?'cleared':'issued'):'available','created_by'=>$uid,'created_at'=>$now,'updated_at'=>$now]); } $n++; } return $n; });
