<?php

return [
    'default' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash-lite',
        'thinking'       => 0,
        'max_output'     => 1024,
        'context_budget' => 3000,
        'timeout'        => 20,
        'est_cost_usd'   => 0.0010,
    ],
    'scan_handwritten' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash',
        'thinking'       => 256,
        'max_output'     => 2048,
        'context_budget' => 4000,
        'timeout'        => 30,
        'est_cost_usd'   => 0.0050,
    ],
    'scan_printed' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash-lite',
        'thinking'       => 0,
        'max_output'     => 2048,
        'context_budget' => 3000,
        'timeout'        => 30,
        'est_cost_usd'   => 0.0030,
    ],
    'audio' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash',
        'thinking'       => 256,
        'max_output'     => 2048,
        'context_budget' => 3000,
        'timeout'        => 30,
        'est_cost_usd'   => 0.0050,
    ],
    'match_fallback' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash-lite',
        'thinking'       => 0,
        'max_output'     => 1024,
        'context_budget' => 2000,
        'timeout'        => 20,
        'est_cost_usd'   => 0.0005,
    ],
    'query' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash-lite',
        'thinking'       => 0,
        'max_output'     => 1024,
        'context_budget' => 3000,
        'timeout'        => 20,
        'est_cost_usd'   => 0.0015,
    ],
    'populate' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash-lite',
        'thinking'       => 0,
        'max_output'     => 1024,
        'context_budget' => 3000,
        'timeout'        => 20,
        'est_cost_usd'   => 0.0010,
    ],
    'list_import' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash',
        'thinking'       => 256,
        'max_output'     => 2048,
        'context_budget' => 4000,
        'timeout'        => 30,
        'est_cost_usd'   => 0.0050,
    ],
    'catalog' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash-lite',
        'thinking'       => 0,
        'max_output'     => 1024,
        'context_budget' => 2000,
        'timeout'        => 25,
        'est_cost_usd'   => 0.0010,
    ],
    'visitor_chat' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash-lite',
        'thinking'       => 0,
        'max_output'     => 300,
        'context_budget' => 2000,
        'timeout'        => 20,
        'est_cost_usd'   => 0.0010,
    ],
    'public_tool' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash',
        'thinking'       => 256,
        'max_output'     => 2048,
        'context_budget' => 3000,
        'timeout'        => 30,
        'est_cost_usd'   => 0.0120,
    ],
    'config_ai' => [
        'provider'       => 'gemini',
        'model'          => 'gemini-2.5-flash-lite',
        'thinking'       => 0,
        'max_output'     => 1500,
        'context_budget' => 3000,
        'timeout'        => 25,
        'est_cost_usd'   => 0.0020,
    ],

    // ── Phase 9 (T9-6): Deprecation timeline & successor fallbacks ──────────
    'deprecation_audit' => [
        'gemini-2.5-flash' => [
            'deprecation_date'   => '2026-10-16',
            'fallback_successor' => 'gemini-2.5-flash-lite',
        ],
        'gemini-2.5-flash-lite' => [
            'deprecation_date'   => '2026-10-16',
            'fallback_successor' => 'gemini-1.5-flash',
        ],
    ],
];
