<?php

/**
 * VenQore Canonical Dashboard Role Pools & Presets
 * Curated presets strictly <= 40 cards per role.
 */

return array (
  'roles' =>
  array (
    'owner' =>
    array (
      0 => 'core.revenue',
      1 => 'core.revenue_trend',
      2 => 'core.net_profit',
      3 => 'core.profit_trend',
      4 => 'core.gross_profit',
      5 => 'core.gross_margin_pct',
      6 => 'core.net_margin_pct',
      7 => 'core.cogs',
      8 => 'core.expenses_total',
      9 => 'core.total_liquidity',
      10 => 'core.liquidity_trend',
      11 => 'core.cash_flow_trend',
      12 => 'core.net_cash_position',
      13 => 'core.working_capital',
      14 => 'core.receivables',
      15 => 'core.receivables_aging',
      16 => 'core.payables',
      17 => 'core.payables_aging',
      18 => 'pos.revenue',
      19 => 'pos.sale_count',
      20 => 'pos.avg_ticket',
      21 => 'inventory.stock_value',
      22 => 'inventory.low_stock_count',
      23 => 'approval.awaiting_review',
    ),
    'admin' =>
    array (
      0 => 'core.revenue',
      1 => 'core.revenue_trend',
      2 => 'core.net_profit',
      3 => 'core.profit_trend',
      4 => 'core.gross_profit',
      5 => 'core.gross_margin_pct',
      6 => 'core.net_margin_pct',
      7 => 'core.cogs',
      8 => 'core.expenses_total',
      9 => 'core.total_liquidity',
      10 => 'core.liquidity_trend',
      11 => 'core.cash_flow_trend',
      12 => 'core.net_cash_position',
      13 => 'core.working_capital',
      14 => 'core.receivables',
      15 => 'core.receivables_aging',
      16 => 'core.payables',
      17 => 'core.payables_aging',
      18 => 'pos.revenue',
      19 => 'pos.sale_count',
      20 => 'pos.avg_ticket',
      21 => 'inventory.stock_value',
      22 => 'inventory.low_stock_count',
      23 => 'approval.awaiting_review',
    ),
    'manager' =>
    array (
      0 => 'core.revenue',
      1 => 'core.revenue_trend',
      2 => 'core.gross_profit',
      3 => 'core.gross_margin_pct',
      4 => 'core.expenses_total',
      5 => 'core.receivables',
      6 => 'core.payables',
      7 => 'pos.revenue',
      8 => 'pos.revenue_trend',
      9 => 'pos.sale_count',
      10 => 'pos.avg_ticket',
      11 => 'pos.payment_breakdown',
      12 => 'inventory.stock_value',
      13 => 'inventory.low_stock_count',
      14 => 'inventory.out_of_stock_count',
      15 => 'inventory.turnover_ratio',
      16 => 'invoicing.count',
      17 => 'invoicing.unpaid_value',
      18 => 'approval.awaiting_review',
      19 => 'approval.pending_aging',
    ),
    'accountant' =>
    array (
      0 => 'core.revenue',
      1 => 'core.net_profit',
      2 => 'core.gross_profit',
      3 => 'core.cogs',
      4 => 'core.expenses_total',
      5 => 'core.expense_ratio',
      6 => 'core.receivables',
      7 => 'core.receivables_aging',
      8 => 'core.payables',
      9 => 'core.payables_aging',
      10 => 'core.total_liquidity',
      11 => 'core.liquidity_trend',
      12 => 'core.cash_flow_trend',
      13 => 'core.net_cash_position',
      14 => 'core.working_capital',
      15 => 'core.balance_sheet_ok',
      16 => 'approval.awaiting_review',
      17 => 'approval.pending_aging',
    ),
    'inventory_controller' =>
    array (
      0 => 'inventory.stock_value',
      1 => 'inventory.stock_value_trend',
      2 => 'inventory.low_stock_count',
      3 => 'inventory.out_of_stock_count',
      4 => 'inventory.turnover_ratio',
      5 => 'inventory.dead_stock_value',
      6 => 'inventory.units_on_hand',
      7 => 'inventory.low_stock_list',
      8 => 'stocktakes.pending_count',
      9 => 'stocktakes.variance_value',
      10 => 'purchases.spend',
      11 => 'purchases.count',
      12 => 'products.count',
      13 => 'products.active_count',
    ),
    'shift_supervisor' =>
    array (
      0 => 'pos.revenue',
      1 => 'pos.revenue_trend',
      2 => 'pos.sale_count',
      3 => 'pos.avg_ticket',
      4 => 'pos.max_sale',
      5 => 'pos.items_per_sale',
      6 => 'pos.payment_breakdown',
      7 => 'pos.hourly_heatmap',
      8 => 'pos.discount_total',
      9 => 'pos.live_feed',
      10 => 'register.open_count',
      11 => 'register.variance_total',
      12 => 'tables.occupied',
      13 => 'tables.occupancy_rate',
    ),
    'purchasing_officer' =>
    array (
      0 => 'purchases.spend',
      1 => 'purchases.spend_trend',
      2 => 'purchases.count',
      3 => 'purchases.unpaid_value',
      4 => 'purchases.by_supplier',
      5 => 'suppliers.count',
      6 => 'suppliers.active',
      7 => 'suppliers.top_suppliers',
      8 => 'suppliers.spend_total',
      9 => 'suppliers.owed_list',
      10 => 'inventory.low_stock_count',
      11 => 'inventory.low_stock_list',
    ),
    'sales_executive' =>
    array (
      0 => 'pos.revenue',
      1 => 'pos.sale_count',
      2 => 'pos.avg_ticket',
      3 => 'pos.discount_total',
      4 => 'invoicing.count',
      5 => 'invoicing.value',
      6 => 'invoicing.unpaid_value',
      7 => 'quotations.count',
      8 => 'quotations.open_value',
      9 => 'quotations.win_rate',
      10 => 'sales_orders.open_count',
      11 => 'sales_orders.open_value',
    ),
    'cashier' =>
    array (
      0 => 'pos.revenue',
      1 => 'pos.sale_count',
      2 => 'pos.avg_ticket',
      3 => 'pos.items_per_sale',
      4 => 'pos.payment_breakdown',
      5 => 'pos.hourly_heatmap',
      6 => 'pos.discount_total',
      7 => 'pos.live_feed',
      8 => 'products.count',
      9 => 'customers.count',
    ),
    'viewer' =>
    array (
      0 => 'core.revenue',
      1 => 'core.revenue_trend',
      2 => 'pos.revenue',
      3 => 'pos.sale_count',
      4 => 'invoicing.count',
      5 => 'products.count',
      6 => 'inventory.stock_value',
      7 => 'customers.count',
    ),
  ),
  'business' =>
  array (
    'default' =>
    array (
      0 => 'core.revenue',
      1 => 'core.net_profit',
      2 => 'core.gross_profit',
      3 => 'core.total_liquidity',
      4 => 'core.receivables',
      5 => 'core.payables',
      6 => 'core.revenue_trend',
      7 => 'products.count',
      8 => 'inventory.stock_value',
      9 => 'inventory.low_stock_count',
      10 => 'customers.count',
      11 => 'core.balance_sheet_ok',
    ),
  ),
  'aliases' =>
  array (
    'retail_store' => 'default',
    'grocery' => 'default',
    'pharmacy' => 'default',
    'apparel' => 'default',
    'electronics' => 'default',
    'services' => 'default',
  ),
);
