<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Add source and escalation_type columns to support_tickets.
 *
 * source           — identifies where the ticket originated (e.g. 'vena_chat', 'manual').
 *                    Used to filter tickets in the Vena Tickets inbox page.
 * escalation_type  — categorises why the ticket was created (for triage priority).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('support_tickets', function (Blueprint $table) {
            // Where the ticket came from. 'vena_chat' = auto-generated by Vena widget.
            $table->string('source', 50)->nullable()->default(null)->after('priority');

            // Why escalation happened — for the support inbox triage display.
            // Values: 'ai_failure', 'billing_or_complex', 'user_requested', 'repeated_failure'
            $table->string('escalation_type', 50)->nullable()->default(null)->after('source');

            $table->index('source'); // Allow fast filter by source in the tickets page
        });
    }

    public function down(): void
    {
        Schema::table('support_tickets', function (Blueprint $table) {
            $table->dropIndex(['source']);
            $table->dropColumn(['source', 'escalation_type']);
        });
    }
};
