<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\SupportTicket;
use App\Models\Tenant;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

/**
 * VenaTicketsController
 *
 * Handles the Vena Chat Tickets inbox — tickets auto-generated by the Vena
 * widget when an escalation happens and agents are offline.
 *
 * Two contexts:
 *   1. Platform (Super Admin)  — all stores, route prefix: /VenQore/vena-tickets
 *   2. Store Admin (per-store) — only this store's tickets, route prefix: /s/{slug}/admin/vena-tickets
 */
class VenaTicketsController extends Controller
{
    // ── Platform Super Admin ──────────────────────────────────────────────────

    /**
     * List all Vena-generated tickets across all stores.
     * Accessible at: GET /VenQore/vena-tickets
     */
    public function index(Request $request): Response
    {
        $query = SupportTicket::withoutGlobalScopes()
            ->where('source', 'vena_chat')
            ->with(['tenant:id,name,slug'])
            ->latest();

        // Status filter
        if ($request->filled('status') && $request->status !== 'all') {
            $query->where('status', $request->status);
        }

        // Escalation type filter
        if ($request->filled('escalation_type') && $request->escalation_type !== 'all') {
            $query->where('escalation_type', $request->escalation_type);
        }

        $tickets = $query->paginate(25)->withQueryString();

        return Inertia::render('Admin/VenaTickets', [
            'tickets'      => $tickets,
            'context'      => 'platform',
            'filters'      => $request->only(['status', 'escalation_type']),
            'open_count'   => SupportTicket::withoutGlobalScopes()->where('source', 'vena_chat')->where('status', 'open')->count(),
        ]);
    }

    /**
     * Show a single Vena ticket with full chat transcript.
     * Accessible at: GET /VenQore/vena-tickets/{ticket}
     */
    public function show(SupportTicket $ticket): Response
    {
        abort_if($ticket->source !== 'vena_chat', 404);

        $ticket->load('tenant:id,name,slug');

        return Inertia::render('Admin/VenaTicketDetail', [
            'ticket'  => $ticket,
            'context' => 'platform',
        ]);
    }

    /**
     * Update ticket status from the platform inbox.
     * Accessible at: POST /VenQore/vena-tickets/{ticket}/status
     */
    public function updateStatus(Request $request, SupportTicket $ticket): RedirectResponse
    {
        abort_if($ticket->source !== 'vena_chat', 404);

        $data = $request->validate([
            'status' => 'required|in:open,in_progress,resolved,closed',
        ]);

        $ticket->update([
            'status'      => $data['status'],
            'resolved_at' => in_array($data['status'], ['resolved', 'closed']) ? now() : null,
        ]);

        return back()->with('success', 'Ticket status updated.');
    }

    // ── Store Admin (per-store context) ────────────────────────────────────────

    /**
     * List Vena tickets for THIS store only.
     * Accessible at: GET /s/{store_slug}/admin/vena-tickets
     */
    public function storeIndex(Request $request): Response
    {
        $tenant = app('current.tenant');

        $query = SupportTicket::withoutGlobalScopes()
            ->where('source', 'vena_chat')
            ->where('tenant_id', $tenant->id)
            ->latest();

        if ($request->filled('status') && $request->status !== 'all') {
            $query->where('status', $request->status);
        }

        $tickets = $query->paginate(20)->withQueryString();

        return Inertia::render('Admin/VenaTickets', [
            'tickets'    => $tickets,
            'context'    => 'store',
            'filters'    => $request->only(['status']),
            'open_count' => SupportTicket::withoutGlobalScopes()
                ->where('source', 'vena_chat')
                ->where('tenant_id', $tenant->id)
                ->where('status', 'open')
                ->count(),
        ]);
    }

    /**
     * Show a single Vena ticket scoped to this store.
     */
    public function storeShow(SupportTicket $ticket): Response
    {
        $tenant = app('current.tenant');

        abort_if($ticket->source !== 'vena_chat', 404);
        abort_if($ticket->tenant_id !== $tenant->id, 403);

        return Inertia::render('Admin/VenaTicketDetail', [
            'ticket'  => $ticket,
            'context' => 'store',
        ]);
    }

    /**
     * Log a manual support ticket from the store admin panel.
     */
    public function storeCreateTicket(Request $request): RedirectResponse
    {
        $tenant = app('current.tenant');

        $data = $request->validate([
            'requester_name'  => 'required|string|max:255',
            'requester_email' => 'required|email|max:255',
            'subject'         => 'required|string|max:255',
            'message'         => 'required|string|max:5000',
            'priority'        => 'required|in:low,normal,high,urgent',
        ]);

        SupportTicket::create([
            'tenant_id'       => $tenant->id,
            'submitted_by'    => auth()->id(),
            'subject'         => $data['subject'],
            'message'         => $data['message'],
            'status'          => 'open',
            'priority'        => $data['priority'],
            'source'          => 'vena_chat', // keeping it visible in the vena-tickets inbox tab
            'escalation_type' => 'user_requested', // logged by user
            'requester_name'  => $data['requester_name'],
            'requester_email' => $data['requester_email'],
        ]);

        return back()->with('success', 'Support ticket logged successfully.');
    }

    /**
     * Update ticket status from the store admin inbox.
     */
    public function storeUpdateStatus(Request $request, SupportTicket $ticket): RedirectResponse
    {
        $tenant = app('current.tenant');

        abort_if($ticket->source !== 'vena_chat', 404);
        abort_if($ticket->tenant_id !== $tenant->id, 403);

        $data = $request->validate([
            'status' => 'required|in:open,in_progress,resolved,closed',
        ]);

        $ticket->update([
            'status'      => $data['status'],
            'resolved_at' => in_array($data['status'], ['resolved', 'closed']) ? now() : null,
        ]);

        return back()->with('success', 'Ticket status updated.');
    }
}
