<?php

namespace App\Reckoner\Resolvers;

use App\Reckoner\CardRegistry;
use App\Reckoner\ReckonerContext;
use App\Reckoner\ReckonerPeriod;
use App\Reckoner\ReckonerResult;

final class ResolverRegistry
{
    private const MAP = [
        'core.revenue' => \App\Reckoner\Resolvers\CoreRevenueResolver::class,
        'core.revenue_trend' => \App\Reckoner\Resolvers\CoreRevenueTrendResolver::class,
        'core.net_profit' => \App\Reckoner\Resolvers\CoreNetProfitResolver::class,
        'core.profit_trend' => \App\Reckoner\Resolvers\CoreProfitTrendResolver::class,
        'core.gross_profit' => \App\Reckoner\Resolvers\CoreGrossProfitResolver::class,
        'core.gross_margin_pct' => \App\Reckoner\Resolvers\CoreGrossMarginPctResolver::class,
        'core.net_margin_pct' => \App\Reckoner\Resolvers\CoreNetMarginPctResolver::class,
        'core.cogs' => \App\Reckoner\Resolvers\CoreCogsResolver::class,
        'core.expenses_total' => \App\Reckoner\Resolvers\CoreExpensesTotalResolver::class,
        'core.expense_ratio' => \App\Reckoner\Resolvers\CoreExpenseRatioResolver::class,
        'core.receivables' => \App\Reckoner\Resolvers\CoreReceivablesResolver::class,
        'core.receivables_aging' => \App\Reckoner\Resolvers\CoreReceivablesAgingResolver::class,
        'core.payables' => \App\Reckoner\Resolvers\CorePayablesResolver::class,
        'core.payables_aging' => \App\Reckoner\Resolvers\CorePayablesAgingResolver::class,
        'core.total_liquidity' => \App\Reckoner\Resolvers\CoreTotalLiquidityResolver::class,
        'core.liquidity_trend' => \App\Reckoner\Resolvers\CoreLiquidityTrendResolver::class,
        'core.cash_flow_trend' => \App\Reckoner\Resolvers\CoreCashFlowTrendResolver::class,
        'core.net_cash_position' => \App\Reckoner\Resolvers\CoreNetCashPositionResolver::class,
        'core.working_capital' => \App\Reckoner\Resolvers\CoreWorkingCapitalResolver::class,
        'core.revenue_vs_prev' => \App\Reckoner\Resolvers\CoreRevenueVsPrevResolver::class,
        'core.profit_vs_prev' => \App\Reckoner\Resolvers\CoreProfitVsPrevResolver::class,
        'core.transaction_count' => \App\Reckoner\Resolvers\CoreTransactionCountResolver::class,
        'core.avg_transaction_value' => \App\Reckoner\Resolvers\CoreAvgTransactionValueResolver::class,
        'core.busiest_day' => \App\Reckoner\Resolvers\CoreBusiestDayResolver::class,
        'core.peak_hour' => \App\Reckoner\Resolvers\CorePeakHourResolver::class,
        'core.balance_sheet_ok' => \App\Reckoner\Resolvers\CoreBalanceSheetOkResolver::class,
        'core.journal_entries_count' => \App\Reckoner\Resolvers\CoreJournalEntriesCountResolver::class,
        'core.audit_trail_count' => \App\Reckoner\Resolvers\CoreAuditTrailCountResolver::class,
        'core.reversal_count' => \App\Reckoner\Resolvers\CoreReversalCountResolver::class,
        'core.document_sequence_ok' => \App\Reckoner\Resolvers\CoreDocumentSequenceOkResolver::class,
        'core.user_activity' => \App\Reckoner\Resolvers\CoreUserActivityResolver::class,
        'core.plan_usage' => \App\Reckoner\Resolvers\CorePlanUsageResolver::class,
        'products.count' => \App\Reckoner\Resolvers\ProductsCountResolver::class,
        'products.active_count' => \App\Reckoner\Resolvers\ProductsActiveCountResolver::class,
        'products.by_category' => \App\Reckoner\Resolvers\ProductsByCategoryResolver::class,
        'products.catalogue_value' => \App\Reckoner\Resolvers\ProductsCatalogueValueResolver::class,
        'products.avg_margin' => \App\Reckoner\Resolvers\ProductsAvgMarginResolver::class,
        'products.top_margin' => \App\Reckoner\Resolvers\ProductsTopMarginResolver::class,
        'products.lowest_margin' => \App\Reckoner\Resolvers\ProductsLowestMarginResolver::class,
        'products.never_sold' => \App\Reckoner\Resolvers\ProductsNeverSoldResolver::class,
        'products.missing_cost' => \App\Reckoner\Resolvers\ProductsMissingCostResolver::class,
        'products.new_this_period' => \App\Reckoner\Resolvers\ProductsNewThisPeriodResolver::class,
        'services.count' => \App\Reckoner\Resolvers\ServicesCountResolver::class,
        'services.revenue' => \App\Reckoner\Resolvers\ServicesRevenueResolver::class,
        'services.revenue_trend' => \App\Reckoner\Resolvers\ServicesRevenueTrendResolver::class,
        'services.share_of_revenue' => \App\Reckoner\Resolvers\ServicesShareOfRevenueResolver::class,
        'services.top_services' => \App\Reckoner\Resolvers\ServicesTopServicesResolver::class,
        'services.avg_ticket' => \App\Reckoner\Resolvers\ServicesAvgTicketResolver::class,
        'services.jobs_count' => \App\Reckoner\Resolvers\ServicesJobsCountResolver::class,
        'customers.count' => \App\Reckoner\Resolvers\CustomersCountResolver::class,
        'customers.new' => \App\Reckoner\Resolvers\CustomersNewResolver::class,
        'customers.new_trend' => \App\Reckoner\Resolvers\CustomersNewTrendResolver::class,
        'customers.active' => \App\Reckoner\Resolvers\CustomersActiveResolver::class,
        'customers.dormant' => \App\Reckoner\Resolvers\CustomersDormantResolver::class,
        'customers.repeat_rate' => \App\Reckoner\Resolvers\CustomersRepeatRateResolver::class,
        'customers.top_customers' => \App\Reckoner\Resolvers\CustomersTopCustomersResolver::class,
        'customers.avg_spend' => \App\Reckoner\Resolvers\CustomersAvgSpendResolver::class,
        'customers.owing' => \App\Reckoner\Resolvers\CustomersOwingResolver::class,
        'customers.by_area' => \App\Reckoner\Resolvers\CustomersByAreaResolver::class,
        'suppliers.count' => \App\Reckoner\Resolvers\SuppliersCountResolver::class,
        'suppliers.active' => \App\Reckoner\Resolvers\SuppliersActiveResolver::class,
        'suppliers.top_suppliers' => \App\Reckoner\Resolvers\SuppliersTopSuppliersResolver::class,
        'suppliers.spend_total' => \App\Reckoner\Resolvers\SuppliersSpendTotalResolver::class,
        'suppliers.spend_trend' => \App\Reckoner\Resolvers\SuppliersSpendTrendResolver::class,
        'suppliers.owed_list' => \App\Reckoner\Resolvers\SuppliersOwedListResolver::class,
        'suppliers.concentration' => \App\Reckoner\Resolvers\SuppliersConcentrationResolver::class,
        'suppliers.new' => \App\Reckoner\Resolvers\SuppliersNewResolver::class,
        'pos.revenue' => \App\Reckoner\Resolvers\PosRevenueResolver::class,
        'pos.revenue_trend' => \App\Reckoner\Resolvers\PosRevenueTrendResolver::class,
        'pos.sale_count' => \App\Reckoner\Resolvers\PosSaleCountResolver::class,
        'pos.avg_ticket' => \App\Reckoner\Resolvers\PosAvgTicketResolver::class,
        'pos.max_sale' => \App\Reckoner\Resolvers\PosMaxSaleResolver::class,
        'pos.items_per_sale' => \App\Reckoner\Resolvers\PosItemsPerSaleResolver::class,
        'pos.payment_breakdown' => \App\Reckoner\Resolvers\PosPaymentBreakdownResolver::class,
        'pos.hourly_heatmap' => \App\Reckoner\Resolvers\PosHourlyHeatmapResolver::class,
        'pos.weekday_split' => \App\Reckoner\Resolvers\PosWeekdaySplitResolver::class,
        'pos.discount_total' => \App\Reckoner\Resolvers\PosDiscountTotalResolver::class,
        'pos.live_feed' => \App\Reckoner\Resolvers\PosLiveFeedResolver::class,
        'invoicing.count' => \App\Reckoner\Resolvers\InvoicingCountResolver::class,
        'invoicing.value' => \App\Reckoner\Resolvers\InvoicingValueResolver::class,
        'invoicing.value_trend' => \App\Reckoner\Resolvers\InvoicingValueTrendResolver::class,
        'invoicing.unpaid_value' => \App\Reckoner\Resolvers\InvoicingUnpaidValueResolver::class,
        'invoicing.overdue_count' => \App\Reckoner\Resolvers\InvoicingOverdueCountResolver::class,
        'invoicing.overdue_value' => \App\Reckoner\Resolvers\InvoicingOverdueValueResolver::class,
        'invoicing.avg_invoice' => \App\Reckoner\Resolvers\InvoicingAvgInvoiceResolver::class,
        'invoicing.avg_days_to_pay' => \App\Reckoner\Resolvers\InvoicingAvgDaysToPayResolver::class,
        'invoicing.largest_open' => \App\Reckoner\Resolvers\InvoicingLargestOpenResolver::class,
        'invoicing.draft_count' => \App\Reckoner\Resolvers\InvoicingDraftCountResolver::class,
        'quotations.count' => \App\Reckoner\Resolvers\QuotationsCountResolver::class,
        'quotations.open_value' => \App\Reckoner\Resolvers\QuotationsOpenValueResolver::class,
        'quotations.win_rate' => \App\Reckoner\Resolvers\QuotationsWinRateResolver::class,
        'quotations.win_rate_trend' => \App\Reckoner\Resolvers\QuotationsWinRateTrendResolver::class,
        'quotations.avg_quote' => \App\Reckoner\Resolvers\QuotationsAvgQuoteResolver::class,
        'quotations.expiring' => \App\Reckoner\Resolvers\QuotationsExpiringResolver::class,
        'sales_orders.open_count' => \App\Reckoner\Resolvers\SalesOrdersOpenCountResolver::class,
        'sales_orders.open_value' => \App\Reckoner\Resolvers\SalesOrdersOpenValueResolver::class,
        'sales_orders.count' => \App\Reckoner\Resolvers\SalesOrdersCountResolver::class,
        'sales_orders.value_trend' => \App\Reckoner\Resolvers\SalesOrdersValueTrendResolver::class,
        'sales_orders.fulfil_rate' => \App\Reckoner\Resolvers\SalesOrdersFulfilRateResolver::class,
        'sales_orders.overdue' => \App\Reckoner\Resolvers\SalesOrdersOverdueResolver::class,
        'sales_orders.by_customer' => \App\Reckoner\Resolvers\SalesOrdersByCustomerResolver::class,
        'sales_returns.count' => \App\Reckoner\Resolvers\SalesReturnsCountResolver::class,
        'sales_returns.value' => \App\Reckoner\Resolvers\SalesReturnsValueResolver::class,
        'sales_returns.rate' => \App\Reckoner\Resolvers\SalesReturnsRateResolver::class,
        'sales_returns.trend' => \App\Reckoner\Resolvers\SalesReturnsTrendResolver::class,
        'sales_returns.top_returned' => \App\Reckoner\Resolvers\SalesReturnsTopReturnedResolver::class,
        'sales_returns.by_reason' => \App\Reckoner\Resolvers\SalesReturnsByReasonResolver::class,
        'recurring.active_count' => \App\Reckoner\Resolvers\RecurringActiveCountResolver::class,
        'recurring.monthly_value' => \App\Reckoner\Resolvers\RecurringMonthlyValueResolver::class,
        'recurring.trend' => \App\Reckoner\Resolvers\RecurringTrendResolver::class,
        'recurring.due_next_7' => \App\Reckoner\Resolvers\RecurringDueNext7Resolver::class,
        'recurring.share_of_revenue' => \App\Reckoner\Resolvers\RecurringShareOfRevenueResolver::class,
        'recurring.churned' => \App\Reckoner\Resolvers\RecurringChurnedResolver::class,
        'proposals.count' => \App\Reckoner\Resolvers\ProposalsCountResolver::class,
        'proposals.pipeline_value' => \App\Reckoner\Resolvers\ProposalsPipelineValueResolver::class,
        'proposals.win_rate' => \App\Reckoner\Resolvers\ProposalsWinRateResolver::class,
        'proposals.avg_value' => \App\Reckoner\Resolvers\ProposalsAvgValueResolver::class,
        'proposals.stale' => \App\Reckoner\Resolvers\ProposalsStaleResolver::class,
        'proposals.avg_cycle_days' => \App\Reckoner\Resolvers\ProposalsAvgCycleDaysResolver::class,
        'pricing.tier_count' => \App\Reckoner\Resolvers\PricingTierCountResolver::class,
        'pricing.revenue_by_tier' => \App\Reckoner\Resolvers\PricingRevenueByTierResolver::class,
        'pricing.customers_by_tier' => \App\Reckoner\Resolvers\PricingCustomersByTierResolver::class,
        'pricing.avg_realised_price' => \App\Reckoner\Resolvers\PricingAvgRealisedPriceResolver::class,
        'pricing.discount_vs_list' => \App\Reckoner\Resolvers\PricingDiscountVsListResolver::class,
        'park.open_count' => \App\Reckoner\Resolvers\ParkOpenCountResolver::class,
        'park.open_value' => \App\Reckoner\Resolvers\ParkOpenValueResolver::class,
        'park.recalled_count' => \App\Reckoner\Resolvers\ParkRecalledCountResolver::class,
        'park.abandoned_count' => \App\Reckoner\Resolvers\ParkAbandonedCountResolver::class,
        'park.oldest' => \App\Reckoner\Resolvers\ParkOldestResolver::class,
        'tables.occupied' => \App\Reckoner\Resolvers\TablesOccupiedResolver::class,
        'tables.occupancy_rate' => \App\Reckoner\Resolvers\TablesOccupancyRateResolver::class,
        'tables.kitchen_pending' => \App\Reckoner\Resolvers\TablesKitchenPendingResolver::class,
        'tables.avg_turn_minutes' => \App\Reckoner\Resolvers\TablesAvgTurnMinutesResolver::class,
        'tables.covers' => \App\Reckoner\Resolvers\TablesCoversResolver::class,
        'tables.avg_cover_value' => \App\Reckoner\Resolvers\TablesAvgCoverValueResolver::class,
        'tables.revenue_per_table' => \App\Reckoner\Resolvers\TablesRevenuePerTableResolver::class,
        'tables.peak_occupancy' => \App\Reckoner\Resolvers\TablesPeakOccupancyResolver::class,
        'presales.count' => \App\Reckoner\Resolvers\PresalesCountResolver::class,
        'presales.value' => \App\Reckoner\Resolvers\PresalesValueResolver::class,
        'presales.advance_collected' => \App\Reckoner\Resolvers\PresalesAdvanceCollectedResolver::class,
        'presales.pending_delivery' => \App\Reckoner\Resolvers\PresalesPendingDeliveryResolver::class,
        'presales.overdue' => \App\Reckoner\Resolvers\PresalesOverdueResolver::class,
        'inventory.stock_value' => \App\Reckoner\Resolvers\InventoryStockValueResolver::class,
        'inventory.stock_value_trend' => \App\Reckoner\Resolvers\InventoryStockValueTrendResolver::class,
        'inventory.product_count' => \App\Reckoner\Resolvers\InventoryProductCountResolver::class,
        'inventory.units_on_hand' => \App\Reckoner\Resolvers\InventoryUnitsOnHandResolver::class,
        'inventory.low_stock_count' => \App\Reckoner\Resolvers\InventoryLowStockCountResolver::class,
        'inventory.low_stock_list' => \App\Reckoner\Resolvers\InventoryLowStockListResolver::class,
        'inventory.out_of_stock_count' => \App\Reckoner\Resolvers\InventoryOutOfStockCountResolver::class,
        'inventory.dead_stock_value' => \App\Reckoner\Resolvers\InventoryDeadStockValueResolver::class,
        'inventory.turnover_ratio' => \App\Reckoner\Resolvers\InventoryTurnoverRatioResolver::class,
        'inventory.days_of_cover' => \App\Reckoner\Resolvers\InventoryDaysOfCoverResolver::class,
        'inventory.value_by_category' => \App\Reckoner\Resolvers\InventoryValueByCategoryResolver::class,
        'inventory.top_by_value' => \App\Reckoner\Resolvers\InventoryTopByValueResolver::class,
        'locations.count' => \App\Reckoner\Resolvers\LocationsCountResolver::class,
        'locations.revenue_by_location' => \App\Reckoner\Resolvers\LocationsRevenueByLocationResolver::class,
        'locations.profit_by_location' => \App\Reckoner\Resolvers\LocationsProfitByLocationResolver::class,
        'locations.stock_by_location' => \App\Reckoner\Resolvers\LocationsStockByLocationResolver::class,
        'locations.revenue_trend_by_location' => \App\Reckoner\Resolvers\LocationsRevenueTrendByLocationResolver::class,
        'locations.stock_imbalance' => \App\Reckoner\Resolvers\LocationsStockImbalanceResolver::class,
        'transfers.pending_count' => \App\Reckoner\Resolvers\TransfersPendingCountResolver::class,
        'transfers.pending_value' => \App\Reckoner\Resolvers\TransfersPendingValueResolver::class,
        'transfers.count' => \App\Reckoner\Resolvers\TransfersCountResolver::class,
        'transfers.avg_transit_days' => \App\Reckoner\Resolvers\TransfersAvgTransitDaysResolver::class,
        'transfers.discrepancy_count' => \App\Reckoner\Resolvers\TransfersDiscrepancyCountResolver::class,
        'stocktakes.pending_count' => \App\Reckoner\Resolvers\StocktakesPendingCountResolver::class,
        'stocktakes.variance_value' => \App\Reckoner\Resolvers\StocktakesVarianceValueResolver::class,
        'stocktakes.variance_pct' => \App\Reckoner\Resolvers\StocktakesVariancePctResolver::class,
        'stocktakes.last_count_days' => \App\Reckoner\Resolvers\StocktakesLastCountDaysResolver::class,
        'stocktakes.top_variances' => \App\Reckoner\Resolvers\StocktakesTopVariancesResolver::class,
        'batches.count' => \App\Reckoner\Resolvers\BatchesCountResolver::class,
        'batches.qty' => \App\Reckoner\Resolvers\BatchesQtyResolver::class,
        'batches.expiring_30' => \App\Reckoner\Resolvers\BatchesExpiring30Resolver::class,
        'batches.expiring_value' => \App\Reckoner\Resolvers\BatchesExpiringValueResolver::class,
        'batches.expired_value' => \App\Reckoner\Resolvers\BatchesExpiredValueResolver::class,
        'batches.expiry_list' => \App\Reckoner\Resolvers\BatchesExpiryListResolver::class,
        'batches.write_off_trend' => \App\Reckoner\Resolvers\BatchesWriteOffTrendResolver::class,
        'serials.count' => \App\Reckoner\Resolvers\SerialsCountResolver::class,
        'serials.in_stock' => \App\Reckoner\Resolvers\SerialsInStockResolver::class,
        'serials.under_warranty' => \App\Reckoner\Resolvers\SerialsUnderWarrantyResolver::class,
        'serials.warranty_expiring' => \App\Reckoner\Resolvers\SerialsWarrantyExpiringResolver::class,
        'serials.returned' => \App\Reckoner\Resolvers\SerialsReturnedResolver::class,
        'variants.count' => \App\Reckoner\Resolvers\VariantsCountResolver::class,
        'variants.top_variants' => \App\Reckoner\Resolvers\VariantsTopVariantsResolver::class,
        'variants.slow_variants' => \App\Reckoner\Resolvers\VariantsSlowVariantsResolver::class,
        'variants.out_of_stock' => \App\Reckoner\Resolvers\VariantsOutOfStockResolver::class,
        'variants.size_colour_mix' => \App\Reckoner\Resolvers\VariantsSizeColourMixResolver::class,
        'barcodes.coverage_pct' => \App\Reckoner\Resolvers\BarcodesCoveragePctResolver::class,
        'barcodes.missing_count' => \App\Reckoner\Resolvers\BarcodesMissingCountResolver::class,
        'barcodes.labels_printed' => \App\Reckoner\Resolvers\BarcodesLabelsPrintedResolver::class,
        'barcodes.scan_share' => \App\Reckoner\Resolvers\BarcodesScanShareResolver::class,
        'barcodes.duplicate_count' => \App\Reckoner\Resolvers\BarcodesDuplicateCountResolver::class,
        'uom.count' => \App\Reckoner\Resolvers\UomCountResolver::class,
        'uom.conversion_count' => \App\Reckoner\Resolvers\UomConversionCountResolver::class,
        'uom.sales_by_uom' => \App\Reckoner\Resolvers\UomSalesByUomResolver::class,
        'uom.missing_conversion' => \App\Reckoner\Resolvers\UomMissingConversionResolver::class,
        'uom.bulk_vs_retail' => \App\Reckoner\Resolvers\UomBulkVsRetailResolver::class,
        'purchases.spend' => \App\Reckoner\Resolvers\PurchasesSpendResolver::class,
        'purchases.spend_trend' => \App\Reckoner\Resolvers\PurchasesSpendTrendResolver::class,
        'purchases.count' => \App\Reckoner\Resolvers\PurchasesCountResolver::class,
        'purchases.unpaid_value' => \App\Reckoner\Resolvers\PurchasesUnpaidValueResolver::class,
        'purchases.overdue_value' => \App\Reckoner\Resolvers\PurchasesOverdueValueResolver::class,
        'purchases.paid_to_suppliers' => \App\Reckoner\Resolvers\PurchasesPaidToSuppliersResolver::class,
        'purchases.by_supplier' => \App\Reckoner\Resolvers\PurchasesBySupplierResolver::class,
        'purchases.by_category' => \App\Reckoner\Resolvers\PurchasesByCategoryResolver::class,
        'purchases.price_increases' => \App\Reckoner\Resolvers\PurchasesPriceIncreasesResolver::class,
        'po.open_count' => \App\Reckoner\Resolvers\PoOpenCountResolver::class,
        'po.open_value' => \App\Reckoner\Resolvers\PoOpenValueResolver::class,
        'po.pending_receipt_value' => \App\Reckoner\Resolvers\PoPendingReceiptValueResolver::class,
        'po.overdue_count' => \App\Reckoner\Resolvers\PoOverdueCountResolver::class,
        'po.avg_lead_days' => \App\Reckoner\Resolvers\PoAvgLeadDaysResolver::class,
        'po.fill_rate' => \App\Reckoner\Resolvers\PoFillRateResolver::class,
        'purchase_returns.count' => \App\Reckoner\Resolvers\PurchaseReturnsCountResolver::class,
        'purchase_returns.value' => \App\Reckoner\Resolvers\PurchaseReturnsValueResolver::class,
        'purchase_returns.credit_due' => \App\Reckoner\Resolvers\PurchaseReturnsCreditDueResolver::class,
        'purchase_returns.by_supplier' => \App\Reckoner\Resolvers\PurchaseReturnsBySupplierResolver::class,
        'purchase_returns.rate' => \App\Reckoner\Resolvers\PurchaseReturnsRateResolver::class,
        'landed.total' => \App\Reckoner\Resolvers\LandedTotalResolver::class,
        'landed.pct_of_goods' => \App\Reckoner\Resolvers\LandedPctOfGoodsResolver::class,
        'landed.by_type' => \App\Reckoner\Resolvers\LandedByTypeResolver::class,
        'landed.true_cost_gap' => \App\Reckoner\Resolvers\LandedTrueCostGapResolver::class,
        'landed.trend' => \App\Reckoner\Resolvers\LandedTrendResolver::class,
        'cookbook.recipe_count' => \App\Reckoner\Resolvers\CookbookRecipeCountResolver::class,
        'cookbook.recipe_cost_pct' => \App\Reckoner\Resolvers\CookbookRecipeCostPctResolver::class,
        'cookbook.best_margin' => \App\Reckoner\Resolvers\CookbookBestMarginResolver::class,
        'cookbook.worst_margin' => \App\Reckoner\Resolvers\CookbookWorstMarginResolver::class,
        'cookbook.ingredient_cost_trend' => \App\Reckoner\Resolvers\CookbookIngredientCostTrendResolver::class,
        'cookbook.wastage_value' => \App\Reckoner\Resolvers\CookbookWastageValueResolver::class,
        'production.run_count' => \App\Reckoner\Resolvers\ProductionRunCountResolver::class,
        'production.total_cost' => \App\Reckoner\Resolvers\ProductionTotalCostResolver::class,
        'production.output_qty' => \App\Reckoner\Resolvers\ProductionOutputQtyResolver::class,
        'production.cost_per_unit' => \App\Reckoner\Resolvers\ProductionCostPerUnitResolver::class,
        'production.yield_pct' => \App\Reckoner\Resolvers\ProductionYieldPctResolver::class,
        'production.wastage_value' => \App\Reckoner\Resolvers\ProductionWastageValueResolver::class,
        'production.in_progress' => \App\Reckoner\Resolvers\ProductionInProgressResolver::class,
        'production.output_trend' => \App\Reckoner\Resolvers\ProductionOutputTrendResolver::class,
        'composite.count' => \App\Reckoner\Resolvers\CompositeCountResolver::class,
        'composite.revenue' => \App\Reckoner\Resolvers\CompositeRevenueResolver::class,
        'composite.margin' => \App\Reckoner\Resolvers\CompositeMarginResolver::class,
        'composite.top_bundles' => \App\Reckoner\Resolvers\CompositeTopBundlesResolver::class,
        'composite.component_shortage' => \App\Reckoner\Resolvers\CompositeComponentShortageResolver::class,
        'khata.receivable_total' => \App\Reckoner\Resolvers\KhataReceivableTotalResolver::class,
        'khata.payable_total' => \App\Reckoner\Resolvers\KhataPayableTotalResolver::class,
        'khata.net_position' => \App\Reckoner\Resolvers\KhataNetPositionResolver::class,
        'khata.biggest_debtors' => \App\Reckoner\Resolvers\KhataBiggestDebtorsResolver::class,
        'khata.overdue_total' => \App\Reckoner\Resolvers\KhataOverdueTotalResolver::class,
        'khata.aging' => \App\Reckoner\Resolvers\KhataAgingResolver::class,
        'khata.collected' => \App\Reckoner\Resolvers\KhataCollectedResolver::class,
        'khata.collection_trend' => \App\Reckoner\Resolvers\KhataCollectionTrendResolver::class,
        'khata.over_limit' => \App\Reckoner\Resolvers\KhataOverLimitResolver::class,
        'payments.received' => \App\Reckoner\Resolvers\PaymentsReceivedResolver::class,
        'payments.received_trend' => \App\Reckoner\Resolvers\PaymentsReceivedTrendResolver::class,
        'payments.paid' => \App\Reckoner\Resolvers\PaymentsPaidResolver::class,
        'payments.net_flow' => \App\Reckoner\Resolvers\PaymentsNetFlowResolver::class,
        'payments.by_method' => \App\Reckoner\Resolvers\PaymentsByMethodResolver::class,
        'payments.cash_vs_digital' => \App\Reckoner\Resolvers\PaymentsCashVsDigitalResolver::class,
        'payments.unallocated' => \App\Reckoner\Resolvers\PaymentsUnallocatedResolver::class,
        'payments.bounced' => \App\Reckoner\Resolvers\PaymentsBouncedResolver::class,
        'expenses.count' => \App\Reckoner\Resolvers\ExpensesCountResolver::class,
        'expenses.trend' => \App\Reckoner\Resolvers\ExpensesTrendResolver::class,
        'expenses.by_category' => \App\Reckoner\Resolvers\ExpensesByCategoryResolver::class,
        'expenses.top_categories' => \App\Reckoner\Resolvers\ExpensesTopCategoriesResolver::class,
        'expenses.unpaid' => \App\Reckoner\Resolvers\ExpensesUnpaidResolver::class,
        'expenses.largest' => \App\Reckoner\Resolvers\ExpensesLargestResolver::class,
        'expenses.recurring_total' => \App\Reckoner\Resolvers\ExpensesRecurringTotalResolver::class,
        'expenses.per_day' => \App\Reckoner\Resolvers\ExpensesPerDayResolver::class,
        'expenses.vs_prev' => \App\Reckoner\Resolvers\ExpensesVsPrevResolver::class,
        'register.open_count' => \App\Reckoner\Resolvers\RegisterOpenCountResolver::class,
        'register.cash_in_drawer' => \App\Reckoner\Resolvers\RegisterCashInDrawerResolver::class,
        'register.cash_sales' => \App\Reckoner\Resolvers\RegisterCashSalesResolver::class,
        'register.expected_vs_actual' => \App\Reckoner\Resolvers\RegisterExpectedVsActualResolver::class,
        'register.variance_total' => \App\Reckoner\Resolvers\RegisterVarianceTotalResolver::class,
        'register.by_staff' => \App\Reckoner\Resolvers\RegisterByStaffResolver::class,
        'register.shift_count' => \App\Reckoner\Resolvers\RegisterShiftCountResolver::class,
        'bank.account_count' => \App\Reckoner\Resolvers\BankAccountCountResolver::class,
        'bank.balances_total' => \App\Reckoner\Resolvers\BankBalancesTotalResolver::class,
        'bank.balance_trend' => \App\Reckoner\Resolvers\BankBalanceTrendResolver::class,
        'bank.balance_by_account' => \App\Reckoner\Resolvers\BankBalanceByAccountResolver::class,
        'bank.top_account' => \App\Reckoner\Resolvers\BankTopAccountResolver::class,
        'bank.money_in' => \App\Reckoner\Resolvers\BankMoneyInResolver::class,
        'bank.money_out' => \App\Reckoner\Resolvers\BankMoneyOutResolver::class,
        'bank.cash_vs_bank' => \App\Reckoner\Resolvers\BankCashVsBankResolver::class,
        'bank.idle_accounts' => \App\Reckoner\Resolvers\BankIdleAccountsResolver::class,
        'recon.unreconciled_count' => \App\Reckoner\Resolvers\ReconUnreconciledCountResolver::class,
        'recon.unreconciled_value' => \App\Reckoner\Resolvers\ReconUnreconciledValueResolver::class,
        'recon.matched_pct' => \App\Reckoner\Resolvers\ReconMatchedPctResolver::class,
        'recon.last_recon_days' => \App\Reckoner\Resolvers\ReconLastReconDaysResolver::class,
        'recon.difference' => \App\Reckoner\Resolvers\ReconDifferenceResolver::class,
        'accounting.trial_balance_ok' => \App\Reckoner\Resolvers\AccountingTrialBalanceOkResolver::class,
        'accounting.assets_total' => \App\Reckoner\Resolvers\AccountingAssetsTotalResolver::class,
        'accounting.liabilities_total' => \App\Reckoner\Resolvers\AccountingLiabilitiesTotalResolver::class,
        'accounting.equity_total' => \App\Reckoner\Resolvers\AccountingEquityTotalResolver::class,
        'accounting.equity_trend' => \App\Reckoner\Resolvers\AccountingEquityTrendResolver::class,
        'accounting.pnl_summary' => \App\Reckoner\Resolvers\AccountingPnlSummaryResolver::class,
        'accounting.balance_sheet' => \App\Reckoner\Resolvers\AccountingBalanceSheetResolver::class,
        'accounting.unposted_count' => \App\Reckoner\Resolvers\AccountingUnpostedCountResolver::class,
        'accounting.drawings' => \App\Reckoner\Resolvers\AccountingDrawingsResolver::class,
        'tax.collected' => \App\Reckoner\Resolvers\TaxCollectedResolver::class,
        'tax.paid' => \App\Reckoner\Resolvers\TaxPaidResolver::class,
        'tax.net_liability' => \App\Reckoner\Resolvers\TaxNetLiabilityResolver::class,
        'tax.liability_trend' => \App\Reckoner\Resolvers\TaxLiabilityTrendResolver::class,
        'tax.by_rate' => \App\Reckoner\Resolvers\TaxByRateResolver::class,
        'tax.taxable_vs_exempt' => \App\Reckoner\Resolvers\TaxTaxableVsExemptResolver::class,
        'tax.filing_due' => \App\Reckoner\Resolvers\TaxFilingDueResolver::class,
        'tax.invoices_missing_tax' => \App\Reckoner\Resolvers\TaxInvoicesMissingTaxResolver::class,
        'assets.count' => \App\Reckoner\Resolvers\AssetsCountResolver::class,
        'assets.gross_value' => \App\Reckoner\Resolvers\AssetsGrossValueResolver::class,
        'assets.net_book_value' => \App\Reckoner\Resolvers\AssetsNetBookValueResolver::class,
        'assets.depreciation_period' => \App\Reckoner\Resolvers\AssetsDepreciationPeriodResolver::class,
        'assets.by_category' => \App\Reckoner\Resolvers\AssetsByCategoryResolver::class,
        'assets.warranty_amc_due' => \App\Reckoner\Resolvers\AssetsWarrantyAmcDueResolver::class,
        'loans.count' => \App\Reckoner\Resolvers\LoansCountResolver::class,
        'loans.outstanding_total' => \App\Reckoner\Resolvers\LoansOutstandingTotalResolver::class,
        'loans.outstanding_trend' => \App\Reckoner\Resolvers\LoansOutstandingTrendResolver::class,
        'loans.emi_due' => \App\Reckoner\Resolvers\LoansEmiDueResolver::class,
        'loans.interest_paid' => \App\Reckoner\Resolvers\LoansInterestPaidResolver::class,
        'loans.by_lender' => \App\Reckoner\Resolvers\LoansByLenderResolver::class,
        'reports.pnl_shortcut' => \App\Reckoner\Resolvers\ReportsPnlShortcutResolver::class,
        'reports.sales_shortcut' => \App\Reckoner\Resolvers\ReportsSalesShortcutResolver::class,
        'reports.stock_shortcut' => \App\Reckoner\Resolvers\ReportsStockShortcutResolver::class,
        'reports.saved_count' => \App\Reckoner\Resolvers\ReportsSavedCountResolver::class,
        'reports.most_used' => \App\Reckoner\Resolvers\ReportsMostUsedResolver::class,
        'reports.scheduled_count' => \App\Reckoner\Resolvers\ReportsScheduledCountResolver::class,
        'ai.top_insight' => \App\Reckoner\Resolvers\AiTopInsightResolver::class,
        'ai.alerts_open' => \App\Reckoner\Resolvers\AiAlertsOpenResolver::class,
        'ai.anomalies' => \App\Reckoner\Resolvers\AiAnomaliesResolver::class,
        'ai.forecast_revenue' => \App\Reckoner\Resolvers\AiForecastRevenueResolver::class,
        'ai.forecast_cash' => \App\Reckoner\Resolvers\AiForecastCashResolver::class,
        'ai.reorder_suggestions' => \App\Reckoner\Resolvers\AiReorderSuggestionsResolver::class,
        'loyalty.member_count' => \App\Reckoner\Resolvers\LoyaltyMemberCountResolver::class,
        'loyalty.new_members' => \App\Reckoner\Resolvers\LoyaltyNewMembersResolver::class,
        'loyalty.member_revenue_share' => \App\Reckoner\Resolvers\LoyaltyMemberRevenueShareResolver::class,
        'loyalty.member_avg_spend' => \App\Reckoner\Resolvers\LoyaltyMemberAvgSpendResolver::class,
        'loyalty.liability' => \App\Reckoner\Resolvers\LoyaltyLiabilityResolver::class,
        'loyalty.gift_card_balance' => \App\Reckoner\Resolvers\LoyaltyGiftCardBalanceResolver::class,
        'marketplace.channel_count' => \App\Reckoner\Resolvers\MarketplaceChannelCountResolver::class,
        'marketplace.revenue_by_channel' => \App\Reckoner\Resolvers\MarketplaceRevenueByChannelResolver::class,
        'marketplace.online_vs_offline' => \App\Reckoner\Resolvers\MarketplaceOnlineVsOfflineResolver::class,
        'marketplace.sync_errors' => \App\Reckoner\Resolvers\MarketplaceSyncErrorsResolver::class,
        'marketplace.stock_mismatch' => \App\Reckoner\Resolvers\MarketplaceStockMismatchResolver::class,
        'marketplace.channel_margin' => \App\Reckoner\Resolvers\MarketplaceChannelMarginResolver::class,
        'staff.member_count' => \App\Reckoner\Resolvers\StaffMemberCountResolver::class,
        'staff.on_shift_count' => \App\Reckoner\Resolvers\StaffOnShiftCountResolver::class,
        'staff.present_today' => \App\Reckoner\Resolvers\StaffPresentTodayResolver::class,
        'staff.absent_today' => \App\Reckoner\Resolvers\StaffAbsentTodayResolver::class,
        'staff.hours_worked' => \App\Reckoner\Resolvers\StaffHoursWorkedResolver::class,
        'staff.attendance_rate' => \App\Reckoner\Resolvers\StaffAttendanceRateResolver::class,
        'staff.sales_by_staff' => \App\Reckoner\Resolvers\StaffSalesByStaffResolver::class,
        'staff.revenue_per_staff' => \App\Reckoner\Resolvers\StaffRevenuePerStaffResolver::class,
    ];

    /**
     * @return array<string, class-string<CardResolverInterface>>
     */
    public static function all(): array
    {
        return self::MAP;
    }

    public static function count(): int
    {
        return count(self::MAP);
    }

    public static function has(string $key): bool
    {
        return isset(self::MAP[$key]);
    }

    public static function classForKey(string $key): ?string
    {
        return self::MAP[$key] ?? null;
    }

    public static function get(string $key): ?CardResolverInterface
    {
        $class = self::classForKey($key);
        return $class && class_exists($class) ? new $class() : null;
    }

    public static function resolve(string $key, ReckonerContext $ctx, ReckonerPeriod $period, array $args = []): ReckonerResult
    {
        $resolver = self::get($key);
        if (!$resolver) {
            return ReckonerResult::failure($key, $key, 'not_found', "No resolver exists for '{$key}'.");
        }

        return $resolver->resolve($ctx, $period, $args);
    }
}
