<?php

namespace App\Reckoner;

use App\Reckoner\Sources\FinanceSource;
use App\Reckoner\Sources\InventorySource;
use App\Reckoner\Sources\OperationsSource;
use App\Reckoner\Sources\PartySource;
use App\Reckoner\Sources\PlatformSource;
use App\Reckoner\Sources\ProductionSource;
use App\Reckoner\Sources\PurchasingSource;
use App\Reckoner\Sources\RestaurantSource;
use App\Reckoner\Sources\SalesSource;
use App\Reckoner\Sources\StaffSource;
use App\Reckoner\Sources\TaxSource;

/**
 * The catalogue of every reading that exists. WHAT readings exist — no
 * queries, ever (§2).
 *
 * Phase 1 populated the ~11 keys mirroring WidgetRegistry's financial cards.
 * Phase 2 adds every metric the nine newly-built sources support — inventory
 * counts, party/purchasing/production/staff/operations/tax figures, and the
 * platform-scoped MRR/tenant-count pair. This is short of the spec's ~250-key
 * full catalogue (that volume assumes ~60 ReportController methods fully
 * read and ported one-by-one, which this session's budget did not allow),
 * but every metric that exists here is wired to a real, schema-verified
 * source — nothing is a stub returning an invented number, with the one
 * explicitly flagged exception documented on PlatformSource::mrr().
 *
 * Key immutability: the `key` is a permanent public identifier. Never rename
 * one — add `'deprecated' => 'replacement.key'` instead.
 */
final class ReckonerRegistry
{
    private static ?array $cache = null;

    /**
     * Module ownership — the seventh gate's map.
     *
     * A reading listed here belongs to a tenant module (config/modules.php).
     * When every module in its list is switched off for the tenant, the
     * reading gates as unavailable — the dashboard mirror of the rule that a
     * disabled module also loses its nav item (ModuleNavBuilder). A reading
     * NOT listed here is core and never module-gated; an array means
     * "visible while ANY of these modules is on" (fail-open by design,
     * matching ModuleService::enabled()'s unknown-key behaviour).
     *
     * Mapping follows config/modules.php's own `cards` declarations
     * (e.g. khata_credit → receivables, purchases → payables) — the module
     * file is the source of the taxonomy; this map only translates its
     * legacy widget ids onto Reckoner keys.
     */
    private const MODULE_MAP = [
        // Inventory
        'inventory.stock_value' => 'inventory',
        'inventory.low_stock_count' => 'inventory',
        'inventory.low_stock_list' => 'inventory',
        'inventory.out_of_stock_count' => 'inventory',
        'inventory.overstock_count' => 'inventory',
        'inventory.product_count' => 'products',
        // Purchasing
        'purchasing.spend' => 'purchases',
        'purchasing.count' => 'purchases',
        'finance.paid_to_suppliers' => 'purchases',
        'finance.payables' => 'purchases',
        // Receivables / khata
        'finance.receivables' => 'khata_credit',
        'finance.receivables_aging' => 'khata_credit',
        // Liquidity — visible while any money-holding module is on
        'finance.total_liquidity' => ['payments', 'cash_register', 'bank_accounts'],
        // Expenses
        'finance.expenses_total' => 'expenses',
        'finance.expenses_by_category' => 'expenses',
        // Parties
        'party.customer_count' => 'customers',
        'party.new_customers' => 'customers',
        'party.dormant_customers' => 'customers',
        'party.supplier_count' => 'suppliers',
        // Orders / operations
        'operations.open_sales_orders' => 'sales_orders',
        'operations.pending_stock_takes' => 'stock_takes',
        'operations.pending_stock_transfers' => 'stock_transfers',
        // Production
        'production.total_cost' => 'production_runs',
        'production.run_count' => 'production_runs',
        // Staff
        'staff.on_shift_count' => 'staff_attendance',
        'staff.member_count' => 'staff_attendance',
        // Restaurant
        'restaurant.tables_occupied' => 'table_service',
        'restaurant.kitchen_orders_pending' => 'table_service',
        // Tax
        'tax.collected' => 'tax_compliance',
    ];

    /**
     * Readings tagged "New" in the add-card library.
     *
     * These are the analytic readings added on top of the original KPI set
     * (the card builder prototype called them "extra"; the product word is
     * "New" — an invitation, not an apology). Purely presentational: the
     * catalogue exposes it as `is_new` and the library renders the badge.
     */
    private const NEW_KEYS = [
        'sales.revenue_trend',
        'sales.payment_breakdown',
        'sales.top_products',
        'sales.top_customers',
        'sales.hourly_heatmap',
        'sales.live_feed',
        'sales.gross_margin_pct',
        'finance.profit_trend',
        'finance.cash_flow_trend',
        'finance.expenses_by_category',
        'finance.receivables_aging',
        'finance.balance_sheet_ok',
        'finance.net_margin_pct',
        'inventory.low_stock_list',
        'inventory.overstock_count',
        'party.new_customers',
        'party.dormant_customers',
        'plan.usage_summary',
    ];

    public static function all(): array
    {
        if (self::$cache !== null) {
            return self::$cache;
        }

        $all = [

            /* ── Sales ────────────────────────────────────────────────── */
            'sales.revenue' => [
                'key' => 'sales.revenue',
                'domain' => 'sales',
                'label' => 'Revenue',
                'generic' => 'Revenue',
                'description' => 'Money earned from posted sales, net of returns and excluding tax.',
                'help' => 'Read from the accounting ledger, so a sale reversed by a journal entry '
                    .'is removed here too. Yearly periods run on the calendar year, '
                    .'1 January to 31 December.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'higher_is_better',
                'signed' => false,
                'periods' => ReckonerPeriod::KEYS,
                'default_period' => 'today',
                'supports_comparison' => true,
                'supports_series' => true,
                'series_granularity' => ['hourly', 'daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
                'permissions' => ['sales.view', 'reports.summary', 'reports.financial'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => SalesSource::class,
                'method' => 'revenue',
                'cache_ttl' => 60,
                'drill_route' => 'reports.sales',
                'dimensions' => [
                    'group_by' => ['enum' => ['none','customer','product','category','channel','payment_method'], 'default' => 'none'],
                    'metric'   => ['enum' => ['value','qty','count'], 'default' => 'value'],
                    'limit'    => ['int'  => [1, 50], 'default' => 10],
                ],
                'filters' => [
                    'product'  => ['type' => 'entity', 'model' => 'App\\Models\\Product'],
                    'customer' => ['type' => 'entity', 'model' => 'App\\Models\\Party'],
                    'category' => ['type' => 'entity', 'model' => 'App\\Models\\Category'],
                ],
                'additive' => true,
            ],

            'sales.max_sale' => [
                'key' => 'sales.max_sale',
                'domain' => 'sales',
                'label' => 'Largest Sale (excl. tax)',
                'generic' => 'Largest Sale',
                'description' => 'The largest individual sale amount, excluding tax, within the period.',
                'help' => 'Calculated by querying the max of net_sales across all posted sales in the period.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'higher_is_better',
                'signed' => false,
                'periods' => ReckonerPeriod::KEYS,
                'default_period' => 'this_month',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['sales.view'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => SalesSource::class,
                'method' => 'maxSale',
                'cache_ttl' => 60,
                'drill_route' => 'sales.index',
                'implemented' => true,
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'sales.gross_margin_pct' => [
                'key' => 'sales.gross_margin_pct',
                'domain' => 'sales',
                'label' => 'Gross Margin',
                'generic' => 'Gross Margin',
                'description' => 'Gross profit as a percentage of revenue.',
                'help' => 'Gross profit ÷ revenue. "Margin" always names which margin — this is the '
                    .'gross figure, before operating expenses. Yearly periods run on the calendar year.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'percent',
                'precision' => 2,
                'direction' => 'higher_is_better',
                'signed' => false,  // Percentage — no accounting-term alternate label (not "Gross Loss Margin").
                'periods' => ReckonerPeriod::KEYS,
                'default_period' => 'this_month',
                'supports_comparison' => true,
                'supports_series' => true,
                'series_granularity' => ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
                'permissions' => ['reports.financial', 'sales.view'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'grossMarginPct',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            /* ── Finance ──────────────────────────────────────────────── */
            'finance.net_profit' => [
                'key' => 'finance.net_profit',
                'domain' => 'finance',
                'label' => 'Net Profit',
                'generic' => 'Net Profit',
                'description' => 'Profit for the period from the ledger, after operating expenses.',
                'help' => 'Gross profit minus operating expenses. Read from the P&L. Renders as '
                    .'"Net Loss" when negative. Yearly periods run on the calendar year.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'higher_is_better',
                'signed' => true,
                'periods' => ReckonerPeriod::KEYS,
                'default_period' => 'this_month',
                'supports_comparison' => true,
                'supports_series' => true,
                'series_granularity' => ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
                'permissions' => ['finance.balances', 'reports.financial'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'netProfit',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => true,
            ],

            'finance.gross_profit' => [
                'key' => 'finance.gross_profit',
                'domain' => 'finance',
                'label' => 'Gross Profit',
                'generic' => 'Gross Profit',
                'description' => 'Revenue minus cost of goods sold, for the period.',
                'help' => 'Revenue minus COGS from the P&L. Renders as "Gross Loss" when negative — '
                    .'the standard accounting term for a negative trading result. Yearly periods '
                    .'run on the calendar year.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'higher_is_better',
                'signed' => true,
                'periods' => ReckonerPeriod::KEYS,
                'default_period' => 'this_month',
                'supports_comparison' => true,
                'supports_series' => true,
                'series_granularity' => ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
                'permissions' => ['finance.balances', 'reports.financial'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'grossProfit',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => true,
            ],

            'finance.cogs' => [
                'key' => 'finance.cogs',
                'domain' => 'finance',
                'label' => 'Cost of Goods Sold',
                'generic' => 'Cost of Goods Sold',
                'description' => 'The cost of the goods behind this period\'s sales.',
                'help' => 'Read from GL account 5000. Yearly periods run on the calendar year.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'lower_is_better',
                'signed' => false,
                'periods' => ReckonerPeriod::KEYS,
                'default_period' => 'this_month',
                'supports_comparison' => true,
                'supports_series' => true,
                'series_granularity' => ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
                'permissions' => ['finance.balances', 'reports.financial'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'cogs',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => true,
            ],

            'finance.net_margin_pct' => [
                'key' => 'finance.net_margin_pct',
                'domain' => 'finance',
                'label' => 'Net Margin',
                'generic' => 'Net Margin',
                'description' => 'Net profit as a percentage of revenue.',
                'help' => 'Net profit ÷ revenue. "Margin" always names which margin — this is the '
                    .'net figure, after operating expenses. Yearly periods run on the calendar year.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'percent',
                'precision' => 2,
                'direction' => 'higher_is_better',
                'signed' => false,  // Percentage — no accounting-term alternate label.
                'periods' => ReckonerPeriod::KEYS,
                'default_period' => 'this_month',
                'supports_comparison' => true,
                'supports_series' => true,
                'series_granularity' => ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
                'permissions' => ['finance.balances', 'reports.financial'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'netMarginPct',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'finance.expenses_total' => [
                'key' => 'finance.expenses_total',
                'domain' => 'finance',
                'label' => 'Expenses',
                'generic' => 'Expenses',
                'description' => 'Operating expenses recorded for the period, excluding cost of goods sold.',
                'help' => 'Total expenses from the P&L minus COGS — operating expenses only. A busy '
                    .'month with high COGS is not overspending. Yearly periods run on the calendar year.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'lower_is_better',
                'signed' => false,
                'periods' => ReckonerPeriod::KEYS,
                'default_period' => 'this_month',
                'supports_comparison' => true,
                'supports_series' => true,
                'series_granularity' => ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
                'permissions' => ['finance.transactions', 'reports.financial'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'expensesTotal',
                'cache_ttl' => 60,
                'drill_route' => 'expenses.index',
                'dimensions' => [
                    'group_by' => ['enum' => ['none','category'], 'default' => 'none'],
                ],
                'filters' => [
                    'category' => ['type' => 'string'],
                ],
                'additive'   => true,
            ],

            'finance.receivables' => [
                'key' => 'finance.receivables',
                'domain' => 'finance',
                'label' => 'Receivables',
                'generic' => 'Receivables',
                'description' => 'What customers currently owe you.',
                'help' => 'Net movement on the AR control account (GL 1200), non-reversed entries '
                    .'only. This is a point-in-time balance, not a period figure.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'neutral',
                'signed' => false,
                'periods' => ['as_of', 'live'],
                'default_period' => 'live',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['finance.balances', 'reports.financial'],
                'feature' => null,
                'capability' => 'has_parties',
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'receivables',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'finance.payables' => [
                'key' => 'finance.payables',
                'domain' => 'finance',
                'label' => 'Payables',
                'generic' => 'Payables',
                'description' => 'What you currently owe suppliers.',
                'help' => 'Net movement on the AP control account (GL 2000), non-reversed entries '
                    .'only. This is a point-in-time balance, not a period figure.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'neutral',
                'signed' => false,
                'periods' => ['as_of', 'live'],
                'default_period' => 'live',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['finance.balances', 'reports.financial'],
                'feature' => null,
                'capability' => 'has_parties',
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'payables',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'finance.total_liquidity' => [
                'key' => 'finance.total_liquidity',
                'domain' => 'finance',
                'label' => 'Total Liquidity',
                'generic' => 'Total Liquidity',
                'description' => 'Total cash and bank account balance.',
                'help' => 'SUM of debit - credit on accounts in the 1000-1099 range.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'higher_is_better',
                'signed' => true,
                'periods' => ['as_of', 'live'],
                'default_period' => 'live',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['finance.balances'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'totalLiquidity',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'finance.balance_sheet_ok' => [
                'key' => 'finance.balance_sheet_ok',
                'domain' => 'finance',
                'label' => 'Books Balanced',
                'generic' => 'Books Balanced',
                'description' => 'Whether the ledger is in balance.',
                'help' => '§7.19: a status, not a KPI to trend. Debits must equal credits across '
                    .'every non-reversed journal entry — a discrepancy here is a bug, not a fact '
                    .'about the business, and is reported once rather than watched drift over time.',
                'shape' => ReckonerShape::STATUS,
                'unit' => 'text',
                'precision' => 0,
                'direction' => 'neutral',
                'signed' => false,
                'periods' => ['live'],
                'default_period' => 'live',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['finance.balances', 'reports.financial'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'balanceSheetStatus',
                'cache_ttl' => 60,
                'drill_route' => 'accounting.trial-balance',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            /* ── Inventory ────────────────────────────────────────────── */
            'inventory.stock_value' => [
                'key' => 'inventory.stock_value',
                'domain' => 'inventory',
                'label' => 'Stock Value',
                'generic' => 'Stock Value',
                'description' => 'Current valuation of stock on hand.',
                'help' => 'FIFO: SUM(remaining batch quantity × unit cost) across open inventory '
                    .'batches. This is a point-in-time balance, not a period figure.',
                'shape' => ReckonerShape::SCALAR,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'neutral',
                'signed' => false,
                'periods' => ['as_of', 'live'],
                'default_period' => 'live',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['inventory.view', 'reports.stock'],
                'feature' => 'stock_valuation',
                'capability' => 'has_inventory',
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'stockValue',
                'cache_ttl' => 60,
                'drill_route' => 'inventory.index',
            ],

            'inventory.low_stock_count' => self::scalar(
                key: 'inventory.low_stock_count',
                domain: 'inventory',
                label: 'Low Stock',
                description: 'Products at or below their alert quantity, but not yet out of stock.',
                help: '§7.13: excludes out-of-stock products — see inventory.out_of_stock_count for '
                    .'those. low_stock_count + out_of_stock_count equals the old combined count.',
                unit: 'integer',
                direction: 'lower_is_better',
                permissions: ['inventory.view'],
                capability: 'has_inventory',
                source: InventorySource::class,
                method: 'lowStockCount',
                drillRoute: 'reports.low-stock',
            ),

            'inventory.out_of_stock_count' => self::scalar(
                key: 'inventory.out_of_stock_count',
                domain: 'inventory',
                label: 'Out of Stock',
                description: 'Products with zero or negative quantity on hand.',
                help: '§7.13: its own metric, not folded into Low Stock.',
                unit: 'integer',
                direction: 'lower_is_better',
                permissions: ['inventory.view'],
                capability: 'has_inventory',
                source: InventorySource::class,
                method: 'outOfStockCount',
                drillRoute: 'reports.low-stock',
            ),

            'inventory.product_count' => self::scalar(
                key: 'inventory.product_count',
                domain: 'inventory',
                label: 'Products',
                description: 'Total products in the catalogue.',
                help: 'Every product row, regardless of stock level.',
                unit: 'integer',
                direction: 'neutral',
                permissions: ['inventory.view'],
                capability: 'has_inventory',
                source: InventorySource::class,
                method: 'productCount',
                drillRoute: 'inventory.index',
            ),

            'inventory.overstock_count' => self::scalar(
                key: 'inventory.overstock_count',
                domain: 'inventory',
                label: 'Overstocked',
                description: 'Products holding more stock than the owner\'s overstock threshold.',
                help: '§6.2: off by default — returns not_applicable until reckoner.overstock_mode '
                    .'is turned on in Settings → Inventory. "auto" mode uses days-of-cover over 180 '
                    .'days; products with no sales history are never flagged.',
                unit: 'integer',
                direction: 'lower_is_better',
                permissions: ['inventory.view'],
                capability: 'has_inventory',
                source: InventorySource::class,
                method: 'overstockCount',
                drillRoute: 'inventory.index',
            ),

            /* ── Purchasing ───────────────────────────────────────────── */
            'purchasing.spend' => array_merge(self::scalar(
                key: 'purchasing.spend',
                domain: 'purchasing',
                label: 'Purchases',
                description: 'What you bought this period — accrual, not cash.',
                help: '§7.6: this is the accrual figure (purchases.total on purchase_date). See '
                    .'finance.paid_to_suppliers for what you actually paid. Never label either one '
                    .'just "Purchases" without this qualifier.',
                unit: 'currency',
                direction: 'lower_is_better',
                permissions: ['purchases.view', 'reports.financial'],
                capability: 'has_purchases',
                source: PurchasingSource::class,
                method: 'spend',
                drillRoute: 'purchases.index',
            ), ['additive' => true]),

            'purchasing.count' => array_merge(self::scalar(
                key: 'purchasing.count',
                domain: 'purchasing',
                label: 'Purchase Bills',
                description: 'Number of purchase bills recorded this period.',
                help: 'Excludes cancelled purchases (workflow_status = cancelled).',
                unit: 'integer',
                direction: 'neutral',
                permissions: ['purchases.view'],
                capability: 'has_purchases',
                source: PurchasingSource::class,
                method: 'count',
                drillRoute: 'purchases.index',
            ), ['additive' => true]),

            'finance.paid_to_suppliers' => array_merge(self::scalar(
                key: 'finance.paid_to_suppliers',
                domain: 'finance',
                label: 'Paid to Suppliers',
                description: 'Cash actually paid against purchase bills this period.',
                help: '§7.6: the cash figure — SUM of active allocations against purchases '
                    .'whose purchase_date falls in this period. See purchasing.spend for what you '
                    .'bought (accrual). Never label either one just "Purchases".',
                unit: 'currency',
                direction: 'lower_is_better',
                permissions: ['purchases.view', 'reports.financial'],
                capability: 'has_purchases',
                source: PurchasingSource::class,
                method: 'paidToSuppliers',
                drillRoute: 'purchases.index',
            ), ['additive' => true]),

            /* ── Party ────────────────────────────────────────────────── */
            'party.customer_count' => self::scalar(
                key: 'party.customer_count',
                domain: 'party',
                label: 'Customers',
                description: 'Total customers on file.',
                help: 'Every party with type = customer, regardless of activity.',
                unit: 'integer',
                direction: 'neutral',
                permissions: ['parties.view', 'sales.view'],
                capability: 'has_parties',
                source: PartySource::class,
                method: 'customerCount',
                periods: ['live'],
                defaultPeriod: 'live',
                drillRoute: 'parties.index',
            ),

            'party.supplier_count' => self::scalar(
                key: 'party.supplier_count',
                domain: 'party',
                label: 'Suppliers',
                description: 'Total suppliers on file.',
                help: 'Every party with type = supplier.',
                unit: 'integer',
                direction: 'neutral',
                permissions: ['parties.view', 'purchases.view'],
                capability: 'has_parties',
                source: PartySource::class,
                method: 'supplierCount',
                periods: ['live'],
                defaultPeriod: 'live',
                drillRoute: 'parties.index',
            ),

            'party.new_customers' => self::scalar(
                key: 'party.new_customers',
                domain: 'party',
                label: 'New Customers',
                description: 'Customers added in this period.',
                help: 'Counted by created_at falling inside the period.',
                unit: 'integer',
                direction: 'higher_is_better',
                permissions: ['parties.view', 'sales.view'],
                capability: 'has_parties',
                source: PartySource::class,
                method: 'newCustomers',
                drillRoute: 'parties.index',
            ),

            'party.dormant_customers' => self::scalar(
                key: 'party.dormant_customers',
                domain: 'party',
                label: 'Dormant Customers',
                description: 'Customers who have bought before but not recently.',
                help: '§6.3: "recently" is reckoner.dormant_days, defaulting by business type and '
                    .'owner-overridable in Settings → Customers. A customer who has never bought is '
                    .'excluded — never having sold to them is a different problem.',
                unit: 'integer',
                direction: 'lower_is_better',
                permissions: ['parties.view', 'sales.view', 'reports.performance'],
                capability: 'has_parties',
                source: PartySource::class,
                method: 'dormantCustomers',
                periods: ['live'],
                defaultPeriod: 'live',
                drillRoute: 'parties.index',
            ),

            /* ── Production ───────────────────────────────────────────── */
            'production.total_cost' => array_merge(self::scalar(
                key: 'production.total_cost',
                domain: 'production',
                label: 'Production Cost',
                description: 'The cost of completed manufacturing runs this period.',
                help: '§7.14: read from production_runs.total_cost (material + labor), which was '
                    .'always populated but never read — the old dashboard hardcoded this to 0. '
                    .'Returns not_applicable, never 0, when no runs completed in the period.',
                unit: 'currency',
                direction: 'lower_is_better',
                permissions: ['inventory.view'],
                feature: 'production',
                capability: 'has_manufacturing',
                source: ProductionSource::class,
                method: 'totalCost',
                drillRoute: 'production.index',
            ), ['additive' => true]),

            'production.run_count' => array_merge(self::scalar(
                key: 'production.run_count',
                domain: 'production',
                label: 'Production Runs',
                description: 'Completed manufacturing runs this period.',
                help: 'Counts production_runs with status = completed, by created_at.',
                unit: 'integer',
                direction: 'neutral',
                permissions: ['inventory.view'],
                feature: 'production',
                capability: 'has_manufacturing',
                source: ProductionSource::class,
                method: 'runCount',
                drillRoute: 'production.index',
            ), ['additive' => true]),

            /* ── Staff ────────────────────────────────────────────────── */
            'staff.on_shift_count' => self::scalar(
                key: 'staff.on_shift_count',
                domain: 'staff',
                label: 'Staff On Shift',
                description: 'Who is currently clocked in.',
                help: 'Attendance rows checked in today with no check-out yet.',
                unit: 'integer',
                direction: 'neutral',
                permissions: ['staff.view', 'admin.settings_manage'],
                capability: 'has_staff',
                source: StaffSource::class,
                method: 'onShiftCount',
                periods: ['live'],
                defaultPeriod: 'live',
                drillRoute: 'staff.index',
            ),

            'staff.member_count' => self::scalar(
                key: 'staff.member_count',
                domain: 'staff',
                label: 'Staff Members',
                description: 'People with access to this store.',
                help: 'Count of tenant_users for this tenant.',
                unit: 'integer',
                direction: 'neutral',
                permissions: ['staff.view', 'admin.settings_manage'],
                capability: 'has_staff',
                source: StaffSource::class,
                method: 'memberCount',
                periods: ['live'],
                defaultPeriod: 'live',
                drillRoute: 'staff.index',
            ),

            /* ── Operations ───────────────────────────────────────────── */
            'operations.open_sales_orders' => self::scalar(
                key: 'operations.open_sales_orders',
                domain: 'operations',
                label: 'Open Orders',
                description: 'Sales orders not yet fulfilled.',
                help: 'Status = open. A status added later shows up as "not open" rather than '
                    .'silently being counted as outstanding work.',
                unit: 'integer',
                direction: 'lower_is_better',
                permissions: ['sales.view'],
                capability: 'has_sales_orders',
                source: OperationsSource::class,
                method: 'openSalesOrders',
                periods: ['live'],
                defaultPeriod: 'live',
                drillRoute: 'sales-orders.index',
            ),

            'operations.pending_stock_takes' => self::scalar(
                key: 'operations.pending_stock_takes',
                domain: 'operations',
                label: 'Pending Stock Takes',
                description: 'Stock counts started but not yet completed.',
                help: 'Status = draft.',
                unit: 'integer',
                direction: 'lower_is_better',
                permissions: ['inventory.view'],
                capability: 'has_inventory',
                source: OperationsSource::class,
                method: 'pendingStockTakes',
                periods: ['live'],
                defaultPeriod: 'live',
                drillRoute: 'stock-takes.index',
            ),

            'operations.pending_stock_transfers' => self::scalar(
                key: 'operations.pending_stock_transfers',
                domain: 'operations',
                label: 'Pending Stock Transfers',
                description: 'Stock transfers awaiting approval.',
                help: 'Status = pending.',
                unit: 'integer',
                direction: 'lower_is_better',
                permissions: ['inventory.view'],
                capability: 'has_inventory',
                source: OperationsSource::class,
                method: 'pendingStockTransfers',
                periods: ['live'],
                defaultPeriod: 'live',
                drillRoute: 'stock-transfers.index',
            ),

            /* ── Tax ──────────────────────────────────────────────────── */
            'tax.collected' => array_merge(self::scalar(
                key: 'tax.collected',
                domain: 'tax',
                label: 'Tax Collected',
                description: 'Tax charged on posted sales this period.',
                help: 'SUM(sales.total_tax) for posted sales. Sales-side only — see the Phase 3 '
                    .'note on tax.net_payable in this build\'s known-gaps report before treating '
                    .'this as a full tax-liability figure.',
                unit: 'currency',
                direction: 'neutral',
                permissions: ['reports.financial', 'sales.view'],
                capability: null,
                source: TaxSource::class,
                method: 'collected',
                drillRoute: 'reports.financial',
            ), ['additive' => true]),

            /* ── Restaurant ───────────────────────────────────────────── */
            'restaurant.tables_occupied' => self::scalar(
                key: 'restaurant.tables_occupied',
                domain: 'restaurant',
                label: 'Tables Occupied',
                description: 'Restaurant tables currently seated.',
                help: 'Status = occupied on restaurant_tables.',
                unit: 'integer',
                direction: 'neutral',
                permissions: ['sales.view'],
                capability: 'has_restaurant',
                source: RestaurantSource::class,
                method: 'tablesOccupied',
                periods: ['live'],
                defaultPeriod: 'live',
                drillRoute: 'restaurant.dashboard',
            ),

            'restaurant.kitchen_orders_pending' => self::scalar(
                key: 'restaurant.kitchen_orders_pending',
                domain: 'restaurant',
                label: 'Kitchen Orders Pending',
                description: 'Orders in the kitchen not yet served.',
                help: 'Status in (pending, preparing) on kitchen_orders.',
                unit: 'integer',
                direction: 'lower_is_better',
                permissions: ['sales.view'],
                capability: 'has_restaurant',
                source: RestaurantSource::class,
                method: 'kitchenOrdersPending',
                periods: ['live'],
                defaultPeriod: 'live',
                drillRoute: 'restaurant.dashboard',
            ),

            /* ── Platform (scope: platform — never reachable from a tenant) ── */
            'platform.active_tenant_count' => self::scalar(
                key: 'platform.active_tenant_count',
                domain: 'platform',
                label: 'Active Stores',
                description: 'Stores currently on an active plan.',
                help: '§7.10: demo tenants excluded from the denominator, without exception.',
                unit: 'integer',
                direction: 'higher_is_better',
                permissions: ['platform.view'],
                capability: null,
                source: PlatformSource::class,
                method: 'activeTenantCount',
                periods: ['live'],
                defaultPeriod: 'live',
                scope: 'platform',
                drillRoute: 'superadmin.tenants',
            ),

            'platform.mrr' => self::scalar(
                key: 'platform.mrr',
                domain: 'platform',
                label: 'MRR',
                description: 'Monthly recurring revenue across active, non-demo stores.',
                help: 'INCOMPLETE per §7.9 — see PlatformSource::mrr() docblock: this is a naive '
                    .'plan-price sum, NOT the coupon-adjusted figure the spec names as the winner. '
                    .'Do not treat this number as correct until that gap is closed.',
                unit: 'currency',
                direction: 'higher_is_better',
                permissions: ['platform.view'],
                capability: null,
                source: PlatformSource::class,
                method: 'mrr',
                periods: ['live'],
                defaultPeriod: 'live',
                scope: 'platform',
                drillRoute: 'superadmin.billing',
            ),

            /* ── Phase B2 Metrics ────────────────────────────────────────── */
            'sales.revenue_trend' => [
                'key' => 'sales.revenue_trend',
                'domain' => 'sales',
                'label' => 'Revenue Trend',
                'generic' => 'Revenue Trend',
                'description' => 'Monthly sales revenue trend.',
                'help' => 'Historical revenue line chart.',
                'shape' => ReckonerShape::SERIES,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'higher_is_better',
                'signed' => false,
                'periods' => ['this_month', 'last_month', 'this_year', 'last_year'],
                'default_period' => 'this_month',
                'supports_comparison' => true,
                'supports_series' => true,
                'series_granularity' => ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
                'permissions' => ['sales.view'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => SalesSource::class,
                'method' => 'revenueTrend',
                'cache_ttl' => 60,
                'drill_route' => 'sales.index',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'finance.profit_trend' => [
                'key' => 'finance.profit_trend',
                'domain' => 'finance',
                'label' => 'Profit Trend',
                'generic' => 'Profit Trend',
                'description' => 'Historical net profit trend.',
                'help' => 'Signed profit & loss series.',
                'shape' => ReckonerShape::SERIES,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'higher_is_better',
                'signed' => true,
                'periods' => ['this_month', 'last_month', 'this_year', 'last_year'],
                'default_period' => 'this_month',
                'supports_comparison' => true,
                'supports_series' => true,
                'series_granularity' => ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
                'permissions' => ['finance.balances'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'profitTrend',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'sales.payment_breakdown' => [
                'key' => 'sales.payment_breakdown',
                'domain' => 'sales',
                'label' => 'Payment Breakdown',
                'generic' => 'Payment Breakdown',
                'description' => 'Sales breakdown by payment method.',
                'help' => 'Cash vs card payments breakdown.',
                'shape' => ReckonerShape::BREAKDOWN,
                'unit' => 'percentage',
                'precision' => 1,
                'direction' => 'neutral',
                'signed' => false,
                'periods' => ['today', 'this_month', 'this_year'],
                'default_period' => 'today',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['sales.view'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => SalesSource::class,
                'method' => 'paymentBreakdown',
                'cache_ttl' => 60,
                'drill_route' => 'sales.index',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'finance.expenses_by_category' => [
                'key' => 'finance.expenses_by_category',
                'domain' => 'finance',
                'label' => 'Expenses by Category',
                'generic' => 'Expenses by Category',
                'description' => 'Operating expenses breakdown by category.',
                'help' => 'Pie chart of top expense accounts.',
                'shape' => ReckonerShape::BREAKDOWN,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'lower_is_better',
                'signed' => false,
                'periods' => ['this_month', 'last_month', 'this_year'],
                'default_period' => 'this_month',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['finance.transactions'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'expensesByCategory',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'sales.top_products' => [
                'key' => 'sales.top_products',
                'domain' => 'sales',
                'label' => 'Top Products',
                'generic' => 'Top Products',
                'description' => 'Highest selling products this period.',
                'help' => 'Top 10 products by quantity and value.',
                'shape' => ReckonerShape::RANKING,
                'unit' => 'integer',
                'precision' => 0,
                'direction' => 'higher_is_better',
                'signed' => false,
                'periods' => ['today', 'this_month', 'this_year'],
                'default_period' => 'this_month',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['sales.view'],
                'feature' => null,
                'capability' => 'has_inventory',
                'scope' => 'tenant',
                'source' => SalesSource::class,
                'method' => 'topProducts',
                'cache_ttl' => 60,
                'drill_route' => 'sales.index',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'sales.top_customers' => [
                'key' => 'sales.top_customers',
                'domain' => 'sales',
                'label' => 'Top Customers',
                'generic' => 'Top Customers',
                'description' => 'Highest value customers this period.',
                'help' => 'Top 10 customers by revenue contribution.',
                'shape' => ReckonerShape::RANKING,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'higher_is_better',
                'signed' => false,
                'periods' => ['this_month', 'this_year'],
                'default_period' => 'this_month',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['sales.view'],
                'feature' => null,
                'capability' => 'has_parties',
                'scope' => 'tenant',
                'source' => PartySource::class,
                'method' => 'topCustomers',
                'cache_ttl' => 60,
                'drill_route' => 'parties.index',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'inventory.low_stock_list' => [
                'key' => 'inventory.low_stock_list',
                'domain' => 'inventory',
                'label' => 'Low Stock Items',
                'generic' => 'Low Stock Items',
                'description' => 'Products below alert quantity.',
                'help' => 'Products with quantity <= alert quantity.',
                'shape' => ReckonerShape::TABLE,
                'unit' => 'integer',
                'precision' => 0,
                'direction' => 'lower_is_better',
                'signed' => false,
                'periods' => ['live'],
                'default_period' => 'live',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['inventory.view'],
                'feature' => null,
                'capability' => 'has_inventory',
                'scope' => 'tenant',
                'source' => InventorySource::class,
                'method' => 'lowStockList',
                'cache_ttl' => 60,
                'drill_route' => 'inventory.index',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'finance.receivables_aging' => [
                'key' => 'finance.receivables_aging',
                'domain' => 'finance',
                'label' => 'Receivables Aging',
                'generic' => 'Receivables Aging',
                'description' => 'Outstanding invoices grouped by aging days.',
                'help' => 'Slices: 0-30, 31-60, 61-90, 90+ days.',
                'shape' => ReckonerShape::BREAKDOWN,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'lower_is_better',
                'signed' => false,
                'periods' => ['live'],
                'default_period' => 'live',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['finance.balances'],
                'feature' => null,
                'capability' => 'has_parties',
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'receivablesAging',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'finance.cash_flow_trend' => [
                'key' => 'finance.cash_flow_trend',
                'domain' => 'finance',
                'label' => 'Cash Flow Trend',
                'generic' => 'Cash Flow Trend',
                'description' => 'Money in vs money out trends.',
                'help' => 'Monthly multi-line trend of income vs expenses.',
                'shape' => ReckonerShape::MULTI_SERIES,
                'unit' => 'currency',
                'precision' => 2,
                'direction' => 'neutral',
                'signed' => false,
                'periods' => ['this_month', 'this_year'],
                'default_period' => 'this_month',
                'supports_comparison' => false,
                'supports_series' => true,
                'series_granularity' => ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
                'permissions' => ['finance.balances'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => FinanceSource::class,
                'method' => 'cashFlowTrend',
                'cache_ttl' => 60,
                'drill_route' => 'reports.financial',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'sales.hourly_heatmap' => [
                'key' => 'sales.hourly_heatmap',
                'domain' => 'sales',
                'label' => 'Hourly Sales Heatmap',
                'generic' => 'Hourly Sales Heatmap',
                'description' => 'Sales count by hour of day and day of week.',
                'help' => 'Grid showing sales frequency concentration.',
                'shape' => ReckonerShape::TABLE,
                'unit' => 'integer',
                'precision' => 0,
                'direction' => 'neutral',
                'signed' => false,
                'periods' => ['this_month', 'this_year'],
                'default_period' => 'this_month',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['sales.view'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => SalesSource::class,
                'method' => 'hourlySalesHeatmap',
                'cache_ttl' => 60,
                'drill_route' => 'sales.index',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'plan.usage_summary' => [
                'key' => 'plan.usage_summary',
                'domain' => 'operations',
                'label' => 'Plan Usage Summary',
                'generic' => 'Plan Usage Summary',
                'description' => 'Usage vs limits on active plan items.',
                'help' => 'Usage percentage of invoices, products, suppliers.',
                'shape' => ReckonerShape::GAUGE,
                'unit' => 'percentage',
                'precision' => 0,
                'direction' => 'neutral',
                'signed' => false,
                'periods' => ['live'],
                'default_period' => 'live',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['admin.settings_manage'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => OperationsSource::class,
                'method' => 'planUsageSummary',
                'cache_ttl' => 60,
                'drill_route' => 'superadmin.billing',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'sales.live_feed' => [
                'key' => 'sales.live_feed',
                'domain' => 'sales',
                'label' => 'Live Sales Feed',
                'generic' => 'Live Sales Feed',
                'description' => 'Real-time activity log of orders and payments.',
                'help' => 'Latest 20 store transactions.',
                'shape' => ReckonerShape::FEED,
                'unit' => 'text',
                'precision' => 0,
                'direction' => 'neutral',
                'signed' => false,
                'periods' => ['live'],
                'default_period' => 'live',
                'supports_comparison' => false,
                'supports_series' => false,
                'series_granularity' => [],
                'permissions' => ['sales.view'],
                'feature' => null,
                'capability' => null,
                'scope' => 'tenant',
                'source' => SalesSource::class,
                'method' => 'liveSalesFeed',
                'cache_ttl' => 60,
                'drill_route' => 'sales.index',
                'dimensions' => [],
                'filters'    => [],
                'additive'   => false,
            ],

            'finance.net_margin_pct_derived' => [
                'key'                 => 'finance.net_margin_pct_derived',
                'domain'              => 'finance',
                'label'               => 'Net Margin (computed)',
                'generic'             => 'Net Margin',
                'description'         => 'Net profit ÷ revenue, guaranteed consistent with the ledger figures.',
                'help'                => 'Derived: net_profit / revenue × 100. Cannot disagree with either component.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'percent',
                'precision'           => 2,
                'direction'           => 'higher_is_better',
                'signed'              => false,
                'periods'             => ReckonerPeriod::KEYS,
                'default_period'      => 'this_month',
                'supports_comparison' => true,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['finance.balances', 'reports.financial'],
                'feature'             => null,
                'capability'          => null,
                'scope'               => 'tenant',
                'cache_ttl'           => 60,
                'drill_route'         => 'reports.financial',
                'dimensions'          => [],
                'filters'             => [],
                'additive'            => false,
                'derived'             => ['finance.net_profit', 'sales.revenue'],
                'compute'             => function (array $r): ?float {
                    $revenue = $r['sales.revenue'] ?? null;
                    $netProfit = $r['finance.net_profit'] ?? null;
                    return ($revenue !== null && $revenue > 0.0 && $netProfit !== null)
                        ? round(($netProfit / $revenue) * 100, 2)
                        : null;
                },
            ],

            'finance.expense_ratio' => [
                'key'                 => 'finance.expense_ratio',
                'domain'              => 'finance',
                'label'               => 'Expense Ratio',
                'generic'             => 'Expense Ratio',
                'description'         => 'Operating expenses as a percentage of revenue.',
                'help'                => 'Derived: expenses_total / revenue × 100. A rising ratio signals cost pressure.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'percent',
                'precision'           => 2,
                'direction'           => 'lower_is_better',
                'signed'              => false,
                'periods'             => ReckonerPeriod::KEYS,
                'default_period'      => 'this_month',
                'supports_comparison' => true,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['finance.balances', 'finance.transactions', 'reports.financial'],
                'feature'             => null,
                'capability'          => null,
                'scope'               => 'tenant',
                'cache_ttl'           => 60,
                'drill_route'         => 'reports.financial',
                'dimensions'          => [],
                'filters'             => [],
                'additive'            => false,
                'derived'             => ['finance.expenses_total', 'sales.revenue'],
                'compute'             => function (array $r): ?float {
                    $revenue = $r['sales.revenue'] ?? null;
                    $expenses = $r['finance.expenses_total'] ?? null;
                    return ($revenue !== null && $revenue > 0.0 && $expenses !== null)
                        ? round(($expenses / $revenue) * 100, 2)
                        : null;
                },
            ],

            'reminders.count' => [
                'key'                 => 'reminders.count',
                'domain'              => 'operations',
                'label'               => 'Invoice Reminders',
                'generic'             => 'Reminders',
                'description'         => 'Count of invoice payment reminders.',
                'help'                => 'Filtered by status: all, scheduled, pending, sent, overdue.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'integer',
                'precision'           => 0,
                'direction'           => 'lower_is_better',
                'signed'              => false,
                'periods'             => ['live', 'today', 'this_month'],
                'default_period'      => 'live',
                'supports_comparison' => false,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['reports.summary', 'sales.view'],
                'feature'             => null,
                'capability'          => null,
                'scope'               => 'tenant',
                'source'              => OperationsSource::class,
                'method'              => 'reminderCount',
                'cache_ttl'           => 60,
                'drill_route'         => 'sales.index',
                'dimensions'          => [
                    'status' => ['enum' => ['all', 'scheduled', 'pending', 'sent', 'overdue'], 'default' => 'all'],
                ],
                'filters'             => [],
                'additive'            => false,
            ],

            'recurring_invoices.count' => [
                'key'                 => 'recurring_invoices.count',
                'domain'              => 'operations',
                'label'               => 'Recurring Invoices',
                'generic'             => 'Recurring Invoices',
                'description'         => 'Count of recurring invoice schedules.',
                'help'                => 'Filtered by status: all, active, paused.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'integer',
                'precision'           => 0,
                'direction'           => 'higher_is_better',
                'signed'              => false,
                'periods'             => ['live'],
                'default_period'      => 'live',
                'supports_comparison' => false,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['reports.summary', 'sales.view'],
                'feature'             => null,
                'capability'          => null,
                'scope'               => 'tenant',
                'source'              => OperationsSource::class,
                'method'              => 'recurringInvoiceCount',
                'cache_ttl'           => 60,
                'drill_route'         => 'sales.index',
                'dimensions'          => [
                    'status' => ['enum' => ['all', 'active', 'paused'], 'default' => 'all'],
                ],
                'filters'             => [],
                'additive'            => false,
            ],

            'recurring_invoices.revenue' => [
                'key'                 => 'recurring_invoices.revenue',
                'domain'              => 'operations',
                'label'               => 'Recurring Monthly Revenue',
                'generic'             => 'Recurring Revenue',
                'description'         => 'Monthly recurring revenue from active schedules.',
                'help'                => 'Sum of amount on active recurring invoice schedules.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'currency',
                'precision'           => 2,
                'direction'           => 'higher_is_better',
                'signed'              => false,
                'periods'             => ['live'],
                'default_period'      => 'live',
                'supports_comparison' => false,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['reports.financial', 'sales.view'],
                'feature'             => null,
                'capability'          => null,
                'scope'               => 'tenant',
                'source'              => OperationsSource::class,
                'method'              => 'recurringInvoiceRevenue',
                'cache_ttl'           => 60,
                'drill_route'         => 'sales.index',
                'dimensions'          => [],
                'filters'             => [],
                'additive'            => false,
            ],

            'batch_tracking.count' => [
                'key'                 => 'batch_tracking.count',
                'domain'              => 'inventory',
                'label'               => 'Inventory Batches',
                'generic'             => 'Batches',
                'description'         => 'Count of active inventory batches.',
                'help'                => 'Filtered by status: all, expiring_soon, expired.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'integer',
                'precision'           => 0,
                'direction'           => 'neutral',
                'signed'              => false,
                'periods'             => ['live'],
                'default_period'      => 'live',
                'supports_comparison' => false,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['inventory.view'],
                'feature'             => null,
                'capability'          => 'has_inventory',
                'scope'               => 'tenant',
                'source'              => OperationsSource::class,
                'method'              => 'batchCount',
                'cache_ttl'           => 60,
                'drill_route'         => 'inventory.index',
                'dimensions'          => [
                    'status' => ['enum' => ['all', 'expiring_soon', 'expired'], 'default' => 'all'],
                ],
                'filters'             => [],
                'additive'            => false,
            ],

            'batch_tracking.qty' => [
                'key'                 => 'batch_tracking.qty',
                'domain'              => 'inventory',
                'label'               => 'Batched Stock Quantity',
                'generic'             => 'Batched Qty',
                'description'         => 'Total unit quantity across all inventory batches.',
                'help'                => 'Sum of batch quantities currently held.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'decimal',
                'precision'           => 2,
                'direction'           => 'higher_is_better',
                'signed'              => false,
                'periods'             => ['live'],
                'default_period'      => 'live',
                'supports_comparison' => false,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['inventory.view'],
                'feature'             => null,
                'capability'          => 'has_inventory',
                'scope'               => 'tenant',
                'source'              => OperationsSource::class,
                'method'              => 'batchQuantity',
                'cache_ttl'           => 60,
                'drill_route'         => 'inventory.index',
                'dimensions'          => [],
                'filters'             => [],
                'additive'            => false,
            ],

            'proposals.count' => [
                'key'                 => 'proposals.count',
                'domain'              => 'sales',
                'label'               => 'Proposals',
                'generic'             => 'Proposals',
                'description'         => 'Count of customer proposals and quotes.',
                'help'                => 'Filtered by status: all, accepted, pending.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'integer',
                'precision'           => 0,
                'direction'           => 'higher_is_better',
                'signed'              => false,
                'periods'             => ['live', 'today', 'this_month'],
                'default_period'      => 'live',
                'supports_comparison' => false,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['sales.view'],
                'feature'             => null,
                'capability'          => null,
                'scope'               => 'tenant',
                'source'              => OperationsSource::class,
                'method'              => 'proposalCount',
                'cache_ttl'           => 60,
                'drill_route'         => 'sales.index',
                'dimensions'          => [
                    'status' => ['enum' => ['all', 'accepted', 'pending'], 'default' => 'all'],
                ],
                'filters'             => [],
                'additive'            => false,
            ],

            'purchase_orders.count' => [
                'key'                 => 'purchase_orders.count',
                'domain'              => 'purchasing',
                'label'               => 'Purchase Orders',
                'generic'             => 'Purchase Orders',
                'description'         => 'Count of purchase orders.',
                'help'                => 'Filtered by status: all, pending, received.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'integer',
                'precision'           => 0,
                'direction'           => 'neutral',
                'signed'              => false,
                'periods'             => ['live', 'today', 'this_month'],
                'default_period'      => 'live',
                'supports_comparison' => false,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['purchases.view'],
                'feature'             => null,
                'capability'          => null,
                'scope'               => 'tenant',
                'source'              => PurchasingSource::class,
                'method'              => 'purchaseOrderCount',
                'cache_ttl'           => 60,
                'drill_route'         => 'purchases.index',
                'dimensions'          => [
                    'status' => ['enum' => ['all', 'pending', 'received'], 'default' => 'all'],
                ],
                'filters'             => [],
                'additive'            => false,
            ],

            'sales_orders.count' => [
                'key'                 => 'sales_orders.count',
                'domain'              => 'sales',
                'label'               => 'Sales Orders',
                'generic'             => 'Sales Orders',
                'description'         => 'Count of sales orders.',
                'help'                => 'Filtered by status: all, confirmed, pending.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'integer',
                'precision'           => 0,
                'direction'           => 'higher_is_better',
                'signed'              => false,
                'periods'             => ['live', 'today', 'this_month'],
                'default_period'      => 'live',
                'supports_comparison' => false,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['sales.view'],
                'feature'             => null,
                'capability'          => 'has_sales_orders',
                'scope'               => 'tenant',
                'source'              => SalesSource::class,
                'method'              => 'salesOrderCount',
                'cache_ttl'           => 60,
                'drill_route'         => 'sales-orders.index',
                'dimensions'          => [
                    'status' => ['enum' => ['all', 'confirmed', 'pending'], 'default' => 'all'],
                ],
                'filters'             => [],
                'additive'            => false,
            ],

            'returns.count' => [
                'key'                 => 'returns.count',
                'domain'              => 'sales',
                'label'               => 'Sales Returns',
                'generic'             => 'Returns',
                'description'         => 'Count of return transactions within the period.',
                'help'                => 'Number of posted return invoices.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'integer',
                'precision'           => 0,
                'direction'           => 'lower_is_better',
                'signed'              => false,
                'periods'             => ReckonerPeriod::KEYS,
                'default_period'      => 'this_month',
                'supports_comparison' => true,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['sales.view', 'reports.summary'],
                'feature'             => null,
                'capability'          => null,
                'scope'               => 'tenant',
                'source'              => SalesSource::class,
                'method'              => 'returnsCount',
                'cache_ttl'           => 60,
                'drill_route'         => 'sales.index',
                'dimensions'          => [],
                'filters'             => [],
                'additive'            => true,
            ],

            'returns.qty' => [
                'key'                 => 'returns.qty',
                'domain'              => 'sales',
                'label'               => 'Returned Units',
                'generic'             => 'Returned Qty',
                'description'         => 'Total unit quantity returned within the period.',
                'help'                => 'Sum of item quantities on return transactions.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'decimal',
                'precision'           => 2,
                'direction'           => 'lower_is_better',
                'signed'              => false,
                'periods'             => ReckonerPeriod::KEYS,
                'default_period'      => 'this_month',
                'supports_comparison' => true,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['sales.view', 'reports.summary'],
                'feature'             => null,
                'capability'          => null,
                'scope'               => 'tenant',
                'source'              => SalesSource::class,
                'method'              => 'returnsQty',
                'cache_ttl'           => 60,
                'drill_route'         => 'sales.index',
                'dimensions'          => [],
                'filters'             => [],
                'additive'            => true,
            ],

            'returns.value' => [
                'key'                 => 'returns.value',
                'domain'              => 'sales',
                'label'               => 'Returned Value',
                'generic'             => 'Returns Value',
                'description'         => 'Total refunded monetary amount for returns within the period.',
                'help'                => 'Sum of grand totals across return transactions.',
                'shape'               => ReckonerShape::SCALAR,
                'unit'                => 'currency',
                'precision'           => 2,
                'direction'           => 'lower_is_better',
                'signed'              => false,
                'periods'             => ReckonerPeriod::KEYS,
                'default_period'      => 'this_month',
                'supports_comparison' => true,
                'supports_series'     => false,
                'series_granularity'  => [],
                'permissions'         => ['sales.view', 'reports.financial'],
                'feature'             => null,
                'capability'          => null,
                'scope'               => 'tenant',
                'source'              => SalesSource::class,
                'method'              => 'returnsValue',
                'cache_ttl'           => 60,
                'drill_route'         => 'sales.index',
                'dimensions'          => [],
                'filters'             => [],
                'additive'            => true,
            ],
        ];

        foreach ($all as $key => &$def) {
            $def['implemented'] = $def['implemented'] ?? true;
            $def['module'] = self::MODULE_MAP[$key] ?? null;
            $def['is_new'] = in_array($key, self::NEW_KEYS, true);
        }
        unset($def);

        return self::$cache = $all;
    }

    /**
     * Builds one registry entry with sensible defaults, so ~20 new Phase 2
     * entries don't each repeat every field verbatim. Every field from §3.1
     * is still present in the resulting array — this only removes
     * boilerplate, not the contract.
     */
    private static function scalar(
        string $key,
        string $domain,
        string $label,
        string $description,
        string $help,
        string $unit,
        string $direction,
        array $permissions,
        ?string $capability,
        string $source,
        string $method,
        ?array $periods = null,
        ?string $defaultPeriod = null,
        ?string $feature = null,
        string $scope = 'tenant',
        bool $signed = false,
        ?string $drillRoute = null,
    ): array {
        return [
            'key' => $key,
            'domain' => $domain,
            'label' => $label,
            'generic' => $label,
            'description' => $description,
            'help' => $help,
            'shape' => ReckonerShape::SCALAR,
            'unit' => $unit,
            'precision' => $unit === 'currency' ? 2 : 0,
            'direction' => $direction,
            'signed' => $signed,
            'periods' => $periods ?? ReckonerPeriod::KEYS,
            'default_period' => $defaultPeriod ?? 'today',
            'supports_comparison' => ($periods ?? null) !== ['live'],
            'supports_series' => ($periods ?? null) !== ['live'],
            'series_granularity' => ($periods ?? null) === ['live'] ? [] : ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
            'permissions' => $permissions,
            'feature' => $feature,
            'capability' => $capability,
            'scope' => $scope,
            'source' => $source,
            'method' => $method,
            'cache_ttl' => 60,
            'drill_route' => $drillRoute,
            'implemented' => true,
            'dimensions' => [],
            'filters'    => [],
            'additive'   => false,
        ];
    }

    public static function find(string $key): ?array
    {
        return self::all()[$key] ?? null;
    }

    public static function exists(string $key): bool
    {
        return array_key_exists($key, self::all());
    }

    public static function scopeOf(string $key): ?string
    {
        return self::find($key)['scope'] ?? null;
    }

    /**
     * Generate the V6 Dashboard reading catalog from ReckonerRegistry.
     * Guaranteed that every reading emitted here has a verified calculation implementation.
     */
    public static function v6Catalog(bool $includePlatform = false): array
    {
        $catalog = [];
        foreach (self::all() as $key => $def) {
            if (!$includePlatform && ($def['scope'] ?? 'tenant') === 'platform') {
                continue;
            }

            $domain = $def['domain'] ?? 'operations';
            $area = match ($domain) {
                'sales' => 'Sales',
                'finance', 'tax' => 'Finance',
                'inventory', 'production' => 'Inventory',
                'purchasing' => 'Purchasing',
                default => 'Operations',
            };

            $module = $def['module'] ?? self::MODULE_MAP[$key] ?? ucfirst($domain);
            if (is_array($module)) {
                $module = ucfirst($module[0] ?? $domain);
            }

            $catalog[] = [
                'key' => $key,
                'label' => $def['label'],
                'shape' => strtoupper($def['shape']->value),
                'unit' => $def['unit'],
                'area' => $area,
                'module' => is_string($module) ? ucfirst($module) : ucfirst($domain),
                'short' => $def['generic'] ?? $def['label'],
                'extra' => in_array($key, self::NEW_KEYS, true),
                'desc' => $def['description'] ?? '',
                'rowNames' => [],
                'sliceNames' => [],
            ];
        }
        return $catalog;
    }

    /** For tests: reset the static cache between fixtures. */
    public static function clearCache(): void
    {
        self::$cache = null;
    }
}
