<?php

require __DIR__ . '/../vendor/autoload.php';
$app = require_once __DIR__ . '/../bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

$file = file_get_contents(__DIR__ . '/../resources/js/Pages/NewDashboard.jsx');
if (!preg_match('/const READINGS = (\[.*?\]);/s', $file, $m)) {
    die("Could not find const READINGS in NewDashboard.jsx\n");
}

$jsReadings = json_decode($m[1], true);
if (!$jsReadings) {
    die("Failed to decode JSON from const READINGS\n");
}

$reckonerKeys = array_keys(App\Reckoner\ReckonerRegistry::all());

$present = [];
$missing = [];
foreach ($jsReadings as $r) {
    if (in_array($r['key'], $reckonerKeys)) {
        $present[] = $r['key'];
    } else {
        $missing[] = $r;
    }
}

echo "TOTAL JS READINGS: " . count($jsReadings) . "\n";
echo "PRESENT IN RECKONER: " . count($present) . "\n";
echo "MISSING (BACKLOG): " . count($missing) . "\n";

$backlogContent = "<?php\n\n/**\n * Reckoner Backlog — Readings declared in V6 UI that do not yet have Reckoner calculations.\n * Generated by Step 0.4 Truth Gate.\n */\nreturn " . var_export($missing, true) . ";\n";

file_put_contents(__DIR__ . '/../config/reckoner_backlog.php', $backlogContent);
echo "Successfully wrote " . count($missing) . " items to config/reckoner_backlog.php\n";
