<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Schema;
use App\Models\Tenant;
use App\Services\GoogleDriveService;

class VqBackupController extends Controller
{
    /**
     * Export all store data into a single encrypted .vq file.
     * Dynamically scans every single database table containing tenant_id to guarantee
     * 100% data fidelity (transactions, cash in hand, settings, products, stocks, etc.).
     */
    /**
     * Generate the encrypted backup payload string.
     */
    public function generateBackupPayload(Tenant $tenant): string
    {
        $dbName = DB::connection()->getDatabaseName();
        $allTables = DB::select("SHOW TABLES");
        $keyName = "Tables_in_{$dbName}";
        
        $tenantTables = [];

        foreach ($allTables as $tableObj) {
            $tableName = $tableObj->$keyName ?? array_values((array)$tableObj)[0];
            if (Schema::hasColumn($tableName, 'tenant_id')) {
                $tenantTables[] = $tableName;
            }
        }

        $backupData = [];

        foreach ($tenantTables as $table) {
            $backupData[$table] = DB::table($table)
                ->where('tenant_id', $tenant->id)
                ->get()
                ->toArray();
        }

        return Crypt::encryptString(json_encode($backupData));
    }

    public function export()
    {
        $tenant = app('current.tenant');
        if (!$tenant) {
            return back()->with('error', 'No active store context found.');
        }

        try {
            $encryptedPayload = $this->generateBackupPayload($tenant);
            $filename = 'venqore_backup_' . $tenant->slug . '_' . date('Y-m-d_His') . '.vq';

            Log::info("Tenant {$tenant->id} ('{$tenant->slug}') successfully exported complete encrypted .vq backup.");

            return response()->streamDownload(function () use ($encryptedPayload) {
                echo $encryptedPayload;
            }, $filename, [
                'Content-Type' => 'application/octet-stream',
            ]);

        } catch (\Exception $e) {
            Log::error("Backup Export failed for store {$tenant->id}: " . $e->getMessage());
            return back()->with('error', 'Failed to generate store backup: ' . $e->getMessage());
        }
    }

    /**
     * Manually sync the current store state to Google Drive.
     */
    public function syncToGoogleDrive(GoogleDriveService $driveService)
    {
        $tenant = app('current.tenant');
        if (!$tenant) {
            return back()->with('error', 'No active store context found.');
        }

        if (!$tenant->google_refresh_token) {
            return back()->with('error', 'Google Drive integration is not connected.');
        }

        try {
            $payload = $this->generateBackupPayload($tenant);
            $filename = 'venqore_backup_manual_' . date('Y-m-d_His') . '.vq';

            $uploaded = $driveService->uploadBackup($tenant, $filename, $payload);

            if ($uploaded) {
                // Prune any backups exceeding the retention settings
                $driveService->pruneOldBackups($tenant);
                return back()->with('success', 'Backup synced successfully to your Google Drive folder!');
            }

            return back()->with('error', 'Failed to upload backup to Google Drive. Check connection logs.');

        } catch (\Exception $e) {
            Log::error("Manual Google Drive sync failed for store {$tenant->id}: " . $e->getMessage());
            return back()->with('error', 'Failed to sync backup to Google Drive: ' . $e->getMessage());
        }
    }

    /**
     * Import and restore store data from an encrypted .vq file.
     */
    public function import(Request $request)
    {
        $request->validate([
            'file' => 'required|file'
        ]);

        $tenant = app('current.tenant');
        if (!$tenant) {
            return back()->with('error', 'No active store context found.');
        }

        $file = $request->file('file');

        // Check file extension
        if ($file->getClientOriginalExtension() !== 'vq') {
            return back()->with('error', 'Invalid file type. Please upload a valid .vq backup file.');
        }

        try {
            $encryptedContent = file_get_contents($file->getRealPath());

            // Decrypt the payload
            try {
                $decryptedJson = Crypt::decryptString($encryptedContent);
            } catch (\Exception $decryptException) {
                return back()->with('error', 'Failed to decrypt backup. This file is corrupt or was generated by a different system key.');
            }

            $backupData = json_decode($decryptedJson, true);

            if (!is_array($backupData)) {
                return back()->with('error', 'Backup format is invalid or empty.');
            }

            // Rebuild database tables in a single transaction
            DB::transaction(function () use ($tenant, $backupData) {
                Schema::disableForeignKeyConstraints();
                try {
                    // 1. Clear existing rows for this tenant
                    foreach (array_keys($backupData) as $table) {
                        if (Schema::hasTable($table)) {
                            DB::table($table)->where('tenant_id', $tenant->id)->delete();
                        }
                    }

                    // 2. Insert new rows, enforcing current tenant_id for absolute security
                    foreach ($backupData as $table => $rows) {
                        if (Schema::hasTable($table) && !empty($rows)) {
                            $insertBuffer = [];
                            foreach ($rows as $row) {
                                $rowArray = (array) $row;
                                
                                // FORCE override the tenant_id column so backup cannot inject data into another store
                                $rowArray['tenant_id'] = $tenant->id;
                                
                                $insertBuffer[] = $rowArray;
                            }
                            
                            // Chunk inserts to prevent SQL parameter limits
                            foreach (array_chunk($insertBuffer, 200) as $chunk) {
                                DB::table($table)->insert($chunk);
                            }
                        }
                    }
                } finally {
                    Schema::enableForeignKeyConstraints();
                }
            });

            Log::info("Tenant {$tenant->id} ('{$tenant->slug}') successfully restored complete data from .vq backup.");
            return back()->with('success', 'Store data restored successfully. All products, sales history, cash in hand, bank balances, and configuration settings are exactly as you left them!');

        } catch (\Exception $e) {
            Log::error("Backup Import failed for store {$tenant->id}: " . $e->getMessage());
            return back()->with('error', 'Failed to restore backup: ' . $e->getMessage());
        }
    }

    /**
     * Download a specific backup file from Google Drive.
     */
    public function downloadFromGoogleDrive(GoogleDriveService $driveService, $fileId)
    {
        $tenant = app('current.tenant');
        if (!$tenant) {
            return back()->with('error', 'No active store context found.');
        }

        try {
            // Need to retrieve file name to serve correctly
            $accessToken = $driveService->getAccessToken($tenant);
            $metaResponse = \Illuminate\Support\Facades\Http::withToken($accessToken)
                ->get("https://www.googleapis.com/drive/v3/files/{$fileId}", [
                    'fields' => 'name',
                ]);
            $filename = $metaResponse->successful() ? $metaResponse->json('name') : "backup_{$fileId}.vq";

            $payload = $driveService->downloadFile($tenant, $fileId);

            if ($payload === null) {
                return back()->with('error', 'Failed to download backup file from Google Drive.');
            }

            return response()->streamDownload(function () use ($payload) {
                echo $payload;
            }, $filename, [
                'Content-Type' => 'application/octet-stream',
            ]);
        } catch (\Exception $e) {
            Log::error("Failed to stream download from Google Drive for store {$tenant->id}: " . $e->getMessage());
            return back()->with('error', 'Download failed: ' . $e->getMessage());
        }
    }

    /**
     * Delete a specific backup file from Google Drive.
     */
    public function deleteFromGoogleDrive(GoogleDriveService $driveService, $fileId)
    {
        $tenant = app('current.tenant');
        if (!$tenant) {
            return back()->with('error', 'No active store context found.');
        }

        try {
            $deleted = $driveService->deleteFile($tenant, $fileId);
            if ($deleted) {
                return back()->with('success', 'Backup deleted from Google Drive successfully.');
            }
            return back()->with('error', 'Failed to delete backup from Google Drive.');
        } catch (\Exception $e) {
            Log::error("Failed to delete backup from Google Drive for store {$tenant->id}: " . $e->getMessage());
            return back()->with('error', 'Deletion failed: ' . $e->getMessage());
        }
    }

    /**
     * Restore the database directly from a specific Google Drive backup file.
     */
    public function restoreFromGoogleDrive(GoogleDriveService $driveService, $fileId)
    {
        $tenant = app('current.tenant');
        if (!$tenant) {
            return back()->with('error', 'No active store context found.');
        }

        try {
            $encryptedContent = $driveService->downloadFile($tenant, $fileId);
            if ($encryptedContent === null) {
                return back()->with('error', 'Failed to download backup file from Google Drive.');
            }

            // Decrypt the payload
            try {
                $decryptedJson = Crypt::decryptString($encryptedContent);
            } catch (\Exception $decryptException) {
                return back()->with('error', 'Failed to decrypt backup. This file is corrupt or was generated by a different system key.');
            }

            $backupData = json_decode($decryptedJson, true);
            if (!is_array($backupData)) {
                return back()->with('error', 'Backup format is invalid or empty.');
            }

            // Rebuild database tables in a single transaction
            DB::transaction(function () use ($tenant, $backupData) {
                Schema::disableForeignKeyConstraints();
                try {
                    // 1. Clear existing rows for this tenant
                    foreach (array_keys($backupData) as $table) {
                        if (Schema::hasTable($table)) {
                            DB::table($table)->where('tenant_id', $tenant->id)->delete();
                        }
                    }

                    // 2. Insert new rows, enforcing current tenant_id for absolute security
                    foreach ($backupData as $table => $rows) {
                        if (Schema::hasTable($table) && !empty($rows)) {
                            $insertBuffer = [];
                            foreach ($rows as $row) {
                                $rowArray = (array) $row;
                                $rowArray['tenant_id'] = $tenant->id;
                                $insertBuffer[] = $rowArray;
                            }
                            
                            foreach (array_chunk($insertBuffer, 200) as $chunk) {
                                DB::table($table)->insert($chunk);
                            }
                        }
                    }
                } finally {
                    Schema::enableForeignKeyConstraints();
                }
            });

            Log::info("Tenant {$tenant->id} ('{$tenant->slug}') successfully restored data directly from Google Drive backup {$fileId}.");
            return back()->with('success', 'Store data restored directly from Google Drive backup successfully!');

        } catch (\Exception $e) {
            Log::error("Direct Google Drive backup restore failed for store {$tenant->id}: " . $e->getMessage());
            return back()->with('error', 'Failed to restore Google Drive backup: ' . $e->getMessage());
        }
    }
}
