import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {SalesPlot,PlotBoundary} from './Charts';
import AutoCard from './AutoCard';
import EditorDemo from './EditorDemo';
import ProductionNotes from './ProductionNotes';
import {families,datasets,sizes,defaults,chooseFamily,chooseDataset,chooseSize,sizeAllowed,variantAllowed,controls,geometry,readSaved,validate,salesTotal,money,history,breakdown,stages,targets,radarData,flows,hierarchy,heatmap,transactions} from './model';
import './studio.css';
function useWidth(){const ref=useRef(null),[width,setWidth]=useState(0);useEffect(()=>{const o=new ResizeObserver(([e])=>setWidth(Math.round(e.contentRect.width)));if(ref.current)o.observe(ref.current);return()=>o.disconnect()},[]);return [ref,width]}
const nice=s=>s.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
function Field({label,id,children}){return <div className="field"><label htmlFor={id}>{label}</label>{children}</div>}
function rawRows(c){switch(c.dataset){case 'total':return [{sales:salesTotal}];case 'target':return [{sales:salesTotal,target:c.target}];case 'history':return history.map(({date,...r})=>({date:date.toLocaleDateString('en-GB'),...r}));case 'breakdown':return breakdown;case 'pipeline':return stages;case 'targets':return targets.map((t,i)=>({...t,maxValue:c.goals?.[i]||t.maxValue}));case 'records':case 'observations':return transactions;case 'flow':return flows.links.map(l=>({source:flows.nodes[l.source].name,target:flows.nodes[l.target].name,value:l.value}));case 'hierarchy':return hierarchy.children.flatMap(p=>p.children.map(d=>({channel:p.name,category:d.name,value:d.value})));case 'scores':return radarData.map(d=>({period:d.label,...d.values}));case 'activity':return heatmap.flatMap(w=>w.bins.map(d=>({date:d.date.toLocaleDateString('en-GB'),orders:d.count})));default:return [{source:'Synthetic stream',status:'Use Start / Pause in the chart'}]}}
function headline(c,state){if(['forbidden','reconciling','partial'].includes(state))return {value:'—',caption:{forbidden:'You do not have access to this dataset',reconciling:'Reconciliation in progress',partial:'Incomplete result · aggregate withheld'}[state]};if(state==='scalar'&&!datasets[c.dataset].families.includes('number')&&c.family!=='gauge')return {value:'—',caption:'No verified summary for this dataset'};if(['loading','unavailable'].includes(state))return {value:'—',caption:state==='loading'?'Loading verified data':'Data unavailable · retry required'};if(state==='empty')return {value:'0',caption:'No activity in selected period'};if(c.dataset==='pipeline')return {value:'126',caption:'Orders from 420 enquiries · 30% conversion'};if(['records','observations'].includes(c.dataset))return {value:'12',caption:'Sample transactions'};if(c.dataset==='activity')return {value:heatmap.flatMap(w=>w.bins).reduce((a,b)=>a+b.count,0).toLocaleString(),caption:'Orders · 5 Jul–26 Sep 2026'};if(c.dataset==='scores')return {value:'79.2 / 100',caption:'Average normalized target score'};if(c.dataset==='stream')return {value:'Simulated live',caption:'Sales / minute · synthetic events'};return {value:money(salesTotal),caption:'1–14 Sep 2026 · PKR'};}
function DataTable({c}){const rows=rawRows(c),keys=Object.keys(rows[0]).filter(k=>!['color','name'].includes(k));return <details className="data-details"><summary>View data · {rows.length} rows</summary><div className="table-scroll"><table><thead><tr>{keys.map(k=><th key={k}>{nice(k)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{keys.map(k=><td key={k}>{typeof r[k]==='number'?r[k].toLocaleString():String(r[k]??'—')}</td>)}</tr>)}</tbody></table></div></details>}
function Editor({c,setC,onSave,onCancel}){const change=(k,v)=>setC(d=>({...d,[k]:v}));return <aside className="editor"><div className="editor-heading"><h2>Edit Sales card</h2><span>Draft</span></div><p className="hint">Change the question, then its presentation.</p>
 <Field label="Card title" id="title"><input id="title" value={c.title} maxLength={60} onChange={e=>change('title',e.target.value)}/></Field>
 <Field label="Sales dataset" id="dataset"><select id="dataset" value={c.dataset} onChange={e=>setC(chooseDataset(c,e.target.value))}>{Object.entries(datasets).map(([k,d])=><option key={k} value={k}>{d.label}</option>)}</select></Field><p className="dataset-note">{datasets[c.dataset].note}</p>
 <Field label="Visualization" id="family"><select id="family" value={c.family} onChange={e=>setC(chooseFamily(c,e.target.value))}>{Object.entries(families).map(([k,d])=><option key={k} value={k} disabled={!datasets[c.dataset].families.includes(k)}>{d.label}{!datasets[c.dataset].families.includes(k)?' — needs '+datasets[d.data].label:''}</option>)}</select></Field>
 <Field label="Visual variant" id="variant"><select id="variant" value={c.variant} onChange={e=>change('variant',e.target.value)}>{families[c.family].variants.map(v=><option key={v} value={v} disabled={!variantAllowed(c,v)}>{nice(v)}{!variantAllowed(c,v)?v==='comparison'?' — needs comparable history':' — needs target dataset':''}</option>)}</select></Field>
 <Field label="Card shape / size" id="size"><select id="size" value={c.size} onChange={e=>setC(d=>chooseSize(d,e.target.value))}>{Object.entries(sizes).map(([k,s])=><option key={k} value={k} disabled={!sizeAllowed(c,k)}>{s.label}{!sizeAllowed(c,k)?' · no scalar summary':k==='full'?' · all available columns':k==='tile'||k==='strip'?' · number only':''}</option>)}</select></Field>
 {c.size==='custom'&&<><Field label={`Preferred width: ${c.span} / 12 columns`} id="span"><input id="span" type="range" min="2" max="12" value={c.span} onChange={e=>change('span',+e.target.value)}/></Field><Field label={`Card height: ${c.rows} rows`} id="rows"><input id="height" type="range" min="1" max="16" step="1" value={c.rows} onChange={e=>change('rows',+e.target.value)}/></Field></>}
 {controls(c).color&&<Field label="Chart color" id="color"><select id="color" value={c.color} onChange={e=>change('color',e.target.value)}><option value="#078578">Teal</option><option value="#5279bd">Blue</option><option value="#ba773e">Copper</option></select></Field>}
 {controls(c).compare&&<label className="check"><input type="checkbox" checked={c.compare} onChange={e=>change('compare',e.target.checked)}/>Compare previous period</label>}
 {['area','line','composed'].includes(c.family)&&<label className="check"><input type="checkbox" checked={c.grid} onChange={e=>change('grid',e.target.checked)}/>Show plot grid</label>}
 {controls(c).legend&&<label className="check"><input type="checkbox" checked={c.legend} onChange={e=>change('legend',e.target.checked)}/>Show legend</label>}
 {c.dataset==='target'&&<Field label="Sales target (Rs)" id="target"><input id="target" type="number" min="1" value={c.target} onChange={e=>change('target',Number(e.target.value))}/></Field>}
 <details className="advanced"><summary>Motion and loading</summary><label className="check"><input type="checkbox" checked={c.motion} onChange={e=>change('motion',e.target.checked)}/>Animate charts</label><Field label="Loading presentation" id="loading"><select id="loading" value={c.loading} onChange={e=>change('loading',e.target.value)}><option value="auto">Automatic for chart family</option><option value="area-pulse">BKLIT area · pulse</option><option value="area-sweep">BKLIT area · sweep</option><option value="line-pulse">BKLIT line · pulse</option><option value="line-sweep">BKLIT line · sweep</option><option value="bars">BKLIT columns</option><option value="cells">BKLIT heatmap cells</option><option value="skeleton">Neutral card skeleton</option></select></Field><p className="hint">Overrides are for evaluating loaders. Production uses a family-compatible default. Reduced motion uses a static state.</p></details>
 {!validate(c)&&<p role="alert" className="validation">Check the title, target and compatible presentation settings.</p>}
 <div className="editor-actions"><button className="primary" disabled={!validate(c)} onClick={onSave}>Save card</button><button onClick={onCancel}>Cancel</button><button onClick={()=>setC({...defaults})}>Reset draft</button></div></aside>}
function App(){const [saved,setSaved]=useState(readSaved),[draft,setDraft]=useState(saved),[editing,setEditing]=useState(true),[notice,setNotice]=useState(''),[state,setState]=useState('ready'),[nav,setNav]=useState(false),[panel,setPanel]=useState(false),[viewport,setViewport]=useState('fluid'),[replay,setReplay]=useState(0),[grid,setGrid]=useState(true);const [shellRef,shellW]=useWidth(),[boardRef,boardW]=useWidth();const c=editing?draft:saved;
 const navOverlay=nav&&shellW<900,navSpace=nav?(navOverlay?56:200):56,panelOverlay=panel&&(shellW-navSpace-250-40<720),panelSpace=panel&&!panelOverlay?250:0;const g=geometry(c,boardW),h=headline(c,state);
 const selectFamily=f=>{setEditing(true);setDraft(d=>chooseFamily(editing?d:saved,f));setState('ready');setNotice('');};
 const selectVariant=variant=>{if(!variantAllowed(c,variant))return;setDraft({...c,variant});setEditing(true);setState('ready');setNotice('Variant applied to preview. Save card to keep this choice.');};
 const save=()=>{if(!validate(draft))return;const next={...draft,title:draft.title.trim()};setSaved(next);setEditing(false);try{localStorage.setItem('venqore-sales-studio-v2',JSON.stringify(next));setNotice('Saved in this browser. Production persistence is described below.')}catch{setNotice('Applied this session; local storage unavailable.')}};
 const variantCount=Object.values(families).reduce((a,f)=>a+f.variants.length,0);
 return <><header className="page-header"><a className="brand" href="#">VenQore <span>/ Sales card studio</span></a><a href="#production">Production notebook ↓</a></header><main><section className="intro"><div><span className="pill">BKLIT source · React · Offline demo</span><h1>One card system.<br/>Room for every useful question.</h1><p>Choose a Sales question, explore its chart variants, then test the card in a real-width shell. Every number here is labeled mock data.</p></div><div className="scope"><b>{Object.keys(families).length} view families</b><span>{variantCount} named variants</span><span>9 size modes, including custom</span><small>Candlestick and maps excluded</small></div></section>
 <section className="family-library" aria-label="Chart family library"><div className="section-label"><h2>1. Choose a chart family</h2><span>Choosing a family switches to its required sample dataset.</span></div><div className="family-buttons">{Object.entries(families).map(([key,f])=><button key={key} aria-pressed={c.family===key} onClick={()=>selectFamily(key)}><span>{f.label}</span><small>{f.variants.length} variants</small></button>)}</div><div className="variant-picker"><div className="section-label"><h2>2. Choose a {families[c.family].label.toLowerCase()} variant</h2><span>Updates the preview immediately · Save card to keep your choice</span></div><div className="variant-buttons" role="group" aria-label={`${families[c.family].label} variants`}>{families[c.family].variants.map(v=><button key={v} aria-pressed={c.variant===v} disabled={!variantAllowed(c,v)} onClick={()=>selectVariant(v)}><span>{nice(v)}</span>{!variantAllowed(c,v)&&<small>{v==='comparison'?'Select Daily sales in the editor':'Select Sales vs target in the editor'}</small>}</button>)}</div></div></section>
 <div className="workbench-toolbar"><p><strong>{editing?'Editing draft':'Saved card'}</strong> · {datasets[c.dataset].label}</p><button onClick={()=>{if(editing){setDraft(saved);setEditing(false)}else{setDraft(saved);setEditing(true)}}}>{editing?'Hide editor / discard draft':'Edit card'}</button></div>
 <div className={'workbench '+(!editing?'editor-closed':'')}>{editing&&<Editor c={draft} setC={setDraft} onSave={save} onCancel={()=>{setDraft(saved);setEditing(false);setNotice('Draft discarded.')}}/>}<section className="preview-panel"><div className="shell-controls"><label>Preview width<select aria-label="Preview width" value={viewport} onChange={e=>setViewport(e.target.value)}><option value="fluid">Available space</option><option value="1440">Up to 1440px</option><option value="1024">Up to 1024px</option><option value="768">Up to 768px</option><option value="390">390px</option><option value="360">360px</option></select></label><button aria-pressed={nav} onClick={()=>setNav(!nav)}>Left sidebar</button><button aria-pressed={panel} onClick={()=>setPanel(!panel)}>Right panel</button><button aria-pressed={grid} onClick={()=>setGrid(!grid)}>12-column guides</button></div>
 <div className="shell-boundary" style={{maxWidth:viewport==='fluid'?'100%':Number(viewport)}}><div className="shell" ref={shellRef} style={{gridTemplateColumns:`${navSpace}px minmax(0,1fr) ${panelSpace}px`}}>
 <nav className={'sim-nav '+(navOverlay?'overlay':'')+(nav?' expanded':'')} aria-label="Simulated navigation"><strong>VQ</strong>{navOverlay&&<button onClick={()=>setNav(false)} aria-label="Close navigation overlay">×</button>}<span>▦ {nav&&'Overview'}</span><span>▤ {nav&&'Sales'}</span><span>▧ {nav&&'Inventory'}</span><span>⚙ {nav&&'Settings'}</span></nav>
 <div className="sim-main"><div className="sim-header"><div><strong>Business overview</strong><small>Mock Sales workspace</small></div><button aria-label="Replay chart animation" onClick={()=>setReplay(n=>n+1)}>↻ Replay</button></div><div className={'board '+(grid?'with-guides':'')} ref={boardRef}>
 <AutoCard g={g} className={(c.family==='number'?'number-card ':'')+(c.size==='strip'?'strip-card':'')+(g.rows===1?' one-row-card':'')} style={{'--chart-line-primary':c.color}} data-family={c.family} data-variant={c.variant}>
 <div className="card-header"><div><span>{c.title||'Sales'}</span><small>{datasets[c.dataset].label}</small></div><span className="mock-badge">Sample</span></div><div className="headline"><strong>{h.value}</strong><span>{h.caption}</span></div>
 {state==='stale'&&<p className="dataset-note" role="status">Last known sample · 14 Sep 2026, 14:00 PKT. Refresh failed; these values may have changed.</p>}<PlotBoundary identity={`${c.family}-${c.variant}-${c.dataset}-${state}`}><SalesPlot key={`${c.family}-${c.variant}-${replay}`} c={c} width={g.width} height={g.height} state={state}/></PlotBoundary>
 {['ready','stale'].includes(state)&&c.family!=='number'&&<DataTable c={c}/>}
 </AutoCard></div><div className="layout-status" aria-live="polite"><b>{boardW}px board</b> · preferred {g.requested}/12 → rendered {g.span}/12 · {g.rows} rows / {g.cardHeight}px · gutter 24px<p>{g.rows!==g.requestedRows?`Requested ${g.requestedRows} rows; this view needs at least ${g.rows}. `:''}{g.requested!==g.span?'The card widened to protect its minimum readable width. Your saved preference did not change.':c.size==='full'?'Full width fills all remaining board columns, with or without side panels.':'The card uses its requested span in the available board.'}</p></div></div>
 {panel&&<aside className={'sim-side '+(panelOverlay?'overlay':'')}><div><strong>Activity panel</strong><button aria-label="Close right panel" onClick={()=>setPanel(false)}>×</button></div><p>Today’s work</p><span>3 orders awaiting dispatch</span><span>2 invoices need attention</span><span>Stock count completed</span><small>{panelOverlay?'Overlay: pushing would leave less than 720px for the board.':'Push mode: this panel participates in board sizing.'}</small></aside>}
 {(navOverlay||panelOverlay)&&<button className="scrim" aria-label="Close panel overlays" onClick={()=>{if(navOverlay)setNav(false);if(panelOverlay)setPanel(false)}}/>}
 </div></div>
 <div className="test-controls"><Field label="Test data state" id="state"><select id="state" value={state} onChange={e=>setState(e.target.value)}><option value="ready">Ready</option><option value="loading">Loading</option><option value="empty">Confirmed empty</option><option value="scalar">Only total available</option><option value="unavailable">Unavailable / request failed</option><option value="reconciling">Reconciling</option><option value="partial">Partial / incomplete</option><option value="stale">Stale / last known data</option><option value="forbidden">Permission denied</option></select></Field><button onClick={()=>setState('ready')}>Resolve / retry</button><p>These controls test behavior; they are not customer dashboard controls.</p></div>
 <p className="sizing-note">The shell is capped by the actual browser space. To test larger screens, widen the window or hide the editor. Current shell: {shellW}px. Nav: {navOverlay?'overlay':nav?'expanded / push':'rail'}. Right panel: {panel?panelOverlay?'overlay':'push':'closed'}.</p>
 </section></div><p className="save-status" role="status">{notice}</p>
 <section className="size-explanation"><h2>Size is a layout contract, not another chart implementation.</h2><div className="size-grid">{Object.entries(sizes).map(([key,s])=><article key={key}><strong>{s.label}</strong><span>{key==='custom'?'2–12 columns, 1–16 rows':`${s.span}/12 columns · ${s.rows} rows`}</span><small>{key==='tile'||key==='strip'?'Number-only. No wasted plotting space.':key==='full'?'All remaining width after panels.':key==='portrait'?'Vertical funnel or plot plus long legend.':'Widens when needed to remain readable.'}</small></article>)}</div><p>Complex views never shrink into a two-column tile. Selecting Tile or Strip keeps the same dataset and shows its verified scalar summary. These sizes are unavailable when that summary does not exist. Rows include the entire card: height = rows × 64 + (rows − 1) × 24. Complex views promote insufficient row requests to their readable minimum. Content is measured and the card grows by whole rows when needed. Cards never scroll; additional records are opened separately. The editor and data table remain separate from chart coordinates.</p></section>
 <EditorDemo DataView={DataTable}/>
 <ProductionNotes/>
 </main><footer>Prototype v2 · No production routes, data or saved dashboards were modified. Source: extras/bklit-ui/sales-studio/. Rebuild with build-sales-studio.mjs.</footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
