import React from 'react';
import {families,datasets} from './model';
const decisions=[
 ['Define what Sales means','Agree whether Sales is posted ledger revenue, invoiced sales, POS receipts, or collected cash. They differ. Set tax, discounts, returns, cancellations, delivery fees and recognition-date rules before combining charts.','Decision required: accounting/product owner'],
 ['One result envelope','Use schemaVersion, metricId, datasetKind, tenant/store scope, currency, timezone, period boundaries, granularity, generatedAt, freshness and completeness alongside data. Carry numerator/denominator and aggregation type for ratios.','Proposed API contract'],
 ['Unknown is not zero','Represent loading, ready, empty, partial, stale, reconciling, unavailable and forbidden separately. A null bucket is a gap unless the backend certifies a complete interval with zero activity. One observation is a point, not a flat time series.','Required before renderer migration'],
 ['Choose views from capabilities','Compute allowed families from data shape AND semantics: ordered time, mutually exclusive categories, cohort stages, target definitions, linked nodes or hierarchy. Intersect with role/plan access and supported size. Revalidate on the server; client menus are not authorization.','Shared versioned registry'],
 ['Separate siblings, combine deliberately','Sales total and sales history can share one visible card, but are separate reads today. Declare their dependency keys explicitly, batch by scope/period, and check matching units and completeness. Never infer a trend reading by string concatenation.','Adapter work'],
 ['Compare equivalent periods','Align local trading timezone, grain, closed/open days and elapsed time. Today so far should compare to the same elapsed window, not a whole previous day. A zero prior value shows “No comparable baseline”, never infinity percent.','Backend comparison policy'],
 ['Amounts and axes','Use decimal or integer minor-unit amounts on the server. Preserve currency and precision. Do not mix currencies without a documented conversion basis. Bars start at zero; signed returns stay signed. Pie/ring proportions require non-negative values.','Data and scale contract'],
 ['Targets are real records','A gauge needs target amount, owner, period, scope and version. Zero/missing target disables progress. Permit more than 100% text while the track saturates at 100%. Channel rings require one target per channel; never use category share as attainment.','Target storage required'],
 ['Funnels need cohorts','Supply ordered stages, counts, cohort/window and deduplication rules. Current stage inventory is not cohort conversion. If counts grow between stages, explain the semantics or reject a conversion funnel. Labels and values live outside narrow segments.','Pipeline adapter required'],
 ['Flows and hierarchies need structure','Sankey requires stable node IDs, valid links, non-negative amounts and conservation checks for the selected meaning. Sunburst requires a tree with leaf rollups, unique identities and no double counting. Do not invent either from a flat category list.','New contracts; not chart aliases'],
 ['Radar and scatter need units','Radar needs meaningful normalized dimensions and a documented denominator per score. Scatter needs paired observations with real X and Y meaning; this library’s time-scatter uses dates on X. Add a numeric X implementation before offering price-versus-margin.','Capability gating'],
 ['Heatmap and live are different products','Heatmap needs explicit row/column buckets, timezone, missing-vs-zero semantics and an accessible color legend. Live needs ordered event IDs, resume cursor, deduplication, late-event policy, backpressure, disconnection state and a pause control. Polling a scalar is not live history.','Backend work required'],
 ['Records remain records','Recent transactions need permission-aware pagination, stable IDs, sorting, formatting and drill-through links. Do not chart arbitrary receipt order. Only offer a trend after a deliberate aggregation query.','Table/feed family'],
 ['12 columns belong to available space','Measure the board after nav and side-panel allocation, not window width. Persist preferred span/shape/order; resolve a larger span when pixel floors demand it. Full width always means span 12 of the remaining board. Do not overwrite preferences when the screen narrows.','Responsive contract demonstrated above'],
 ['Predictable reflow, not holes','Pack cards in stable reading order with explicit row tracks and gutters. Span compatibility alone cannot guarantee hole-free packing. Test a multi-card board with portrait cards, removals, pinned positions and permission changes before selecting the final packing algorithm.','Open: packing prototype still required'],
 ['Panels have a budget','This workshop uses a 720px remaining-board budget: below that, secondary panels overlay; navigation overlays below 900px. These are proposed thresholds, not replacements for the existing 1216px shell rule. Validate against real shell widths, then centralize them.','Proposed; integrate with OneGlanceLayout'],
 ['Adaptive interiors','Keep header, plot, legend and footer separate inside a fixed row-span frame. Measure content and promote to additional whole rows instead of scrolling inside the card. Reserve axis margins before measuring the plot. Reduce tick count at narrow widths; abbreviate amounts with exact tooltip/table values. Circular charts retain their aspect ratio. Portrait charts gain vertical room; full-width rings do not stretch into ellipses.','Implemented in workshop'],
 ['Loading without false data','Use BKLIT pulse/sweep/column/cell loaders only as clearly marked placeholders. Reuse last-known values only with a stale timestamp. Request IDs/abort prevent an old period response from replacing a newer one. Never display a success-looking dummy series during reconciliation.','Renderer + request lifecycle'],
 ['Persistence and migration','Version card specs. Preserve reading_key, period, args, style and current layouts. Add explicit renderer variant and preferred size semantics; audit the spec migration against model/API serialization first. Convert copies, retain rollback data, and surface unsupported legacy choices instead of silently changing their meaning.','No production migration performed'],
 ['Editor transactions and failures','Keep a draft until Save; Cancel restores the saved card. Validate title, data capability, variant and size on both sides. Use dashboard revision / ETag to avoid overwriting another device; show failed saves and permit retry. Local storage is only this demo’s persistence.','API acceptance criteria'],
 ['Performance and accessibility','Use stable React keys and one measured layout pass; avoid rebuilding the board on hover. Batch reads, cache by tenant/filter/period, pause hidden/live charts and cap point counts. Preserve extrema when decimating. Provide keyboard legends, tabular values, non-color cues and reduced motion.','Acceptance criteria'],
 ['Do not delete older dashboards yet','Inventory active routes and tenant usage. Move the main dashboard behind a feature flag to the shared renderer and existing backend pipeline. Migrate saved layouts separately; retire Workspace and legacy pages only after parity and rollback checks.','Rollout decision']
];
export default function ProductionNotes(){return <section className="production-notes" id="production"><div className="notes-heading"><span className="pill">Implementation notebook</span><h2>What this changes in the real dashboard</h2><p>The workshop tests presentation and sizing. These notes preserve the data, architecture and migration decisions it exposes. “Mock available” never means “production ready”.</p></div>
 <div className="evidence"><h3>Verified in the current source</h3><ul><li><code>Pages/NewDashboard.jsx</code> rebuilds the board with HTML strings and mounts its own chart functions. The modular React chart path is separate.</li><li><code>Dashboard/chartRegistry.js</code> maps several names to generic series/breakdown renderers. Its comments mark live line, scatter, radar and Sankey as not offered by current shape legality.</li><li><code>MeasureEngine.php</code> returns <code>value</code> for <code>core.revenue</code> and <code>points</code> for <code>core.revenue_trend</code>. Revenue is read from <code>gl.sales_revenue</code>; payment breakdown is a separate reading.</li><li><code>Dashboard/charts/kit.jsx → padSeries()</code> extends sparse series to flat lines. The active page also has scalar-to-series fallbacks. Review both; constant balances and period sales flows require different rules.</li><li><code>DashboardSanitizer.php</code> already checks reading access, period, chart legality and geometry. It currently coerces illegal choices; new editor saves should return clear validation errors.</li><li><code>DashboardCard.php</code> persists reading, period, granularity, args, style and geometry. <code>resources/layout-law.json</code> is shared by PHP and JavaScript. Extend these coherently rather than adding a third layout store.</li></ul><p className="hint">Read-only source inspection. Actual production API responses, accounting reconciliation and database migrations remain unverified.</p></div>
 <h3>Capability matrix</h3><div className="table-scroll"><table><thead><tr><th>Dataset contract</th><th>Compatible views</th><th>What must exist</th></tr></thead><tbody>{Object.entries(datasets).map(([key,d])=><tr key={key}><td>{d.label}</td><td>{d.families.map(f=>families[f].label).join(', ')}</td><td>{d.note}</td></tr>)}</tbody></table></div>
 <h3>Decisions and open work</h3><div className="decision-grid">{decisions.map(([title,body,status])=><article key={title}><h4>{title}</h4><p>{body}</p><small>{status}</small></article>)}</div>
 <h3>Coverage record — what is accounted for</h3><div className="table-scroll"><table><thead><tr><th>Requirement</th><th>Workshop behavior</th><th>Still required for production</th></tr></thead><tbody>{[
 ['Reuse across 100 cards','Shared dataset registry, renderers and geometry; no 2,000 hand-built card combinations.','Each metric needs a definition, authorized adapter, capability rules and reconciliation fixtures.'],
 ['Chart variety','14 BKLIT chart families plus number and records; 61 named variants.','Audit each upstream option before exposing it; pin library version. Some palettes remain fixed.'],
 ['Useful editor','Save/cancel drafts; controls limited to supported views. Comparison needs history; progress needs a target.','Server validation, accessible focus behavior, API errors, revision conflicts and permissions.'],
 ['Tile through full width','9 size modes; custom height uses 1–16 whole rows. Rows are 64px with 24px gutters, matching the existing layout law. Tile preserves the dataset; no scalar means no tile.','Test multi-card placement, resize handles, drag keyboard support and layout migration.'],
 ['Readable data','Separate legend tracks, adaptive ticks, exact values in tables. Daily components reconcile with channel totals.','Long translations, RTL, extreme amounts, negative values, sparse intervals and low-contrast environments.'],
 ['Honest states','Ready, loading, empty, scalar-only, unavailable, reconciling, partial, stale and forbidden demos. Partial hides unverified aggregates; stale is timestamped.','Real completeness maps, stale policy, request cancellation, reconnect logic and server-side access enforcement.'],
 ['Motion and loading','BKLIT loaders, replay, hover and explicit live simulation; static loading under reduced motion.','Full keyboard/screen-reader and motion audit across every composition.'],
 ['12-column shell and panels','Measured remaining board width; full-width means all 12 available columns. Side panels push or overlay.','Integrate shared production breakpoints and implement focus management; resolve simultaneous overlays.'],
 ['Production evidence','Existing renderer paths, scalar/series mismatch and shared layout registry documented above.','Connect one real Sales card behind a feature flag and reconcile actual API responses before rollout.'],
 ['Verification boundary','877 geometry/capability cases plus validation and rollup assertions pass. Prior browser checks exercised chart variants, loaders and panel widths.','Latest audit edits have build and model checks. Browser verification remains incomplete: the browser tool blocks file:// preview access. The popup editor and latest ring text sizing await visual checks. Visual approval remains outstanding.']
 ].map(([requirement,workshop,remaining])=><tr key={requirement}><td>{requirement}</td><td>{workshop}</td><td>{remaining}</td></tr>)}</tbody></table></div>
 <p>No finite prototype covers every possible dataset. Unsupported combinations must be rejected explicitly, and each new capability must bring its own data fixtures and acceptance checks. The open items above are rollout gates, not completed features.</p>
 <h3>Proposed card contract</h3><pre>{`// One definition + data adapters + shared renderers; not N bespoke cards.
{
  schemaVersion: 3, metricId: "sales",
  dataset: "history", readingKeys: ["core.revenue", "core.revenue_trend"],
  scope: { storeId, currency, timezone },
  period: { start, end, grain, compareMode },
  view: { family: "area", variant: "gradient", legend: true },
  layout: { preferredSpan: 8, shape: "landscape", order: 2 },
  revision: 17
}
// Server resolves authorized capabilities; viewport geometry is not saved.
// Target records and dataset dependencies are validated server-side.`}</pre>
 <h3>Production rollout gates</h3><ol><li>Agree Sales definition; trace each reading to its authoritative ledger/POS source and verify tenant boundaries.</li><li>Test adapters with zero, missing, negative, single-point, stale, partial and multi-currency fixtures; reconcile aggregates.</li><li>Connect one real Sales card behind a flag using the actual React/BKLIT renderer and existing dashboard API.</li><li>Test the editor, optimistic concurrency and layout round-trip at 360, 768, 1024, 1440 and 1920px, with both panels toggled.</li><li>Test mixed-card packing, RTL/long labels, large amounts, keyboard use, reduced motion, focus preservation and slow/offline responses.</li><li>Audit existing saved variants, migrate copies with rollback, then expand by dataset family.</li></ol>
 <h3>Reference and scope</h3><p>The chart families use the local downloaded BKLIT source. See the <a href="https://bklit.com/charts" target="_blank" rel="noreferrer">BKLIT gallery</a>, <a href="https://bklit.com/charts/area-chart" target="_blank" rel="noreferrer">area loading examples</a>, and <a href="https://bklit.com/charts/funnel-chart" target="_blank" rel="noreferrer">funnel variations</a>. Candlestick and choropleth are excluded as requested. Sankey is marked pre-alpha upstream: pin the source version and test before production adoption.</p><p>This is a finite capability prototype, not a claim that every upstream Studio setting is implemented. Family-specific variants are listed in the editor. Geometry, aliases and loaders should be versioned so future library upgrades cannot silently alter saved cards.</p>
 </section>}
