import { normalizePlan } from '@/lib/plans';

/**
 * VenQore Feature Matrix — Canonical 227 Feature Definitions (V11 Architecture)
 *
 * Synchronized with Database\Seeders\PlanFeatureMatrixSeeder.php.
 * Ghost Appendix A keys removed; canonical Appendix B keys registered.
 */

export const FEATURE_GROUPS = [
    {
        id: "onboarding",
        emoji: "\ud83d\ude80",
        label: "Onboarding & First Impression",
        description: "Landing page, trial, instant setup, and platform presence features.",
        features: [
            {"key":"demo_store","label":"Interactive Demo Store","type":"system","note":"Infrastructure \u2014 demo store toggle"},
            {"key":"free_trial_days","label":"Free Trial Days","type":"number","note":"Blank = 0 days; 14 = 14-day trial"},
            {"key":"instant_store_creator","label":"Instant Store Creator","type":"system","note":"Infrastructure \u2014 store creation engine"},
            {"key":"industry_seeding","label":"Smart Industry Archetype Seeding","type":"boolean"},
            {"key":"dark_theme","label":"\"Midnight Nebula\" Dark Theme","type":"boolean"},
            {"key":"light_theme","label":"Harmonious Light Theme","type":"boolean"},
            {"key":"multi_store_hub","label":"Multi-Store Hub Dashboard","type":"boolean"},
            {"key":"multi_store_roles","label":"Granular Multi-Store User Roles","type":"boolean"},
            {"key":"cashier_pin_login","label":"Instant Cashier PIN Login","type":"boolean"},
            {"key":"device_adaptive","label":"Device-Adaptive Layouts","type":"boolean"},
            {"key":"pwa_install","label":"Web App \/ PWA Install","type":"system"},
            {"key":"guided_setup_tour","label":"Self-Guiding Setup Tour","type":"boolean"},
            {"key":"coupon_stacking","label":"Flexible Coupon Code Stacking","type":"boolean"},
            {"key":"platform_status_badge","label":"Platform Live Status Badge","type":"boolean"},
            {"key":"system_cache_refresher","label":"System Cache Refresher","type":"boolean"},
            {"key":"owner_profile_card","label":"Owner Profile Card","type":"boolean"},
            {"key":"one_click_system_wipe","label":"One-Click System Wipe","type":"boolean"},
            {"key":"smtp_mail","label":"Custom SMTP Mail Server","type":"boolean"},
            {"key":"sms_gateway","label":"SMS Gateway Integrations","type":"boolean"},
        ],
    },
    {
        id: "core_limits",
        emoji: "\u26a1",
        label: "Core Limits & Quotas",
        description: "Commercial scale fences, SKU capacity, staff seats, locations and register hardware.",
        features: [
            {"key":"sku_limit","label":"Product Catalogue Limit (SKUs)","type":"number","note":"500 Solo \u00b7 5k Starter \u00b7 25k Core \u00b7 250k Scale"},
            {"key":"staff_limit","label":"Full Staff Seats","type":"number","note":"1 Solo \u00b7 1 Starter \u00b7 5 Core \u00b7 25 Scale"},
            {"key":"locations","label":"Store Locations \/ Warehouses","type":"number","note":"1 Solo\/Starter\/Core \u00b7 10 Scale"},
            {"key":"location_limit","label":"Location Limit Alias","type":"number","note":"Enforced secondary location gate"},
            {"key":"registers","label":"Register Terminals (POS)","type":"number","note":"1 Solo \u00b7 2 Starter \u00b7 6 Core \u00b7 20 Scale"},
            {"key":"till_logins","label":"Till PIN Logins","type":"number","note":"2 on Solo \u00b7 Unlimited on paid"},
            {"key":"devices_per_seat","label":"Hardware Devices per Seat","type":"number","note":"2 Solo \u00b7 3 Starter\/Core \u00b7 5 Scale"},
            {"key":"visible_history_days","label":"Visible History Days","type":"number","note":"30 days on Solo \u00b7 Unlimited on paid"},
            {"key":"transactions_per_month","label":"Monthly Transactions Limit","type":"number","note":"100 on Solo \u00b7 Unlimited on paid"},
            {"key":"service_jobs_per_month","label":"Monthly Service Jobs","type":"number","note":"20 on Solo \u00b7 Unlimited on paid"},
        ],
    },
    {
        id: "security",
        emoji: "\ud83d\udee1\ufe0f",
        label: "Security, Audit & Granular Roles",
        description: "Activity logs, tamper-evident audit trails, and granular RBAC roles.",
        features: [
            {"key":"security_activity_log","label":"Security Activity Log","type":"boolean","note":"Audit log of staff & login actions"},
            {"key":"audit_trail","label":"Immutable Audit Trail","type":"boolean","note":"Financial and inventory mutation audit log"},
            {"key":"custom_roles","label":"Granular Custom Roles & Permissions","type":"boolean","note":"Create bespoke permission sets"},
        ],
    },
    {
        id: "pos",
        emoji: "\ud83d\uded2",
        label: "POS & Supercharged Checkout",
        description: "Checkout terminal, scanner, printing, and payment features.",
        features: [
            {"key":"pos","label":"POS Terminal Module","type":"boolean","note":"Core point-of-sale interface"},
            {"key":"barcode_scanner","label":"Instant Barcode Scanner Integration","type":"boolean"},
            {"key":"imei_scanner","label":"Unique Serial & IMEI Scanner","type":"boolean"},
            {"key":"serial_tracking","label":"Serial Number Tracking","type":"boolean","note":"Per-item serial lifecycle tracking"},
            {"key":"keyboard_hotkeys","label":"High-Speed Keyboard-First Checkout","type":"boolean"},
            {"key":"senior_mode","label":"Accessibility \"Senior Mode\" Toggle","type":"boolean"},
            {"key":"high_contrast_colors","label":"High-Contrast Price\/Qty Color Coding","type":"boolean"},
            {"key":"profit_peek","label":"Owner \"Profit Peek\" Swipe","type":"boolean"},
            {"key":"cart_tabs_limit","label":"Multi-Tab Customer Checkout","type":"number","note":"Max parallel cart tabs"},
            {"key":"park_recall","label":"Park & Recall (Hold Bill)","type":"boolean"},
            {"key":"inflight_product_creation","label":"In-Flight Product Creation","type":"boolean"},
            {"key":"cart_session_protection","label":"Cart Rescue & Session Protection","type":"boolean"},
            {"key":"contextual_qty_modifiers","label":"Contextual Quantity Modifiers","type":"boolean"},
            {"key":"auto_customer_discounts","label":"Automatic Customer Discounts","type":"boolean"},
            {"key":"fuzzy_product_finder","label":"Typo Fuzzy Finder (Product Search)","type":"boolean"},
            {"key":"auto_cash_rounding","label":"Automatic Cash Rounding","type":"boolean"},
            {"key":"split_payments","label":"Multi-Account Split Payments","type":"boolean"},
            {"key":"daily_cash_audit","label":"Daily Cash Register Audit","type":"boolean"},
            {"key":"silent_webusb_printing","label":"Silent WebUSB Thermal Printing","type":"boolean"},
            {"key":"receipt_cutline_padding","label":"Receipt Cut-Line Padding","type":"boolean"},
            {"key":"custom_thermal_widths","label":"Custom Thermal Roll Widths (80\/58mm)","type":"boolean"},
            {"key":"dynamic_accent_colors","label":"Dynamic Accent Colors on Docs","type":"boolean"},
            {"key":"invoice_column_toggles","label":"Column Toggles on Invoices","type":"boolean"},
            {"key":"amount_to_words","label":"Dynamic Amount-to-Words Translation","type":"boolean"},
            {"key":"receipt_qr_code","label":"Verification QR Code Generation","type":"boolean"},
            {"key":"branded_receipt_sync","label":"Branded Receipt Sync (Logo\/Header)","type":"boolean"},
            {"key":"pos_negative_stock_alert","label":"POS Negative Stock Alert Badge","type":"boolean"},
            {"key":"negative_stock_lock","label":"Negative Stock Sales Lock","type":"boolean"},
            {"key":"service_fee_additions","label":"Dynamic Service Fee Additions","type":"boolean"},
            {"key":"auto_vat_gst","label":"Automatic VAT\/GST Calculations","type":"boolean"},
            {"key":"custom_charge_toggle","label":"Quick Custom Charge Toggle","type":"boolean"},
            {"key":"fuzzy_customer_lookup","label":"Fuzzy Customer Name Lookup","type":"boolean"},
            {"key":"recent_invoices_panel","label":"Recent Invoices List","type":"boolean"},
            {"key":"cashier_change_helper","label":"Cashier Change Helper","type":"boolean"},
            {"key":"barcode_label_print","label":"Barcode Label Printing Factory","type":"boolean"},
            {"key":"label_qr_codes","label":"Dynamic Label QR Codes","type":"boolean"},
            {"key":"barcode_label_factory","label":"Custom Label Designer Factory","type":"boolean"},
        ],
    },
    {
        id: "invoicing",
        emoji: "\ud83e\uddfe",
        label: "Invoicing, Customer Khata & Receivables",
        description: "Customer credit tracking, invoicing, loyalty, and debt collection.",
        features: [
            {"key":"customer_khata","label":"Digital Customer Khata Ledger","type":"boolean"},
            {"key":"customer_payments_log","label":"Customer Payments Log","type":"boolean"},
            {"key":"customer_statements","label":"Monthly Customer Statements","type":"boolean"},
            {"key":"aged_receivables","label":"Aged Receivables (30\/60\/90+ Days)","type":"boolean"},
            {"key":"credit_limit_rules","label":"Customer Credit Limit Enforcer","type":"boolean"},
            {"key":"multi_payment_invoices","label":"Multi-Payment Invoices (Partial\/Milestone)","type":"boolean"},
            {"key":"customer_payment_alloc","label":"FIFO Invoice Payment Allocation","type":"boolean"},
            {"key":"anniversary_tracker","label":"Birthday & Anniversary Tracker","type":"boolean"},
            {"key":"customer_ltv_score","label":"Customer Lifetime Value (LTV) Badge","type":"boolean"},
            {"key":"customer_wallet","label":"Customer Prepaid Wallet \/ Store Credit","type":"boolean"},
            {"key":"loyalty_points","label":"Loyalty Points Engine","type":"boolean"},
            {"key":"digital_gift_cards","label":"Digital Gift Cards System","type":"boolean"},
            {"key":"marketing_campaigns","label":"SMS\/Email Marketing Campaigns","type":"boolean"},
            {"key":"wholesale_pricing","label":"Tiered B2B Wholesale Pricing","type":"boolean"},
            {"key":"b2b_proposal_builder","label":"B2B Quotation & Proposal Builder","type":"boolean"},
            {"key":"quotation_conversion","label":"One-Click Quote-to-Invoice Conversion","type":"boolean"},
            {"key":"inflight_session_recovery","label":"Invoice Draft Recovery","type":"boolean"},
            {"key":"tax_inclusive_exclusive","label":"Tax-Inclusive vs Exclusive Pricing Toggle","type":"boolean"},
            {"key":"b2b_margin_displayer","label":"Live Margin & Profit Display on Invoices","type":"boolean"},
            {"key":"sales_return_vouchers","label":"Sales Return Credit Vouchers","type":"boolean"},
            {"key":"b2b_invoice_designer","label":"B2B Commercial Invoice Template","type":"boolean"},
            {"key":"pre_sales_reservation","label":"Pre-Sales Stock Reservation","type":"boolean"},
            {"key":"refund_reason_analysis","label":"Refund Reason Analysis","type":"boolean"},
            {"key":"tax_exempt_customers","label":"Tax-Exempt Customer Classification","type":"boolean"},
            {"key":"customer_address_book","label":"Multi-Address Book per Customer","type":"boolean"},
            {"key":"a4_invoice_pdf","label":"Standard A4 PDF Invoices","type":"boolean"},
            {"key":"letter_size_invoice","label":"US Letter Size Invoice Option","type":"boolean"},
            {"key":"outstanding_balance_grid","label":"Outstanding Balance Grid","type":"boolean"},
            {"key":"payment_due_dates","label":"Custom Payment Due Dates","type":"boolean"},
            {"key":"overdue_highlights","label":"Visual Overdue Invoice Highlights","type":"boolean"},
            {"key":"lump_sum_payments","label":"Lump-Sum Payment Distribution","type":"boolean"},
            {"key":"partial_payment_indicator","label":"Partial Payment Progress Indicators","type":"boolean"},
            {"key":"unified_party_ledger","label":"Unified Customer\/Vendor Cross-Ledger","type":"boolean"},
            {"key":"recurring_invoices","label":"Automated Recurring Invoices","type":"boolean"},
            {"key":"recurring_invoicing","label":"Recurring Invoicing Engine","type":"boolean"},
            {"key":"invoice_reminders","label":"Overdue Invoice Auto-Reminders","type":"boolean"},
        ],
    },
    {
        id: "procurement",
        emoji: "\ud83d\udce6",
        label: "Procurement, Suppliers & Payables",
        description: "Purchase orders, supplier khata, landed costs, and supplier payments.",
        features: [
            {"key":"supplier_khata","label":"Supplier Khata Ledger","type":"boolean"},
            {"key":"delayed_supplier_payments","label":"Post-Dated Supplier Payment Schedules","type":"boolean"},
            {"key":"supplier_statements","label":"Supplier Account Statements","type":"boolean"},
            {"key":"aged_payables","label":"Aged Payables (30\/60\/90+ Days)","type":"boolean"},
            {"key":"installment_payments","label":"Supplier Installment Plans","type":"boolean"},
            {"key":"purchase_orders","label":"Full Purchase Order Workflow","type":"boolean"},
            {"key":"partial_shipments","label":"Partial Goods Received (GRN)","type":"boolean"},
            {"key":"supplier_debit_notes","label":"Supplier Debit Notes","type":"boolean"},
            {"key":"auto_cost_adjuster","label":"Automated Inventory Cost Adjuster","type":"boolean"},
            {"key":"cost_price_fluctuator","label":"Cost Price Fluctuation Alerts","type":"boolean"},
            {"key":"supplier_lead_time","label":"Supplier Lead Time Tracker","type":"boolean"},
            {"key":"landing_costs","label":"Landed Cost Distribution (Freight\/Customs)","type":"boolean"},
            {"key":"suppliers_directory","label":"Suppliers Directory & Contacts","type":"boolean"},
            {"key":"supplier_sku_mapping","label":"Supplier SKU to Internal SKU Mapping","type":"boolean"},
            {"key":"inbound_expiry_tracking","label":"Inbound Expiry Date Verification","type":"boolean"},
            {"key":"purchase_returns","label":"Purchase Return & Refund Manager","type":"boolean"},
            {"key":"auto_po_generation","label":"Auto-Generate PO from Low Stock","type":"boolean"},
            {"key":"bulk_supplier_payments","label":"Bulk Supplier Payment Allocations","type":"boolean"},
            {"key":"purchase_pdf_upload","label":"Attach Supplier Invoice PDFs to POs","type":"boolean"},
            {"key":"reconciled_bank_payments","label":"Reconciled Bank Payment Logs","type":"boolean"},
            {"key":"tax_inclusive_procurement","label":"Tax-Inclusive Supplier Invoicing","type":"boolean"},
            {"key":"supplier_outstanding_alerts","label":"Supplier Payment Due Alerts","type":"boolean"},
            {"key":"supplier_refund_tracker","label":"Supplier Overpayment Refund Tracker","type":"boolean"},
            {"key":"custom_payment_terms","label":"Custom Vendor Payment Terms","type":"boolean"},
        ],
    },
    {
        id: "inventory",
        emoji: "\ud83c\udfed",
        label: "Inventory, Production & Manufacturing",
        description: "Multi-location inventory, FIFO valuation, Bill of Materials, and work orders.",
        features: [
            {"key":"stock_transfer","label":"Inter-Warehouse Stock Transfers","type":"boolean"},
            {"key":"product_variants","label":"Product Matrix Variants (Size\/Color)","type":"boolean"},
            {"key":"fifo_costing","label":"True FIFO Inventory Costing","type":"boolean"},
            {"key":"batch_tracking","label":"Batch \/ Lot Number Tracking","type":"boolean"},
            {"key":"batch_expiry","label":"Batch Expiry Date Guard","type":"boolean"},
            {"key":"stock_take_audit","label":"Full Stock-Take & Physical Count Audits","type":"boolean"},
            {"key":"disaster_claim","label":"Damaged \/ Lost Goods Write-Off Manager","type":"boolean"},
            {"key":"bill_of_materials","label":"Bill of Materials (BOM) Recipes","type":"boolean"},
            {"key":"production","label":"Production Runs & Assembly","type":"boolean"},
            {"key":"manufacturing","label":"Manufacturing Module","type":"boolean"},
            {"key":"auto_assembly_logic","label":"Automatic Recipe Deduction on Sale","type":"boolean"},
            {"key":"auto_assembly_checkout","label":"POS Auto-Assembly Composite Items","type":"boolean"},
            {"key":"production_simulator","label":"Production Cost & Yield Simulator","type":"boolean"},
            {"key":"recipe_history_archival","label":"Recipe Cost & Ingredient Version History","type":"boolean"},
            {"key":"product_history_timeline","label":"Product Stock Movement Audit Timeline","type":"boolean"},
            {"key":"category_management","label":"Nested Category & Brand Tree","type":"boolean"},
            {"key":"stock_levels_view","label":"Real-Time Multi-Branch Stock Levels","type":"boolean"},
            {"key":"low_stock_alerts","label":"Low Stock & Reorder Point Alerts","type":"boolean"},
            {"key":"uom_converter","label":"Unit of Measure (UOM) Conversion Matrix","type":"boolean"},
        ],
    },
    {
        id: "ecommerce_channels",
        emoji: "\ud83c\udf10",
        label: "E-Commerce, Multi-Branch & Channels",
        description: "Multi-branch operations, marketplace synchronization, and API\/Webhooks.",
        features: [
            {"key":"multi_branch","label":"Multi-Branch Operations Engine","type":"boolean","note":"Scale fence \u2014 multi-branch capability"},
            {"key":"woocommerce","label":"WooCommerce Two-Way Sync","type":"boolean","note":"Live catalog, stock, and order bridge"},
            {"key":"amazon_sync","label":"Amazon Marketplace Sync","type":"boolean"},
            {"key":"ebay_sync","label":"eBay Marketplace Sync","type":"boolean"},
            {"key":"tiktok_sync","label":"TikTok Shop Sync","type":"boolean"},
            {"key":"woocommerce_customer_reg","label":"WooCommerce Customer Registration Bridge","type":"boolean"},
            {"key":"woocommerce_stock_sync","label":"Instant Webhook Stock Sync to Store","type":"boolean"},
            {"key":"woocommerce_orders_bridge","label":"Automated Web Order Fulfillment Bridge","type":"boolean"},
            {"key":"web_catalog_toggles","label":"Selective Web-Catalog Visibility per SKU","type":"boolean"},
            {"key":"api_access","label":"REST API Access Token","type":"boolean"},
            {"key":"webhooks","label":"Real-Time Outgoing Event Webhooks","type":"boolean"},
            {"key":"api_webhooks","label":"Full Developer API & Webhooks Access","type":"boolean"},
            {"key":"white_label","label":"White-Label Branding (Remove VenQore Badges)","type":"boolean"},
            {"key":"network_basic","label":"Basic Network Node Federation","type":"boolean"},
            {"key":"network_unlimited","label":"Unlimited Enterprise Network Nodes","type":"boolean"},
            {"key":"consolidated_reporting","label":"Consolidated Multi-Entity Financials","type":"boolean"},
            {"key":"vensync_command","label":"VenSync Multi-Channel Command Center","type":"boolean"},
        ],
    },
    {
        id: "accounting",
        emoji: "\ud83d\udcca",
        label: "Double-Entry Accounting & Finance",
        description: "General ledger, bank reconciliation, fixed asset depreciation, and compliance.",
        features: [
            {"key":"double_entry_ledger","label":"Double-Entry General Ledger (GL)","type":"boolean"},
            {"key":"cash_account_reconciliation","label":"Cash in Hand Reconciliation","type":"boolean"},
            {"key":"loan_ledger","label":"Commercial Loan & EMI Tracker","type":"boolean"},
            {"key":"inter_register_transfers","label":"Till-to-Bank Cash Transfers","type":"boolean"},
            {"key":"advance_allocation","label":"Advance Payment Multi-Invoice Allocation","type":"boolean"},
            {"key":"debit_credit_notes","label":"Formal Debit & Credit Notes Engine","type":"boolean"},
            {"key":"tax_summary_engine","label":"Real-Time Tax Liability Calculator","type":"boolean"},
            {"key":"expense_manager","label":"Operating Expense Category Manager","type":"boolean"},
            {"key":"charity_engine","label":"Automated Charity \/ Zakat Allocations","type":"boolean"},
            {"key":"petty_cash","label":"Petty Cash Voucher Register","type":"boolean"},
            {"key":"fixed_asset_depreciation","label":"Fixed Asset Depreciation Ledger","type":"boolean"},
            {"key":"fiscal_year_closing","label":"Fiscal Year-End Closing & Balance Carry","type":"boolean"},
            {"key":"bank_reconciliation","label":"Bank Statement Reconciliation Engine","type":"boolean"},
            {"key":"e_invoicing","label":"Electronic Invoicing & Fiscal Signatures","type":"boolean"},
            {"key":"fund_management","label":"Internal Capital & Partner Capital Accounts","type":"boolean"},
            {"key":"google_drive_backup","label":"Automated Google Drive Encrypted Backups","type":"boolean"},
            {"key":"adviser_seat","label":"External Accountant \/ CPA Read Seat","type":"boolean"},
        ],
    },
    {
        id: "ai_signals",
        emoji: "\ud83e\udde0",
        label: "AI, Signals & Intelligence",
        description: "Smart receipt OCR capture, conversational AI assistants, and growth forecasting.",
        features: [
            {"key":"ai_assistant","label":"Conversational AI POS Copilot","type":"boolean"},
            {"key":"smart_capture","label":"SmartCapture Optical Invoice Scanner","type":"boolean"},
            {"key":"hypersearch_byok","label":"HyperSearch BYOK (Bring Your Own Key)","type":"boolean"},
            {"key":"ai_credits_monthly","label":"Monthly AI Engine Credits","type":"number","note":"100 Solo \u00b7 500 Starter \u00b7 2000 Core \u00b7 10000 Scale"},
            {"key":"ai_scans_monthly","label":"Monthly SmartCapture OCR Scans","type":"number","note":"10 on Solo \u00b7 Unlimited on paid"},
            {"key":"ai_system_builder","label":"Autonomous Store Builder & Theme AI","type":"boolean"},
            {"key":"growth_engine","label":"Autonomous Growth Recommendations","type":"boolean"},
            {"key":"growth_signals","label":"Predictive Inventory Stockout Signals","type":"boolean"},
            {"key":"bulk_upload","label":"AI Multi-Format Product Importer (CSV\/Excel)","type":"boolean"},
            {"key":"live_chat_widget","label":"Real-Time Live Chat Customer Widget","type":"boolean"},
        ],
    },
    {
        id: "services_industry",
        emoji: "\ud83d\udee0\ufe0f",
        label: "Services, Work Orders & Industry Modules",
        description: "Job cards, repair ticketing, service contracts, and specialized retail verticals.",
        features: [
            {"key":"services","label":"Services & Labor Catalog","type":"boolean","note":"Service items with hourly\/fixed rates"},
            {"key":"service_jobs","label":"Service Job Cards & Status Board","type":"boolean"},
            {"key":"service_contracts","label":"Annual Maintenance Contracts (AMC)","type":"boolean"},
            {"key":"work_orders","label":"Internal Shop Work Orders","type":"boolean"},
            {"key":"optical_prescription","label":"Optometry Rx & Axis Measurement Matrix","type":"boolean"},
            {"key":"tailor_measurements","label":"Apparel & Bespoke Tailoring Measurements","type":"boolean"},
            {"key":"jewelry_metal_rates","label":"Precious Metals Daily Karat Rate Engine","type":"boolean"},
        ],
    },
    {
        id: "support_system",
        emoji: "\ud83e\udd1d",
        label: "Support, SLA & System Capabilities",
        description: "Support channel tiering, SLA, and lifetime platform infrastructure.",
        features: [
            {"key":"chat_support","label":"Priority In-App Chat Support","type":"boolean"},
            {"key":"whatsapp_reminders","label":"Automated WhatsApp Customer Reminders","type":"boolean"},
            {"key":"dedicated_account_manager","label":"Dedicated Customer Success Manager","type":"boolean"},
            {"key":"ltd","label":"AppSumo \/ LTD Lifetime Architecture Flag","type":"system","note":"System flag \u2014 lifetime account"},
        ],
    },
    {
        id: "reports_universal",
        emoji: "\ud83d\udcc8",
        label: "Reports & Analytics (Universal Access)",
        description: "All 23 comprehensive business reports are included on every plan under V11 \u00a71.1 Universal Architecture.",
        features: [
            {"key":"reports","label":"Reporting Complexity Tier","type":"select","note":"Basic on Solo \u00b7 Advanced on Starter\/Core\/Scale","options":["basic","advanced"]},
            {"key":"report_sales_records","label":"Sales Records Report","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_purchase_records","label":"Purchase Records Report","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_stock_records","label":"Stock Movement Records","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_stock_valuation","label":"FIFO Stock Valuation Report","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_profit_loss","label":"Income Statement (Profit & Loss)","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_cash_flow","label":"Cash Flow Statement","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_expenses","label":"Operating Expense Breakdown","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_tax","label":"Tax Liability & GST Audit Report","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_day_book","label":"Daily Journal \/ Day Book","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_party_records","label":"Customer & Vendor Party Directory","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_sales_analytics","label":"Deep Sales Trend & Peak Hours Analytics","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_profitability","label":"Item & Category Margin Profitability","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_discounts","label":"Discounting & Coupon Leakage Audit","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_aging","label":"Aged Debtors & Creditors Waterfall","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_balance_sheet","label":"Formal Balance Sheet","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_expense_analysis","label":"Overhead & OpEx Ratio Analysis","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_party_insights","label":"Customer Retention & Churn Analytics","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"owners_daily_pulse","label":"Owner Daily Pulse Dashboard Summary","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_ledger","label":"General Ledger Detail Audit","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_point_in_time","label":"Historical Point-in-Time Inventory","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_cross_party","label":"Cross-Party Balance Reconciliations","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_loans","label":"Loan & Amortization Schedule","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
            {"key":"report_export","label":"Universal CSV\/Excel\/PDF Batch Exporter","type":"boolean","note":"Included on every plan (V11 \u00a71.1)"},
        ],
    },
];

export const TOTAL_FEATURES = FEATURE_GROUPS.reduce((acc, g) => acc + g.features.length, 0);

export const FEATURE_DEFAULTS = {
    "demo_store": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "free_trial_days": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "0",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "instant_store_creator": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "industry_seeding": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "dark_theme": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "light_theme": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "multi_store_hub": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "multi_store_roles": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "cashier_pin_login": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "device_adaptive": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "pwa_install": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "guided_setup_tour": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "coupon_stacking": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "platform_status_badge": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "system_cache_refresher": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "owner_profile_card": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "one_click_system_wipe": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "smtp_mail": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "sms_gateway": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "security_activity_log": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "audit_trail": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "custom_roles": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "pos": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "barcode_scanner": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "imei_scanner": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "serial_tracking": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "keyboard_hotkeys": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "senior_mode": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "high_contrast_colors": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "profit_peek": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "cart_tabs_limit": {
        "solo": "5",
        "starter": "10",
        "core": "25",
        "scale": "50",
        "trial": "25",
        "ltd_1": "10",
        "ltd_2": "25",
        "ltd_3": "50"
    },
    "park_recall": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "inflight_product_creation": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "cart_session_protection": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "contextual_qty_modifiers": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "auto_customer_discounts": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "fuzzy_product_finder": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "auto_cash_rounding": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "split_payments": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "daily_cash_audit": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "silent_webusb_printing": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "receipt_cutline_padding": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "custom_thermal_widths": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "dynamic_accent_colors": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "invoice_column_toggles": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "amount_to_words": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "receipt_qr_code": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "branded_receipt_sync": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "pos_negative_stock_alert": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "negative_stock_lock": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "service_fee_additions": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "auto_vat_gst": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "custom_charge_toggle": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "fuzzy_customer_lookup": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "recent_invoices_panel": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "cashier_change_helper": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "barcode_label_print": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "label_qr_codes": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "barcode_label_factory": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "customer_khata": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "customer_payments_log": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "customer_statements": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "aged_receivables": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "credit_limit_rules": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "multi_payment_invoices": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "customer_payment_alloc": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "anniversary_tracker": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "customer_ltv_score": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "customer_wallet": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "loyalty_points": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "digital_gift_cards": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "marketing_campaigns": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "wholesale_pricing": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "b2b_proposal_builder": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "quotation_conversion": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "inflight_session_recovery": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "tax_inclusive_exclusive": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "b2b_margin_displayer": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "sales_return_vouchers": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "b2b_invoice_designer": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "pre_sales_reservation": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "refund_reason_analysis": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "tax_exempt_customers": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "customer_address_book": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "a4_invoice_pdf": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "letter_size_invoice": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "outstanding_balance_grid": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "payment_due_dates": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "overdue_highlights": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "lump_sum_payments": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "partial_payment_indicator": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "unified_party_ledger": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "recurring_invoices": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "invoice_reminders": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "supplier_khata": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "delayed_supplier_payments": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "supplier_statements": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "aged_payables": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "installment_payments": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "purchase_orders": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "partial_shipments": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "supplier_debit_notes": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "auto_cost_adjuster": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "cost_price_fluctuator": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "supplier_lead_time": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "landing_costs": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "suppliers_directory": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "supplier_sku_mapping": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "inbound_expiry_tracking": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "purchase_returns": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "auto_po_generation": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "bulk_supplier_payments": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "purchase_pdf_upload": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "reconciled_bank_payments": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "tax_inclusive_procurement": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "supplier_outstanding_alerts": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "supplier_refund_tracker": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "custom_payment_terms": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "locations": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "10",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "2",
        "ltd_3": "5"
    },
    "location_limit": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "10",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "2",
        "ltd_3": "5"
    },
    "stock_transfer": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "product_variants": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "fifo_costing": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "batch_tracking": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "batch_expiry": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "stock_take_audit": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "disaster_claim": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "bill_of_materials": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "production": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "manufacturing": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "auto_assembly_logic": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "auto_assembly_checkout": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "production_simulator": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "recipe_history_archival": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "product_history_timeline": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "category_management": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "stock_levels_view": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "low_stock_alerts": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "uom_converter": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "sku_limit": {
        "solo": "500",
        "starter": "5000",
        "core": "25000",
        "scale": "250000",
        "trial": "25000",
        "ltd_1": "5000",
        "ltd_2": "25000",
        "ltd_3": "50000"
    },
    "staff_limit": {
        "solo": "1",
        "starter": "1",
        "core": "5",
        "scale": "25",
        "trial": "5",
        "ltd_1": "1",
        "ltd_2": "2",
        "ltd_3": "5"
    },
    "till_logins": {
        "solo": "2",
        "starter": null,
        "core": null,
        "scale": null,
        "trial": null,
        "ltd_1": null,
        "ltd_2": null,
        "ltd_3": null
    },
    "registers": {
        "solo": "1",
        "starter": "2",
        "core": "6",
        "scale": "20",
        "trial": "6",
        "ltd_1": "2",
        "ltd_2": "4",
        "ltd_3": "10"
    },
    "devices_per_seat": {
        "solo": "2",
        "starter": "3",
        "core": "3",
        "scale": "5",
        "trial": "3",
        "ltd_1": "3",
        "ltd_2": "3",
        "ltd_3": "3"
    },
    "visible_history_days": {
        "solo": "30",
        "starter": null,
        "core": null,
        "scale": null,
        "trial": null,
        "ltd_1": null,
        "ltd_2": null,
        "ltd_3": null
    },
    "transactions_per_month": {
        "solo": "100",
        "starter": null,
        "core": null,
        "scale": null,
        "trial": null,
        "ltd_1": null,
        "ltd_2": null,
        "ltd_3": null
    },
    "service_jobs_per_month": {
        "solo": "20",
        "starter": null,
        "core": null,
        "scale": null,
        "trial": null,
        "ltd_1": null,
        "ltd_2": null,
        "ltd_3": null
    },
    "multi_branch": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "woocommerce": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "amazon_sync": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "ebay_sync": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "tiktok_sync": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "woocommerce_customer_reg": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "woocommerce_stock_sync": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "woocommerce_orders_bridge": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "web_catalog_toggles": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "api_access": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "webhooks": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "api_webhooks": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "white_label": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "network_basic": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "network_unlimited": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "consolidated_reporting": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "double_entry_ledger": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "cash_account_reconciliation": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "loan_ledger": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "inter_register_transfers": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "advance_allocation": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "debit_credit_notes": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "tax_summary_engine": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "expense_manager": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "charity_engine": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "petty_cash": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "fixed_asset_depreciation": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "fiscal_year_closing": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "bank_reconciliation": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "e_invoicing": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "fund_management": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "google_drive_backup": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "adviser_seat": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "reports": {
        "solo": "basic",
        "starter": "advanced",
        "core": "advanced",
        "scale": "advanced",
        "trial": "advanced",
        "ltd_1": "advanced",
        "ltd_2": "advanced",
        "ltd_3": "advanced"
    },
    "report_sales_records": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_purchase_records": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_stock_records": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_stock_valuation": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_profit_loss": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_cash_flow": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_expenses": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_tax": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_day_book": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_party_records": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_sales_analytics": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_profitability": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_discounts": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_aging": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_balance_sheet": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_expense_analysis": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_party_insights": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "owners_daily_pulse": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "report_ledger": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "report_point_in_time": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "report_cross_party": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "report_loans": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "report_export": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "ai_assistant": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "smart_capture": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "hypersearch_byok": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "ai_credits_monthly": {
        "solo": "100",
        "starter": "500",
        "core": "2000",
        "scale": "10000",
        "trial": "2000",
        "ltd_1": "500",
        "ltd_2": "2000",
        "ltd_3": "10000"
    },
    "ai_scans_monthly": {
        "solo": "10",
        "starter": null,
        "core": null,
        "scale": null,
        "trial": null,
        "ltd_1": null,
        "ltd_2": null,
        "ltd_3": null
    },
    "ai_system_builder": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "growth_engine": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "growth_signals": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "0"
    },
    "bulk_upload": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "live_chat_widget": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "services": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "service_jobs": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "service_contracts": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "optical_prescription": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "tailor_measurements": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "jewelry_metal_rates": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "work_orders": {
        "solo": "1",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "chat_support": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "dedicated_account_manager": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "1",
        "trial": "0",
        "ltd_1": "0",
        "ltd_2": "0",
        "ltd_3": "1"
    },
    "recurring_invoicing": {
        "solo": "1",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "vensync_command": {
        "solo": "0",
        "starter": "0",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "0",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "whatsapp_reminders": {
        "solo": "0",
        "starter": "1",
        "core": "1",
        "scale": "1",
        "trial": "1",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    },
    "ltd": {
        "solo": "0",
        "starter": "0",
        "core": "0",
        "scale": "0",
        "trial": "0",
        "ltd_1": "1",
        "ltd_2": "1",
        "ltd_3": "1"
    }
};

export const getFeatureDefault = (featureKey, planSlug) => {
    let baseSlug = normalizePlan(planSlug);
    if (baseSlug === 'ltd_1') baseSlug = 'starter';
    else if (baseSlug === 'ltd_2') baseSlug = 'core';
    else if (baseSlug === 'ltd_3') baseSlug = 'scale';

    if (['ltd_1', 'ltd_2', 'ltd_3'].includes(planSlug) && featureKey === 'transactions_per_month') {
        return null;
    }

    return FEATURE_DEFAULTS[featureKey]?.[baseSlug] ?? FEATURE_DEFAULTS[featureKey]?.[planSlug] ?? null;
};
